import type { StageSummary, AttractionDetail } from '../types/metrics';

export const STAGE_SUMMARIES: StageSummary[] = [
  {
    id: 'ATRACCION',
    order: 0,
    label: 'Atraccion',
    description: 'Visitantes que llegan a tu ecosistema digital desde todos los canales',
    mainKpi: { label: 'visitantes', value: 45000 },
    secondaryKpi: { label: 'canales activos', value: 8 },
    hasDetail: true,
  },
  {
    id: 'CAPTURA',
    order: 1,
    label: 'Captura',
    description: 'Visitantes que dejan sus datos y se convierten en leads',
    mainKpi: { label: 'leads', value: 8500 },
    secondaryKpi: { label: 'tasa conversion', value: 18.9, unit: '%' },
    hasDetail: false,
  },
  {
    id: 'NUTRICION',
    order: 2,
    label: 'Nutricion',
    description: 'Leads que interactuan con tu contenido y avanzan en el embudo',
    mainKpi: { label: 'MQLs', value: 3200 },
    secondaryKpi: { label: 'engagement rate', value: 37.6, unit: '%' },
    hasDetail: false,
  },
  {
    id: 'OPORTUNIDAD',
    order: 3,
    label: 'Oportunidad',
    description: 'Leads calificados listos para recibir una oferta',
    mainKpi: { label: 'SQLs', value: 850 },
    secondaryKpi: { label: 'pipeline value', value: 425000, unit: '$' },
    hasDetail: false,
  },
  {
    id: 'VENTAS',
    order: 4,
    label: 'Ventas',
    description: 'Oportunidades que se convierten en clientes de pago',
    mainKpi: { label: 'clientes', value: 450 },
    secondaryKpi: { label: 'ticket promedio', value: 2800, unit: '$' },
    hasDetail: false,
  },
  {
    id: 'ADOPCION',
    order: 5,
    label: 'Adopcion',
    description: 'Clientes que usan activamente tu producto o servicio',
    mainKpi: { label: 'activos', value: 400 },
    secondaryKpi: { label: 'activacion', value: 88.9, unit: '%' },
    hasDetail: false,
  },
  {
    id: 'EXPANSION',
    order: 6,
    label: 'Expansion',
    description: 'Clientes que compran mas productos o upgradean',
    mainKpi: { label: 'upsells', value: 120 },
    secondaryKpi: { label: 'revenue expansion', value: 30, unit: '%' },
    hasDetail: false,
  },
  {
    id: 'EVANGELIZACION',
    order: 7,
    label: 'Evangelizacion',
    description: 'Clientes que refieren nuevos prospectos activamente',
    mainKpi: { label: 'referidores', value: 85 },
    secondaryKpi: { label: 'referidos/mes', value: 340 },
    hasDetail: false,
  },
];

export const MOCK_ATTRACTION_DETAIL: AttractionDetail = {
  period: 'last_30_days',
  lastUpdated: '2026-03-14T03:15:00Z',
  organicSocial: {
    totals: { reach: 24500, engagement: 5800 },
    channels: [
      {
        slug: 'ig-organic',
        name: 'Instagram',
        channelType: 'social',
        metrics: [
          { name: 'reach', value: 12000 },
          { name: 'engagement', value: 3200, breakdown: { likes: 2000, comments: 800, shares: 0, saves: 400 } },
        ],
        sourceLabel: 'Instagram',
        connected: true,
      },
      {
        slug: 'yt-organic',
        name: 'YouTube',
        channelType: 'social',
        metrics: [
          { name: 'reach', value: 8500 },
          { name: 'engagement', value: 1800, breakdown: { likes: 1200, comments: 600 } },
        ],
        sourceLabel: 'YouTube',
        connected: true,
      },
      {
        slug: 'fb-organic',
        name: 'Facebook',
        channelType: 'social',
        metrics: [
          { name: 'reach', value: 4000 },
          { name: 'engagement', value: 800, breakdown: { reactions: 500, comments: 200, shares: 100 } },
        ],
        sourceLabel: 'Facebook',
        connected: true,
      },
    ],
  },
  ga4Search: {
    totals: { sessions: 1800, users: 1400 },
    channels: [
      {
        slug: 'google-organic',
        name: 'Google Organico',
        channelType: 'search',
        metrics: [
          { name: 'sessions', value: 1100 },
          { name: 'users', value: 850 },
        ],
        sourceLabel: 'Google Search',
        connected: true,
      },
      {
        slug: 'direct',
        name: 'Trafico Directo',
        channelType: 'direct',
        metrics: [
          { name: 'sessions', value: 450 },
          { name: 'users', value: 380 },
        ],
        sourceLabel: 'Direct',
        connected: true,
      },
      {
        slug: 'ai-search-organic',
        name: 'AI Search',
        channelType: 'search',
        metrics: [
          { name: 'sessions', value: 250 },
          { name: 'users', value: 170 },
        ],
        sourceLabel: 'AI Search',
        connected: true,
      },
    ],
  },
  paid: {
    totals: { reach: 12000, clicks: 3500, conversions: 120, spend: 8200 },
    channels: [
      {
        slug: 'meta-ads',
        name: 'Meta Ads',
        channelType: 'paid',
        metrics: [
          { name: 'reach', value: 5000 },
          { name: 'clicks', value: 1500 },
          { name: 'conversions', value: 55 },
          { name: 'spend', value: 3500, unit: 'currency', currency: 'USD' },
        ],
        sourceLabel: 'Meta Ads',
        connected: true,
      },
      {
        slug: 'google-ads',
        name: 'Google Ads',
        channelType: 'paid',
        metrics: [
          { name: 'reach', value: 4000 },
          { name: 'clicks', value: 1200 },
          { name: 'conversions', value: 40 },
          { name: 'spend', value: 2800, unit: 'currency', currency: 'USD' },
        ],
        sourceLabel: 'Google Ads',
        connected: true,
      },
      {
        slug: 'tiktok-ads',
        name: 'TikTok Ads',
        channelType: 'paid',
        metrics: [
          { name: 'reach', value: 2000 },
          { name: 'clicks', value: 600 },
          { name: 'conversions', value: 18 },
          { name: 'spend', value: 1200, unit: 'currency', currency: 'USD' },
        ],
        sourceLabel: 'TikTok Ads',
        connected: true,
        stale: true,
        errorMessage: 'Token expirado',
        lastUpdated: '2026-03-12T10:00:00Z',
      },
    ],
  },
  outbound: {
    totals: { contacts: 500, responses: 120 },
    channels: [
      {
        slug: 'cold-contact',
        name: 'Contacto en Frio',
        channelType: 'outbound',
        metrics: [
          { name: 'contacts', value: 500 },
          { name: 'responses', value: 120 },
        ],
        sourceLabel: 'Cold Outreach',
        connected: true,
      },
    ],
  },
  available: {
    channels: [
      {
        slug: 'tiktok-organic',
        name: 'TikTok',
        channelType: 'social',
        metrics: [],
        sourceLabel: 'TikTok',
        connected: false,
      },
      {
        slug: 'linkedin-organic',
        name: 'LinkedIn',
        channelType: 'social',
        metrics: [],
        sourceLabel: 'LinkedIn',
        connected: false,
      },
      {
        slug: 'yt-ads',
        name: 'YouTube Ads',
        channelType: 'paid',
        metrics: [],
        sourceLabel: 'YouTube Ads',
        connected: false,
      },
    ],
  },
};
