import type { StageSummary, AttractionDetail } from '../types/metrics';

export const STAGE_SUMMARIES: StageSummary[] = [
  {
    id: 'ATRACCION',
    order: 0,
    label: 'Atracción',
    description: 'Visitantes que llegan a tu ecosistema digital desde todos los canales',
    mainKpi: { label: 'visitantes', value: 45000 },
    secondaryKpi: { label: 'canales activos', value: 8 },
    hasDetail: true,
  },
  {
    id: 'CAPTURA',
    order: 1,
    label: 'Captura',
    description: 'Visitantes que dejan sus datos y se convierten en leads',
    mainKpi: { label: 'leads', value: 8500 },
    secondaryKpi: { label: 'tasa conversión', value: 18.9, unit: '%' },
    hasDetail: false,
  },
  {
    id: 'NUTRICION',
    order: 2,
    label: 'Nutrición',
    description: 'Leads que interactúan con tu contenido y avanzan en el embudo',
    mainKpi: { label: 'MQLs', value: 3200 },
    secondaryKpi: { label: 'engagement rate', value: 37.6, unit: '%' },
    hasDetail: false,
  },
  {
    id: 'OPORTUNIDAD',
    order: 3,
    label: 'Oportunidad',
    description: 'Leads calificados listos para recibir una oferta',
    mainKpi: { label: 'SQLs', value: 850 },
    secondaryKpi: { label: 'pipeline value', value: 425000, unit: '$' },
    hasDetail: false,
  },
  {
    id: 'VENTAS',
    order: 4,
    label: 'Ventas',
    description: 'Oportunidades que se convierten en clientes de pago',
    mainKpi: { label: 'clientes', value: 450 },
    secondaryKpi: { label: 'ticket promedio', value: 2800, unit: '$' },
    hasDetail: false,
  },
  {
    id: 'ADOPCION',
    order: 5,
    label: 'Adopción',
    description: 'Clientes que usan activamente tu producto o servicio',
    mainKpi: { label: 'activos', value: 400 },
    secondaryKpi: { label: 'activación', value: 88.9, unit: '%' },
    hasDetail: false,
  },
  {
    id: 'EXPANSION',
    order: 6,
    label: 'Expansión',
    description: 'Clientes que compran más productos o upgradean',
    mainKpi: { label: 'upsells', value: 120 },
    secondaryKpi: { label: 'revenue expansion', value: 30, unit: '%' },
    hasDetail: false,
  },
  {
    id: 'EVANGELIZACION',
    order: 7,
    label: 'Evangelización',
    description: 'Clientes que refieren nuevos prospectos activamente',
    mainKpi: { label: 'referidores', value: 85 },
    secondaryKpi: { label: 'referidos/mes', value: 340 },
    hasDetail: false,
  },
];

export const MOCK_ATTRACTION_DETAIL: AttractionDetail = {
  period: 'last_30_days',
  organic: {
    totalValue: 32500,
    channels: [
      {
        slug: 'ig-organic',
        name: 'Instagram',
        channelType: 'ORGANIC_SOCIAL',
        value: 12000,
        sourceLabel: 'Instagram Graph API',
        connected: true,
      },
      {
        slug: 'yt-organic',
        name: 'YouTube',
        channelType: 'ORGANIC_SOCIAL',
        value: 8500,
        sourceLabel: 'YouTube Analytics',
        connected: true,
      },
      {
        slug: 'fb-organic',
        name: 'Facebook',
        channelType: 'ORGANIC_SOCIAL',
        value: 5200,
        sourceLabel: 'Facebook Page Insights',
        connected: false,
      },
      {
        slug: 'tiktok-organic',
        name: 'TikTok',
        channelType: 'ORGANIC_SOCIAL',
        value: 3800,
        sourceLabel: 'TikTok Analytics',
        connected: false,
      },
      {
        slug: 'linkedin-organic',
        name: 'LinkedIn',
        channelType: 'ORGANIC_SOCIAL',
        value: 1200,
        sourceLabel: 'LinkedIn Analytics',
        connected: false,
      },
      {
        slug: 'google-organic',
        name: 'Google Orgánico',
        channelType: 'ORGANIC_SEARCH',
        value: 1100,
        sourceLabel: 'Google Analytics 4',
        connected: false,
      },
      {
        slug: 'direct',
        name: 'Tráfico Directo',
        channelType: 'ORGANIC_SEARCH',
        value: 450,
        sourceLabel: 'Google Analytics 4',
        connected: false,
      },
      {
        slug: 'ai-search-organic',
        name: 'AI Search',
        channelType: 'ORGANIC_SEARCH',
        value: 250,
        sourceLabel: 'Google Analytics 4',
        connected: false,
      },
    ],
  },
  paid: {
    totalValue: 12500,
    totalCost: 8200,
    channels: [
      {
        slug: 'meta-ads',
        name: 'Meta Ads',
        channelType: 'PAID_MEDIA',
        value: 5000,
        cost: 3500,
        sourceLabel: 'Meta Ads Manager',
        connected: true,
      },
      {
        slug: 'google-ads',
        name: 'Google Ads',
        channelType: 'PAID_MEDIA',
        value: 3500,
        cost: 2800,
        sourceLabel: 'Google Ads',
        connected: false,
      },
      {
        slug: 'tiktok-ads',
        name: 'TikTok Ads',
        channelType: 'PAID_MEDIA',
        value: 2200,
        cost: 1200,
        sourceLabel: 'TikTok Ads Manager',
        connected: false,
      },
      {
        slug: 'yt-ads',
        name: 'YouTube Ads',
        channelType: 'PAID_MEDIA',
        value: 1300,
        cost: 500,
        sourceLabel: 'Google Ads',
        connected: false,
      },
      {
        slug: 'cold-contact',
        name: 'Contacto en Frío',
        channelType: 'PAID_MEDIA',
        value: 500,
        cost: 200,
        sourceLabel: 'Manual / CRM',
        connected: false,
      },
    ],
  },
};
