import type { StageSummary, AttractionDetail, CaptureDetail, NurtureDetail, OpportunityDetail, SalesDetail, AdoptionDetail, ExpansionDetailData, EvangelizationDetail } from '../types/metrics';

export const STAGE_SUMMARIES: StageSummary[] = [
  {
    id: 'ATRACCION',
    order: 0,
    label: 'Atraccion',
    description: 'Visitantes que llegan a tu ecosistema digital desde todos los canales',
    mainKpi: { label: 'visitantes', value: 45000 },
    secondaryKpi: { label: 'canales activos', value: 8 },
    hasDetail: true,
  },
  {
    id: 'CAPTURA',
    order: 1,
    label: 'Captura',
    description: 'Visitantes que dejan sus datos y se convierten en leads',
    mainKpi: { label: 'leads', value: 8500 },
    secondaryKpi: { label: 'tasa conversion', value: 18.9, unit: '%' },
    hasDetail: true,
  },
  {
    id: 'NUTRICION',
    order: 2,
    label: 'Nutricion',
    description: 'Leads que interactuan con tu contenido y avanzan en el embudo',
    mainKpi: { label: 'MQLs', value: 3200 },
    secondaryKpi: { label: 'engagement rate', value: 37.6, unit: '%' },
    hasDetail: true,
  },
  {
    id: 'OPORTUNIDAD',
    order: 3,
    label: 'Oportunidad',
    description: 'Leads calificados listos para recibir una oferta',
    mainKpi: { label: 'SQLs', value: 850 },
    secondaryKpi: { label: 'pipeline value', value: 425000, unit: '$' },
    hasDetail: true,
  },
  {
    id: 'VENTAS',
    order: 4,
    label: 'Ventas',
    description: 'Oportunidades que se convierten en clientes de pago',
    mainKpi: { label: 'clientes', value: 450 },
    secondaryKpi: { label: 'ticket promedio', value: 2800, unit: '$' },
    hasDetail: true,
  },
  {
    id: 'ADOPCION',
    order: 5,
    label: 'Adopcion',
    description: 'Clientes que usan activamente tu producto o servicio',
    mainKpi: { label: 'activos', value: 400 },
    secondaryKpi: { label: 'activacion', value: 88.9, unit: '%' },
    hasDetail: true,
  },
  {
    id: 'EXPANSION',
    order: 6,
    label: 'Expansion',
    description: 'Clientes que compran mas productos o upgradean',
    mainKpi: { label: 'upsells', value: 120 },
    secondaryKpi: { label: 'revenue expansion', value: 30, unit: '%' },
    hasDetail: false,
  },
  {
    id: 'EVANGELIZACION',
    order: 7,
    label: 'Evangelizacion',
    description: 'Clientes que refieren nuevos prospectos activamente',
    mainKpi: { label: 'referidores', value: 85 },
    secondaryKpi: { label: 'referidos/mes', value: 340 },
    hasDetail: true,
  },
];

export const MOCK_ATTRACTION_DETAIL: AttractionDetail = {
  period: 'last_30_days',
  lastUpdated: '2026-03-14T03:15:00Z',
  organicSocial: {
    totals: { reach: 24500, engagement: 5800 },
    channels: [
      {
        slug: 'ig-organic',
        name: 'Instagram',
        channelType: 'social',
        metrics: [
          { name: 'reach', value: 12000 },
          { name: 'engagement', value: 3200, breakdown: { likes: 2000, comments: 800, shares: 0, saves: 400 } },
        ],
        sourceLabel: 'Instagram',
        connected: true,
      },
      {
        slug: 'yt-organic',
        name: 'YouTube',
        channelType: 'social',
        metrics: [
          { name: 'reach', value: 8500 },
          { name: 'engagement', value: 1800, breakdown: { likes: 1200, comments: 600 } },
        ],
        sourceLabel: 'YouTube',
        connected: true,
      },
      {
        slug: 'fb-organic',
        name: 'Facebook',
        channelType: 'social',
        metrics: [
          { name: 'reach', value: 4000 },
          { name: 'engagement', value: 800, breakdown: { reactions: 500, comments: 200, shares: 100 } },
        ],
        sourceLabel: 'Facebook',
        connected: true,
      },
    ],
  },
  ga4Search: {
    totals: { sessions: 1800, users: 1400 },
    channels: [
      {
        slug: 'google-organic',
        name: 'Google Organico',
        channelType: 'search',
        metrics: [
          { name: 'sessions', value: 1100 },
          { name: 'users', value: 850 },
        ],
        sourceLabel: 'Google Search',
        connected: true,
      },
      {
        slug: 'direct',
        name: 'Trafico Directo',
        channelType: 'direct',
        metrics: [
          { name: 'sessions', value: 450 },
          { name: 'users', value: 380 },
        ],
        sourceLabel: 'Direct',
        connected: true,
      },
      {
        slug: 'ai-search-organic',
        name: 'AI Search',
        channelType: 'search',
        metrics: [
          { name: 'sessions', value: 250 },
          { name: 'users', value: 170 },
        ],
        sourceLabel: 'AI Search',
        connected: true,
      },
    ],
  },
  paid: {
    totals: { reach: 12000, clicks: 3500, conversions: 120, spend: 8200 },
    channels: [
      {
        slug: 'meta-ads',
        name: 'Meta Ads',
        channelType: 'paid',
        metrics: [
          { name: 'reach', value: 5000 },
          { name: 'clicks', value: 1500 },
          { name: 'conversions', value: 55 },
          { name: 'spend', value: 3500, unit: 'currency', currency: 'USD' },
        ],
        sourceLabel: 'Meta Ads',
        connected: true,
      },
      {
        slug: 'google-ads',
        name: 'Google Ads',
        channelType: 'paid',
        metrics: [
          { name: 'reach', value: 4000 },
          { name: 'clicks', value: 1200 },
          { name: 'conversions', value: 40 },
          { name: 'spend', value: 2800, unit: 'currency', currency: 'USD' },
        ],
        sourceLabel: 'Google Ads',
        connected: true,
      },
      {
        slug: 'tiktok-ads',
        name: 'TikTok Ads',
        channelType: 'paid',
        metrics: [
          { name: 'reach', value: 2000 },
          { name: 'clicks', value: 600 },
          { name: 'conversions', value: 18 },
          { name: 'spend', value: 1200, unit: 'currency', currency: 'USD' },
        ],
        sourceLabel: 'TikTok Ads',
        connected: true,
        stale: true,
        errorMessage: 'Token expirado',
        lastUpdated: '2026-03-12T10:00:00Z',
      },
    ],
  },
  outbound: {
    totals: { contacts: 500, responses: 120 },
    channels: [
      {
        slug: 'cold-contact',
        name: 'Contacto en Frio',
        channelType: 'outbound',
        metrics: [
          { name: 'contacts', value: 500 },
          { name: 'responses', value: 120 },
        ],
        sourceLabel: 'Cold Outreach',
        connected: true,
      },
    ],
  },
  available: {
    channels: [
      {
        slug: 'tiktok-organic',
        name: 'TikTok',
        channelType: 'social',
        metrics: [],
        sourceLabel: 'TikTok',
        connected: false,
      },
      {
        slug: 'linkedin-organic',
        name: 'LinkedIn',
        channelType: 'social',
        metrics: [],
        sourceLabel: 'LinkedIn',
        connected: false,
      },
      {
        slug: 'yt-ads',
        name: 'YouTube Ads',
        channelType: 'paid',
        metrics: [],
        sourceLabel: 'YouTube Ads',
        connected: false,
      },
    ],
  },
};

export const MOCK_CAPTURE_DETAIL: CaptureDetail = {
  headerKpis: { totalLeads: 8500, conversionRate: 18.9, costPerLead: 2.35 },
  miniFunnel: {
    sourceLabel: 'Visitantes',
    sourceValue: 45000,
    targetLabel: 'Leads',
    targetValue: 8500,
    conversionRate: 18.9,
  },
  webInfrastructure: {
    totals: { leads: 3200, cost: 500.0, conversion_rate: 7.1 },
    channels: [
      {
        slug: 'landing-form',
        name: 'Landing Page Form',
        channelType: 'form',
        metrics: [
          { name: 'leads', value: 2800 },
          { name: 'cost', value: 0, unit: 'currency', currency: 'USD' },
          { name: 'conversion_rate', value: 6.2 },
        ],
        sourceLabel: 'Landing Page',
        connected: true,
        costType: 'EXPENSE',
      },
      {
        slug: 'mailerlite',
        name: 'MailerLite',
        channelType: 'email',
        metrics: [
          { name: 'leads', value: 400 },
          { name: 'cost', value: 29.0, unit: 'currency', currency: 'USD' },
          { name: 'conversion_rate', value: 0.9 },
        ],
        sourceLabel: 'MailerLite',
        connected: true,
        costType: 'EXPENSE',
      },
    ],
  },
  aiAgent: {
    totals: { leads: 5300, cost: 800.0, conversion_rate: 11.8 },
    channels: [
      {
        slug: 'ig-dm',
        name: 'Instagram DM',
        channelType: 'messaging',
        metrics: [
          { name: 'leads', value: 2100 },
          { name: 'cost', value: 250.0, unit: 'currency', currency: 'USD' },
          { name: 'conversion_rate', value: 4.7 },
          { name: 'conversations', value: 4800 },
        ],
        sourceLabel: 'Instagram DM',
        connected: true,
        costType: 'EXPENSE',
      },
      {
        slug: 'fb-messenger',
        name: 'Facebook Messenger',
        channelType: 'messaging',
        metrics: [
          { name: 'leads', value: 1500 },
          { name: 'cost', value: 200.0, unit: 'currency', currency: 'USD' },
          { name: 'conversion_rate', value: 3.3 },
          { name: 'conversations', value: 3200 },
        ],
        sourceLabel: 'Messenger',
        connected: true,
        costType: 'EXPENSE',
      },
      {
        slug: 'tiktok-dm',
        name: 'TikTok DM',
        channelType: 'messaging',
        metrics: [
          { name: 'leads', value: 900 },
          { name: 'cost', value: 180.0, unit: 'currency', currency: 'USD' },
          { name: 'conversion_rate', value: 2.0 },
          { name: 'conversations', value: 2100 },
        ],
        sourceLabel: 'TikTok DM',
        connected: true,
        costType: 'EXPENSE',
      },
      {
        slug: 'whatsapp-inbound',
        name: 'WhatsApp Inbound',
        channelType: 'messaging',
        metrics: [
          { name: 'leads', value: 800 },
          { name: 'cost', value: 170.0, unit: 'currency', currency: 'USD' },
          { name: 'conversion_rate', value: 1.8 },
          { name: 'conversations', value: 1900 },
        ],
        sourceLabel: 'WhatsApp',
        connected: true,
        costType: 'EXPENSE',
      },
    ],
  },
  period: 'last_30_days',
  lastUpdated: '2026-03-15T10:30:00Z',
};

export const MOCK_NURTURE_DETAIL: NurtureDetail = {
  headerKpis: { totalMqls: 2100, conversionRate: 24.7, costPerMql: 12.50 },
  miniFunnel: {
    sourceLabel: 'Leads',
    sourceValue: 8500,
    targetLabel: 'MQLs',
    targetValue: 2100,
    conversionRate: 24.7,
  },
  retargeting: {
    totals: { reach: 45200, clicks: 3100, spend: 1250, cost_per_mql: 8.75 },
    channels: [
      {
        slug: 'meta-retargeting',
        name: 'Meta Retargeting',
        channelType: 'retargeting',
        metrics: [
          { name: 'reach', value: 25000 },
          { name: 'clicks', value: 1800 },
          { name: 'spend', value: 650, unit: 'currency', currency: 'USD' },
        ],
        sourceLabel: 'Meta Ads',
        connected: true,
      },
      {
        slug: 'google-retargeting',
        name: 'Google Retargeting',
        channelType: 'retargeting',
        metrics: [
          { name: 'reach', value: 15000 },
          { name: 'clicks', value: 900 },
          { name: 'spend', value: 400, unit: 'currency', currency: 'USD' },
        ],
        sourceLabel: 'Google Ads',
        connected: true,
      },
      {
        slug: 'tiktok-retargeting',
        name: 'TikTok Retargeting',
        channelType: 'retargeting',
        metrics: [
          { name: 'reach', value: 5200 },
          { name: 'clicks', value: 400 },
          { name: 'spend', value: 200, unit: 'currency', currency: 'USD' },
        ],
        sourceLabel: 'TikTok Ads',
        connected: true,
      },
    ],
  },
  automation: {
    totals: { emails_sent: 12500, open_rate: 42.3, click_rate: 8.1, cost_per_mql: 3.75 },
    channels: [
      {
        slug: 'mailerlite',
        name: 'Mailerlite',
        channelType: 'email',
        metrics: [
          { name: 'emails_sent', value: 12500 },
          { name: 'open_rate', value: 42.3, unit: 'percentage' },
          { name: 'click_rate', value: 8.1, unit: 'percentage' },
        ],
        sourceLabel: 'MailerLite',
        connected: true,
      },
      {
        slug: 'ai-sdr',
        name: 'AI SDR',
        channelType: 'automation',
        metrics: [],
        sourceLabel: 'AI SDR',
        connected: true,
      },
    ],
  },
  period: 'last_30_days',
  lastUpdated: new Date().toISOString(),
};

export const MOCK_OPPORTUNITY_DETAIL: OpportunityDetail = {
  headerKpis: {
    totalSqls: 69,
    conversionRate: 32.9,
    costPerSql: 145.50,
  },
  miniFunnel: {
    sourceLabel: 'MQLs',
    sourceValue: 210,
    targetLabel: 'SQLs',
    targetValue: 69,
    conversionRate: 32.9,
  },
  checkout: {
    channels: [
      {
        slug: 'checkout-init',
        name: 'Checkout Iniciado',
        channelType: 'checkout',
        sourceLabel: 'Shopify',
        connected: true,
        metrics: [
          { name: 'count', value: 38 },
          { name: 'value', value: 12450.00, unit: 'currency', currency: 'USD' },
        ],
      },
      {
        slug: 'abandoned-cart',
        name: 'Carrito Abandonado',
        channelType: 'checkout',
        sourceLabel: 'Shopify',
        connected: true,
        metrics: [
          { name: 'count', value: 14 },
          { name: 'value', value: 4200.00, unit: 'currency', currency: 'USD' },
          { name: 'abandonment_rate', value: 36.8 },
        ],
      },
    ],
    totals: { count: 38, abandoned: 14, value: 12450.00, abandonment_rate: 36.8 },
  },
  paymentLinks: {
    channels: [
      {
        slug: 'link-enviado',
        name: 'Link de Pago Enviado',
        channelType: 'payment',
        sourceLabel: 'Sales Agent',
        connected: true,
        metrics: [],
      },
      {
        slug: 'checkout-lp',
        name: 'Checkout Landing Page',
        channelType: 'payment',
        sourceLabel: 'Landing Page',
        connected: true,
        metrics: [],
      },
    ],
    totals: { count: 0, value: 0 },
  },
  qualification: {
    channels: [
      {
        slug: 'meeting-booked',
        name: 'Reuniones Agendadas',
        channelType: 'scheduling',
        sourceLabel: 'Scheduling',
        connected: true,
        metrics: [
          { name: 'booked', value: 24 },
          { name: 'completed', value: 18 },
          { name: 'no_show', value: 3 },
          { name: 'rescheduled', value: 3 },
        ],
      },
    ],
    totals: { booked: 24, completed: 18, no_show: 3, rescheduled: 3, attendance_rate: 75.0 },
  },
  bottlenecks: [
    {
      type: 'abandoned_cart',
      metricLabel: 'Tasa de Abandono',
      currentRate: 36.8,
      severity: 'warning',
      threshold: 30,
      tip: 'Revisa tu proceso de pago y considera email de recuperacion de carrito',
    },
  ],
  period: 'last_30_days',
  lastUpdated: new Date().toISOString(),
};

export const MOCK_SALES_DETAIL: SalesDetail = {
  headerKpis: {
    totalRevenue: 130000,
    totalRevenueUsd: 7540,
    currency: 'MXN',
    newCustomers: 138,
    cac: 450,
    cacIncomplete: false,
    netSales: 118000,
    totalDiscounts: 5200,
    totalTax: 20800,
    refundCount: 3,
    refundAmount: 6800,
    shippingRevenue: 4500,
    repeatCustomers: 22,
    discountUsageCount: 18,
    shopifyRevenue: 130000,
    shopifyOrderCount: 138,
    shopifyAvgOrderValue: 942,
    shopifyCurrency: 'MXN',
  },
  miniFunnel: {
    sourceLabel: 'Oportunidades',
    sourceValue: 850,
    targetLabel: 'Ventas',
    targetValue: 450,
    conversionRate: 52.9,
  },
  adquisicion: {
    groupKey: 'adquisicion',
    groupLabel: 'Adquisicion',
    totalRevenue: 85000,
    totalRevenueUsd: 4930,
    customerCount: 138,
    revenuePercentage: 65.4,
    currency: 'MXN',
    tiers: [
      {
        tierKey: 'low_ticket',
        tierLabel: 'Low Ticket',
        offers: [
          {
            offerId: 'offer-001',
            publicName: 'Curso Intensivo',
            offerType: 'self_paced_course',
            pricingType: 'one_time',
            totalRevenue: 45000,
            salesCount: 120,
            currency: 'MXN',
            usdRevenue: 2610,
            sourceBreakdown: { SHOPIFY: 60, AGENT: 15, MANUAL: 5 },
            newSubscriptions: null,
            newSubscriptionRevenue: null,
            renewals: null,
            renewalRevenue: null,
            subscriptionNewLabel: null,
            subscriptionRenewalLabel: null,
          },
          {
            offerId: 'offer-002',
            publicName: 'Guia Descargable',
            offerType: 'digital_download',
            pricingType: 'one_time',
            totalRevenue: 12000,
            salesCount: 80,
            currency: 'MXN',
            usdRevenue: 696,
            sourceBreakdown: { SHOPIFY: 70, MANUAL: 10 },
            newSubscriptions: null,
            newSubscriptionRevenue: null,
            renewals: null,
            renewalRevenue: null,
            subscriptionNewLabel: null,
            subscriptionRenewalLabel: null,
          },
        ],
      },
      {
        tierKey: 'mid_ticket',
        tierLabel: 'Mid Ticket',
        offers: [
          {
            offerId: 'offer-003',
            publicName: 'Mentoria Grupal',
            offerType: 'group_coaching',
            pricingType: 'one_time',
            totalRevenue: 28000,
            salesCount: 14,
            currency: 'MXN',
            usdRevenue: 1624,
            sourceBreakdown: { AGENT: 10, MANUAL: 4 },
            newSubscriptions: null,
            newSubscriptionRevenue: null,
            renewals: null,
            renewalRevenue: null,
            subscriptionNewLabel: null,
            subscriptionRenewalLabel: null,
          },
        ],
      },
    ],
  },
  expansion: {
    groupKey: 'expansion',
    groupLabel: 'Expansion',
    totalRevenue: 45000,
    totalRevenueUsd: 2610,
    customerCount: 35,
    revenuePercentage: 34.6,
    currency: 'MXN',
    tiers: [
      {
        tierKey: 'recurrente',
        tierLabel: 'Recurrente',
        offers: [
          {
            offerId: 'offer-004',
            publicName: 'Membresia Premium',
            offerType: 'membership',
            pricingType: 'subscription',
            totalRevenue: 45000,
            salesCount: 35,
            currency: 'MXN',
            usdRevenue: 2610,
            sourceBreakdown: { SHOPIFY: 20, AGENT: 10, API: 5 },
            newSubscriptions: 20,
            newSubscriptionRevenue: 30000,
            renewals: 15,
            renewalRevenue: 15000,
            subscriptionNewLabel: 'nuevas',
            subscriptionRenewalLabel: 'renovaciones',
          },
        ],
      },
    ],
  },
  bottlenecks: [],
  period: 'last_30_days',
  lastUpdated: new Date().toISOString(),
};

export const MOCK_ADOPTION_DETAIL: AdoptionDetail = {
  headerKpis: {
    activeCustomers: 128,
    inactiveCustomers: 34,
    healthPct: 79.0,
    avgTtvDays: 4.2,
    refundCount: 3,
    refundAmount: 2500,
    refundCurrency: 'MXN',
    refundAmountUsd: 145,
  },
  miniFunnel: { sourceLabel: 'Ventas', sourceValue: 180, targetLabel: 'Activos', targetValue: 128, conversionRate: 71.1 },
  offers: [
    { offerId: 'offer-1', publicName: 'Curso de Marketing Digital', totalCustomers: 95, activeCount: 78, inactiveCount: 17, healthPct: 82.1, ttvDays: 3.5 },
    { offerId: 'offer-2', publicName: 'Coaching 1:1', totalCustomers: 42, activeCount: 35, inactiveCount: 7, healthPct: 83.3, ttvDays: 1.2 },
    { offerId: 'offer-3', publicName: 'Membresia Premium', totalCustomers: 25, activeCount: 15, inactiveCount: 10, healthPct: 60.0, ttvDays: 6.8 },
  ],
  bottlenecks: [],
  period: 'last_30_days',
  lastUpdated: new Date().toISOString(),
};

export const MOCK_EXPANSION_DETAIL: ExpansionDetailData = {
  headerKpis: {
    netMrr: 45000,
    netMrrUsd: 2610,
    currency: 'MXN',
    avgLtv: 8500,
    avgLtvUsd: 493,
    churnRatePct: 3.8,
  },
  miniFunnel: { sourceLabel: 'Activos', sourceValue: 128, targetLabel: 'Expansion', targetValue: 23, conversionRate: 18.0 },
  retencion: {
    groupKey: 'retencion', groupLabel: 'Retencion', groupSubtitle: 'Renovaciones de suscripciones activas',
    totalCount: 45, totalRevenue: 38000, totalRevenueUsd: 2204, currency: 'MXN', ratePct: 92.0,
    offers: [
      { offerId: 'offer-3', publicName: 'Membresia Premium', count: 30, revenue: 28500, currency: 'MXN', usdRevenue: 1653 },
      { offerId: 'offer-4', publicName: 'Plan Coaching Mensual', count: 15, revenue: 9500, currency: 'MXN', usdRevenue: 551 },
    ],
  },
  crecimiento: {
    groupKey: 'crecimiento', groupLabel: 'Crecimiento', groupSubtitle: 'Ventas adicionales y upgrades a clientes existentes',
    totalCount: 12, totalRevenue: 15000, totalRevenueUsd: 870, currency: 'MXN', ratePct: 9.4,
    offers: [
      { offerId: 'offer-5', publicName: 'Workshop Avanzado', count: 8, revenue: 12000, currency: 'MXN', usdRevenue: 696 },
      { offerId: 'offer-6', publicName: 'Consultoria Express', count: 4, revenue: 3000, currency: 'MXN', usdRevenue: 174 },
    ],
  },
  cancelaciones: {
    groupKey: 'cancelaciones', groupLabel: 'Cancelaciones', groupSubtitle: 'Suscripciones perdidas y ingreso afectado',
    totalCount: 5, totalRevenue: 8000, totalRevenueUsd: 464, currency: 'MXN', ratePct: 3.8,
    offers: [
      { offerId: 'offer-3', publicName: 'Membresia Premium', count: 3, revenue: 5700, currency: 'MXN', usdRevenue: 331 },
      { offerId: 'offer-4', publicName: 'Plan Coaching Mensual', count: 2, revenue: 2300, currency: 'MXN', usdRevenue: 133 },
    ],
  },
  bottlenecks: [],
  period: 'last_30_days',
  lastUpdated: new Date().toISOString(),
};

export const MOCK_EVANGELIZATION_DETAIL: EvangelizationDetail = {
  headerKpis: {
    kFactor: 0.73,
    referralConversions: 8,
    npsScore: 8.4,
    referralRevenue: 24500,
    referralRevenueUsd: 1360,
    currency: 'MXN',
    activeEvangelists: 5,
  },
  miniFunnel: { sourceLabel: 'Clientes Activos', sourceValue: 42, targetLabel: 'Evangelistas', targetValue: 5, conversionRate: 11.9 },
  referidos: [
    { customerId: 'mock-1', fullName: 'Maria Garcia', referralCode: 'REF-MG2K4X', referralsSent: 6, conversions: 3, revenueAttributed: 12500, currency: 'MXN', usdRevenue: 694, isActive: true },
    { customerId: 'mock-2', fullName: 'Carlos Lopez', referralCode: 'REF-CL9B7Z', referralsSent: 4, conversions: 2, revenueAttributed: 8000, currency: 'MXN', usdRevenue: 444, isActive: true },
    { customerId: 'mock-3', fullName: 'Ana Torres', referralCode: 'REF-AT3F1Q', referralsSent: 3, conversions: 1, revenueAttributed: 4000, currency: 'MXN', usdRevenue: 222, isActive: true },
  ],
  candidatos: [
    { customerId: 'mock-4', fullName: 'Roberto Diaz', npsScore: 10, respondedAt: '2026-03-10T14:30:00Z' },
    { customerId: 'mock-5', fullName: 'Laura Mendez', npsScore: 9, respondedAt: '2026-03-12T09:15:00Z' },
  ],
  npsSummary: {
    npsScore: 8.4,
    standardNps: 65,
    promoterCount: 15,
    passiveCount: 8,
    detractorCount: 3,
    totalResponses: 26,
    surveysSent: 35,
    responseRatePct: 74.3,
  },
  ugcCount: 7,
  ugcWritten: 5,
  ugcAudio: 2,
  bottlenecks: [],
  period: 'last_30_days',
  lastUpdated: new Date().toISOString(),
};
