"""add_gallery_image_table

Revision ID: 66a20b0fa0fc
Revises: e9a1d0ee1583
Create Date: 2026-02-10 13:31:54.056326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66a20b0fa0fc'
down_revision: Union[str, None] = 'e9a1d0ee1583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('public_url', sa.String(), nullable=False),
    sa.Column('user_description', sa.Text(), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('ai_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent_traces', sa.Column('action', sa.String(), nullable=True))
    op.add_column('agent_traces', sa.Column('reward', sa.Float(), nullable=True))
    op.add_column('agent_traces', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_traces', 'feedback')
    op.drop_column('agent_traces', 'reward')
    op.drop_column('agent_traces', 'action')
    op.drop_table('gallery_images')
    # ### end Alembic commands ###
