"""refactor_offer_and_journey_final

Revision ID: 9c6fc3c2980b
Revises: 16a58268fd71
Create Date: 2026-02-02 21:46:20.150218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c6fc3c2980b'
down_revision: Union[str, None] = '16a58268fd71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. RENAME Table instead of Dropping
    # op.drop_table('enrollments') 
    op.rename_table('enrollments', 'journey_progress')
    
    # 2. Add New Columns to JourneyProgress
    op.add_column('journey_progress', sa.Column('product_line', sa.String(), nullable=True))
    op.add_column('journey_progress', sa.Column('funnel_entry_point', sa.String(), nullable=True))
    op.add_column('journey_progress', sa.Column('deal_value_potential', sa.Float(), nullable=True, server_default='0.0'))
    op.add_column('journey_progress', sa.Column('objection_status', sa.String(), nullable=True))
    
    # Handle FK renames/creation if needed (Postgres usually keeps them pointing correctly but names might be old)
    # Ideally we rename the constraint too, but for now functionality is key.
    
    op.drop_constraint(op.f('avatar_definitions_user_id_fkey'), 'avatar_definitions', type_='foreignkey')
    op.create_foreign_key(None, 'avatar_definitions', 'users', ['user_id'], ['id'])
    
    op.add_column('leads', sa.Column('social_handle_main', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('fit_score', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('intent_score', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('temperature', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('is_blacklisted', sa.Boolean(), nullable=True))
    op.add_column('leads', sa.Column('last_interaction_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('next_scheduled_action', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('conversation_summary', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('key_objections_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Handle constraints safely
    try:
        op.drop_index(op.f('ix_leads_api_id'), table_name='leads')
    except:
        pass
        
    try:
        op.drop_constraint(op.f('users_email_key'), 'leads', type_='unique')
        op.drop_constraint(op.f('users_phone_key'), 'leads', type_='unique')
    except:
        pass
        
    op.create_unique_constraint(None, 'leads', ['api_id'])
    
    op.add_column('products', sa.Column('internal_sku', sa.String(), nullable=True))
    op.add_column('products', sa.Column('delivery_model', sa.String(), nullable=True))
    op.add_column('products', sa.Column('headline_promise', sa.String(), nullable=True))
    op.add_column('products', sa.Column('target_avatar_match', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('requires_application', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('min_financial_capacity', sa.String(), nullable=True))
    op.add_column('products', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('products', sa.Column('guarantee_type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('upsell_product_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'products', ['upsell_product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'upsell_product_id')
    op.drop_column('products', 'guarantee_type')
    op.drop_column('products', 'currency')
    op.drop_column('products', 'min_financial_capacity')
    op.drop_column('products', 'requires_application')
    op.drop_column('products', 'target_avatar_match')
    op.drop_column('products', 'headline_promise')
    op.drop_column('products', 'delivery_model')
    op.drop_column('products', 'internal_sku')
    op.drop_constraint(None, 'leads', type_='unique')
    op.create_unique_constraint(op.f('users_phone_key'), 'leads', ['phone'])
    op.create_unique_constraint(op.f('users_email_key'), 'leads', ['email'])
    op.create_index(op.f('ix_leads_api_id'), 'leads', ['api_id'], unique=False)
    op.drop_column('leads', 'key_objections_history')
    op.drop_column('leads', 'conversation_summary')
    op.drop_column('leads', 'next_scheduled_action')
    op.drop_column('leads', 'last_interaction_date')
    op.drop_column('leads', 'is_blacklisted')
    op.drop_column('leads', 'temperature')
    op.drop_column('leads', 'intent_score')
    op.drop_column('leads', 'fit_score')
    op.drop_column('leads', 'timezone')
    op.drop_column('leads', 'social_handle_main')
    op.drop_constraint(None, 'avatar_definitions', type_='foreignkey')
    op.create_foreign_key(op.f('avatar_definitions_user_id_fkey'), 'avatar_definitions', 'leads', ['user_id'], ['id'])
    
    # Reverse Rename
    op.rename_table('journey_progress', 'enrollments')
    op.drop_column('enrollments', 'objection_status')
    op.drop_column('enrollments', 'deal_value_potential')
    op.drop_column('enrollments', 'funnel_entry_point')
    op.drop_column('enrollments', 'product_line')
    
    # ### end Alembic commands ###
