"""Render :data:`EXTRACTION_CONTRACTS` as Markdown.

Run from the repo root:

    cd backend && .venv/bin/python scripts/generate_extraction_contract_doc.py

Writes ``docs/etl/extraction-contract.md`` (idempotent).
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow running directly from `backend/` without setting PYTHONPATH manually.
_BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(_BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(_BACKEND_ROOT))

from src.modules.analytics.domain.extraction_contract import (
    CHANNEL_TYPE_TO_PROVIDERS,
    EXTRACTION_CONTRACTS,
    STORAGE_TABLES_DOC,
    WORKER_SCHEDULE_DOC,
    APIEndpoint,
    ChannelOutput,
    MetricMapping,
    ProviderContract,
    ProviderStatus,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "docs" / "etl" / "extraction-contract.md"


_STATUS_BADGE = {
    ProviderStatus.PRODUCTION: "🟢 production",
    ProviderStatus.PARTIAL: "🟡 partial",
    ProviderStatus.BROKEN: "🔴 broken",
    ProviderStatus.PASS_THROUGH: "⚪ pass-through",
    ProviderStatus.DEPRECATED: "⚫ deprecated",
}


def _render_endpoint(ep: APIEndpoint) -> str:
    docs = f" ([docs]({ep.docs_url}))" if ep.docs_url else ""
    return f"- **{ep.description}**{docs}\n  `{ep.url_template}`"


def _render_metric(m: MetricMapping) -> str:
    notes = f" — {m.notes}" if m.notes else ""
    return f"| `{m.canonical_name}` | `{m.api_field}` | {m.unit} |{notes} |"


def _render_channel(channel: ChannelOutput) -> str:
    out = [
        f"#### Channel `{channel.channel_slug}` (stage: `{channel.stage}`)",
        "",
    ]
    if channel.description:
        out.extend([channel.description, ""])
    if not channel.metrics:
        out.append("_No metrics emitted directly — populated via webhooks or downstream._")
    else:
        out.extend(
            [
                "| Canonical name | API field | Unit | Notes |",
                "|---|---|---|---|",
                *(_render_metric(m) for m in channel.metrics),
            ]
        )
    out.append("")
    return "\n".join(out)


def _render_provider(contract: ProviderContract) -> str:
    badge = _STATUS_BADGE[contract.status]
    multi_stage = "yes" if contract.is_multi_stage else "no"
    period_extraction = "yes" if contract.has_period_extraction else "no"
    issues = "\n".join(f"- {issue}" for issue in contract.known_issues) if contract.known_issues else "_None._"
    notes = f"\n\n> {contract.notes}" if contract.notes else ""

    sections: list[str] = []
    sections.append(f"## `{contract.provider_name}` — {contract.display_name}")
    sections.append("")
    sections.append(f"**Status:** {badge}  ")
    sections.append(f"**Code:** `{contract.module_path}.{contract.class_name}`  ")
    sections.append(f"**Auth:** {contract.auth_type.value} via {contract.auth_provider}  ")
    sections.append(
        f"**Required credentials:** {', '.join(f'`{c}`' for c in contract.required_credentials) or '_none_'}  "
    )
    sections.append(
        f"**Serves channel_types:** {', '.join(f'`{c}`' for c in contract.serves_channel_types) or '_none_'}  "
    )
    sections.append(f"**Multi-stage:** {multi_stage}  ")
    sections.append(f"**Stages supported:** {', '.join(f'`{s}`' for s in contract.stages_supported)}  ")
    sections.append(f"**Has period extraction:** {period_extraction}  ")
    sections.append(f"**Extraction modes:** {', '.join(m.value for m in contract.extraction_modes)}  ")
    sections.append(f"**Cron:** {contract.cron_schedule}  ")
    sections.append(f"**Storage tables:** {', '.join(f'`{t}`' for t in contract.storage_tables)}  ")
    sections.append(f"**Last verified:** {contract.last_verified}{notes}")
    sections.append("")
    sections.append("### API endpoints")
    sections.append("")
    if contract.api_endpoints:
        sections.extend(_render_endpoint(ep) for ep in contract.api_endpoints)
    else:
        sections.append("_None — does not call any external API._")
    sections.append("")
    sections.append("### Channels & metrics")
    sections.append("")
    for channel in contract.channel_outputs:
        sections.append(_render_channel(channel))
    sections.append("### Known issues")
    sections.append("")
    sections.append(issues)
    sections.append("")
    sections.append("---")
    sections.append("")
    return "\n".join(sections)


def _render_storage_tables() -> str:
    out = [
        "## Storage tables",
        "",
        "These are the tables the ETL pipeline reads or writes. Generated by `pipeline.py` / `period_pipeline.py` / `campaign_sync_pipeline.py`.",
        "",
        "| Table | Purpose |",
        "|---|---|",
    ]
    for table, description in STORAGE_TABLES_DOC.items():
        out.append(f"| `{table}` | {description} |")
    out.append("")
    return "\n".join(out)


def _render_channel_type_mapping() -> str:
    out = [
        "## `channel_type` → providers (intended mapping)",
        "",
        "This is the mapping that `etl_service.run_all_providers` SHOULD use to resolve which provider handles each `channel_connections.channel_type` value. It is currently NOT applied — the code uses `conn.channel_type` directly which silently ignores any connection whose `channel_type` does not equal a provider name verbatim.",
        "",
        "| `channel_type` | Provider(s) |",
        "|---|---|",
    ]
    for ct, providers in CHANNEL_TYPE_TO_PROVIDERS.items():
        provider_str = ", ".join(f"`{p}`" for p in providers)
        out.append(f"| `{ct}` | {provider_str} |")
    out.append("")
    return "\n".join(out)


def _render_worker_schedule() -> str:
    out = [
        "## Worker schedule reference",
        "",
        "Source: `backend/src/workers/settings.py`. The contract test verifies that the function names referenced here still exist.",
        "",
        "| Task | Schedule |",
        "|---|---|",
    ]
    for task, description in WORKER_SCHEDULE_DOC.items():
        out.append(f"| `{task}` | {description} |")
    out.append("")
    return "\n".join(out)


def _render_summary_table() -> str:
    out = [
        "## Provider summary",
        "",
        "| Provider | Status | Channels | Period? | Multi-stage? |",
        "|---|---|---|---|---|",
    ]
    for name in sorted(EXTRACTION_CONTRACTS.keys()):
        c = EXTRACTION_CONTRACTS[name]
        badge = _STATUS_BADGE[c.status]
        channels = ", ".join(f"`{ch.channel_slug}`" for ch in c.channel_outputs)
        period = "✓" if c.has_period_extraction else "—"
        multi = "✓" if c.is_multi_stage else "—"
        out.append(f"| `{name}` | {badge} | {channels} | {period} | {multi} |")
    out.append("")
    return "\n".join(out)


def render() -> str:
    parts: list[str] = []
    parts.append("# ETL Extraction Contract")
    parts.append("")
    parts.append(
        "**This file is auto-generated** from "
        "`backend/src/modules/analytics/domain/extraction_contract.py`. "
        "Do not edit by hand. Regenerate with:"
    )
    parts.append("")
    parts.append("```bash\ncd backend && .venv/bin/python scripts/generate_extraction_contract_doc.py\n```")
    parts.append("")
    parts.append(
        "The contract is the single source of truth for what the analytics ETL extracts, from where, when, and where it lands. It is enforced by `backend/tests/architecture/test_extraction_contract.py` — that test fails if the providers in `PROVIDER_REGISTRY` drift from the entries here."
    )
    parts.append("")
    parts.append("## Why this exists")
    parts.append("")
    parts.append(
        "Future Claude (or any developer / auditor) should be able to answer:\n\n"
        "1. **Which external sources do we pull from?**\n"
        "2. **What metrics does each provider produce?**\n"
        "3. **When does the extraction run?**\n"
        "4. **Where does the data land?**\n"
        "5. **What is currently broken or partial?**\n\n"
        "...without having to read every provider implementation."
    )
    parts.append("")
    parts.append(_render_summary_table())
    parts.append(_render_storage_tables())
    parts.append(_render_channel_type_mapping())
    parts.append(_render_worker_schedule())
    parts.append("---")
    parts.append("")
    parts.append("# Provider details")
    parts.append("")
    for name in sorted(EXTRACTION_CONTRACTS.keys()):
        parts.append(_render_provider(EXTRACTION_CONTRACTS[name]))
    return "\n".join(parts)


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
