from typing import Optional, List
from uuid import UUID
from sqlalchemy.orm import Session
from src.modules.sales.infrastructure.repositories.lead_repository import LeadRepository
from src.modules.sales.domain.lead import Lead, UserProfile

class LeadService:
    def __init__(self, db: Session):
        self.db = db
        self.repository = LeadRepository(db)

    def get_lead(self, lead_id: UUID) -> Optional[Lead]:
        return self.repository.get_by_id(lead_id)

    def find_lead_by_channel(self, channel: str, channel_id: str, tenant_id: UUID) -> Optional[Lead]:
        return self.repository.get_by_channel_id(channel, channel_id, tenant_id)

    def create_lead(self, tenant_id: UUID, profile: Optional[UserProfile] = None, **channel_ids) -> Lead:
        new_lead = Lead(
            id=UUID(int=0), # Placeholder, will be generated by DB or Pydantic default if we change it
            tenant_id=tenant_id,
            profile_data=profile or UserProfile(),
            **channel_ids
        )
        # Note: In Domain Entity, ID is mandatory UUID. In create flow, we usually let DB generate it or generate here.
        import uuid
        new_lead.id = uuid.uuid4()
        
        return self.repository.create(new_lead)

    def update_lead(self, lead: Lead) -> Lead:
        return self.repository.update(lead)

class PipelineService:
    def __init__(self, db: Session):
        self.db = db
        self.lead_repo = LeadRepository(db)

    def move_stage(self, lead_id: UUID, new_stage: str):
        # Placeholder for Pipeline Logic
        # e.g. update lead.pipeline_stage
        pass
