import type { ComponentEntry } from "./types";

// FEATURE slices: brand-studio, connections, offer-studio, audit, admin, settings
// (The legacy "brand" slice was removed in Sprint 5; brand-studio is now the
// canonical home for brand-facing components — see docs/ux-sessions/2026-04-17-universal-editable-form-component/.)
export const REGISTRY_OTHER_FEATURES: ComponentEntry[] = [
  // ==========================================================================
  // FEATURE: connections (features/connections/components/)
  // ==========================================================================
  {
    name: "WhatsAppView",
    atomicLevel: "organism",
    filePath: "features/connections/components/whatsapp-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "WhatsApp connection config view.",
  },
  {
    name: "ManyChatView",
    atomicLevel: "organism",
    filePath: "features/connections/components/manychat-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "ManyChat connection config view.",
  },
  {
    name: "GoogleAnalyticsView",
    atomicLevel: "organism",
    filePath: "features/connections/components/google-analytics-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Google Analytics connection config view.",
  },
  {
    name: "GoogleWorkspaceView",
    atomicLevel: "organism",
    filePath: "features/connections/components/google-workspace-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Google Workspace connection config view.",
  },
  {
    name: "ShopifyView",
    atomicLevel: "organism",
    filePath: "features/connections/components/shopify-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Shopify connection config view.",
  },
  {
    name: "YouTubeView",
    atomicLevel: "organism",
    filePath: "features/connections/components/youtube-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "YouTube connection config view.",
  },
  {
    name: "MetaView",
    atomicLevel: "organism",
    filePath: "features/connections/components/meta-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Meta (Facebook/Instagram) connection config view.",
  },
  {
    name: "GmailView",
    atomicLevel: "organism",
    filePath: "features/connections/components/gmail-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Gmail connection config view.",
  },
  {
    name: "GoogleCalendarView",
    atomicLevel: "organism",
    filePath: "features/connections/components/google-calendar-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Google Calendar connection config view.",
  },
  {
    name: "MailerliteView",
    atomicLevel: "organism",
    filePath: "features/connections/components/mailerlite-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Mailerlite connection config view.",
  },
  {
    name: "TelegramView",
    atomicLevel: "organism",
    filePath: "features/connections/components/telegram-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Telegram connection config view.",
  },

  // ==========================================================================
  // FEATURE: offer-studio (features/offer-studio/components/) — selected
  // ==========================================================================
  {
    name: "OfferStudioNavRail",
    atomicLevel: "molecule",
    filePath: "features/offer-studio/components/OfferStudioNavRail.tsx",
    source: "feature",
    featureSlice: "offer-studio",
    variants: [],
    props: [],
    description: "Flat navigation rail for Offer Studio sections (post-F1.3).",
  },
  {
    name: "OfferShellLayout",
    atomicLevel: "organism",
    filePath: "features/offer-studio/components/OfferShellLayout.tsx",
    source: "feature",
    featureSlice: "offer-studio",
    variants: [],
    props: ["offerId", "tenantId"],
    description: "Shell layout (breadcrumb + header + variant rail + tab bar) mounted once per offer.",
  },
  {
    name: "OfferShellHeader",
    atomicLevel: "organism",
    filePath: "features/offer-studio/components/OfferShellHeader.tsx",
    source: "feature",
    featureSlice: "offer-studio",
    variants: [],
    props: ["offer", "tenantId"],
    description: "Offer header row — title + format badge + status switcher + kebab menu.",
  },

  // ==========================================================================
  // FEATURE: audit (features/audit/components/)
  // ==========================================================================
  {
    name: "AuditDashboard",
    atomicLevel: "organism",
    filePath: "features/audit/components/AuditDashboard.tsx",
    source: "feature",
    featureSlice: "audit",
    variants: [],
    props: [],
    description: "Main audit/conversation trace dashboard.",
  },
  {
    name: "TraceInspector",
    atomicLevel: "organism",
    filePath: "features/audit/components/trace-inspector.tsx",
    source: "feature",
    featureSlice: "audit",
    variants: [],
    props: ["traceId"],
    description: "LangGraph trace visualization and inspection.",
  },
  {
    name: "ContextPanel",
    atomicLevel: "molecule",
    filePath: "features/audit/components/context-panel.tsx",
    source: "feature",
    featureSlice: "audit",
    variants: [],
    props: ["context"],
    description: "Context data panel for trace inspection.",
  },
  {
    name: "NodeDetailsPanel",
    atomicLevel: "molecule",
    filePath: "features/audit/components/node-details-panel.tsx",
    source: "feature",
    featureSlice: "audit",
    variants: [],
    props: ["node"],
    description: "Details panel for a single graph node in trace.",
  },
  {
    name: "UserList",
    atomicLevel: "molecule",
    filePath: "features/audit/components/user-list.tsx",
    source: "feature",
    featureSlice: "audit",
    variants: [],
    props: ["users"],
    description: "User list for filtering audit conversations.",
  },
  {
    name: "ChatTimeline",
    atomicLevel: "molecule",
    filePath: "features/audit/components/chat-timeline.tsx",
    source: "feature",
    featureSlice: "audit",
    variants: [],
    props: ["messages"],
    description: "Chat message timeline visualization.",
  },
  {
    name: "NodeIcons",
    atomicLevel: "atom",
    filePath: "features/audit/components/node-icons.tsx",
    source: "feature",
    featureSlice: "audit",
    variants: [],
    props: ["nodeType"],
    description: "Icon set for graph node types.",
  },

  // ==========================================================================
  // FEATURE: admin (features/admin/components/)
  // ==========================================================================
  {
    name: "TenantsList",
    atomicLevel: "organism",
    filePath: "features/admin/components/tenants-list.tsx",
    source: "feature",
    featureSlice: "admin",
    variants: [],
    props: [],
    description: "Admin tenant management list.",
  },

  // ==========================================================================
  // FEATURE: settings (features/settings/components/)
  // ==========================================================================
  {
    name: "SettingsView",
    atomicLevel: "organism",
    filePath: "features/settings/components/SettingsView.tsx",
    source: "feature",
    featureSlice: "settings",
    variants: [],
    props: [],
    description: "Main settings page layout with tabs.",
  },
  {
    name: "TeamView",
    atomicLevel: "organism",
    filePath: "features/settings/components/team-view.tsx",
    source: "feature",
    featureSlice: "settings",
    variants: [],
    props: [],
    description: "Team member management view.",
  },
  {
    name: "WebhookView",
    atomicLevel: "organism",
    filePath: "features/settings/components/webhook-view.tsx",
    source: "feature",
    featureSlice: "settings",
    variants: [],
    props: [],
    description: "Webhook configuration view.",
  },
  {
    name: "AiKeysForm",
    atomicLevel: "molecule",
    filePath: "features/settings/components/ai-keys-form.tsx",
    source: "feature",
    featureSlice: "settings",
    variants: [],
    props: [],
    description: "Form for configuring AI API keys.",
  },
  {
    name: "GeneralSettingsForm",
    atomicLevel: "molecule",
    filePath: "features/settings/components/general-settings-form.tsx",
    source: "feature",
    featureSlice: "settings",
    variants: [],
    props: [],
    description: "General tenant settings form.",
  },
  {
    name: "ProfileView",
    atomicLevel: "organism",
    filePath: "features/settings/components/profile-view.tsx",
    source: "feature",
    featureSlice: "settings",
    variants: [],
    props: [],
    description: "User profile settings view.",
  },
];
