import type { ComponentEntry } from "./types";

// FEATURE: sales (features/sales/components/)
export const REGISTRY_SALES: ComponentEntry[] = [
  // ==========================================================================
  // FEATURE: sales (features/sales/components/)
  // ==========================================================================

  // --- Atoms ---
  {
    name: "ScoreRing",
    atomicLevel: "atom",
    filePath: "features/sales/components/atoms/ScoreRing.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: ["score", "size"],
    description: "Circular score visualization ring.",
  },
  {
    name: "ActionIcon",
    atomicLevel: "atom",
    filePath: "features/sales/components/atoms/ActionIcon.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: ["action", "size"],
    description: "Icon representing a sales action type.",
  },
  {
    name: "LeadAvatar",
    atomicLevel: "atom",
    filePath: "features/sales/components/atoms/LeadAvatar.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: ["name", "imageUrl", "size"],
    description: "Lead profile avatar with initials fallback.",
    issues: ["Duplicates Avatar from shadcn — could extend it instead"],
  },
  {
    name: "TemperatureBadge",
    atomicLevel: "atom",
    filePath: "features/sales/components/atoms/TemperatureBadge.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: ["temperature"],
    description: "Color-coded lead temperature indicator (hot/warm/cold).",
  },

  // --- Molecules ---
  {
    name: "IdentityHeader",
    atomicLevel: "molecule",
    filePath: "features/sales/components/molecules/IdentityHeader.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: ["lead"],
    description: "Lead identity display with avatar, name, contact info.",
  },
  {
    name: "LeadCard",
    atomicLevel: "molecule",
    filePath: "features/sales/components/molecules/LeadCard.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: ["lead", "onClick"],
    description: "Kanban card for a single lead with score, temperature, summary.",
  },

  // --- Organisms ---
  {
    name: "LeadCommandCenter",
    atomicLevel: "organism",
    filePath: "features/sales/components/organisms/LeadCommandCenter.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: ["leadId"],
    description: "Full lead detail panel with tabs, timeline, actions.",
  },
  {
    name: "LeadPipelineBoard",
    atomicLevel: "organism",
    filePath: "features/sales/components/organisms/LeadPipelineBoard.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: ["stages", "leads"],
    description: "Kanban board for sales pipeline with drag-and-drop lanes.",
  },

  // --- Other sales components (unclassified in source) ---
  {
    name: "GenerateLinkModal",
    atomicLevel: "molecule",
    filePath: "features/sales/components/generate-link-modal.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: ["open", "onClose"],
    description: "Modal for generating shareable payment/scheduling links.",
    issues: ["Not in molecules/ directory"],
  },
  {
    name: "AvailabilityView",
    atomicLevel: "organism",
    filePath: "features/sales/components/availability-view.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: [],
    description: "Availability configuration view for scheduling.",
    issues: ["Not in organisms/ directory"],
  },
  {
    name: "EventTypeForm",
    atomicLevel: "molecule",
    filePath: "features/sales/components/event-type-form.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: ["eventType", "onSubmit"],
    description: "Form for creating/editing scheduling event types.",
    issues: ["Not in molecules/ directory"],
  },
  {
    name: "EventTypeView",
    atomicLevel: "organism",
    filePath: "features/sales/components/event-type-view.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: [],
    description: "List/manage event types for scheduling.",
    issues: ["Not in organisms/ directory"],
  },
  {
    name: "PaymentGatewayConfig",
    atomicLevel: "organism",
    filePath: "features/sales/components/overlay/payment-gateway-config.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: [],
    description: "Payment gateway configuration overlay.",
  },
  {
    name: "AppointmentSheet",
    atomicLevel: "molecule",
    filePath: "features/sales/components/overlay/appointment-sheet.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: ["open", "onClose", "appointmentId"],
    description: "Side sheet for viewing/editing appointment details.",
  },
  {
    name: "AvailabilityModal",
    atomicLevel: "molecule",
    filePath: "features/sales/components/overlay/availability-modal.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: ["open", "onClose"],
    description: "Modal for setting availability hours.",
  },
  {
    name: "CalendarWidget",
    atomicLevel: "molecule",
    filePath: "features/sales/components/dashboard/calendar-widget.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: [],
    description: "Dashboard calendar showing upcoming appointments.",
  },
  {
    name: "ActivityFeedWidget",
    atomicLevel: "molecule",
    filePath: "features/sales/components/dashboard/activity-feed-widget.tsx",
    source: "feature",
    featureSlice: "sales",
    variants: [],
    props: [],
    description: "Dashboard widget showing recent sales activity.",
  },
];
