import type { ComponentEntry } from "./types";

// FEATURE slices: brand, connections, offer-studio, audit, admin, settings
export const REGISTRY_OTHER_FEATURES: ComponentEntry[] = [
  // ==========================================================================
  // FEATURE: brand (features/brand/components/)
  // ==========================================================================
  {
    name: "BrandEmptyState",
    atomicLevel: "atom",
    filePath: "features/brand/components/empty-state/brand-empty-state.tsx",
    source: "feature",
    featureSlice: "brand",
    variants: [],
    props: [],
    description: "Empty state for Brand Studio when no brand exists.",
  },
  {
    name: "EditSheetManager",
    atomicLevel: "organism",
    filePath: "features/brand/components/forms/edit-sheet-manager.tsx",
    source: "feature",
    featureSlice: "brand",
    variants: [],
    props: [],
    description: "Sheet manager for editing brand sections.",
  },
  {
    name: "SmartFillDialog",
    atomicLevel: "molecule",
    filePath: "features/brand/components/smart-fill/smart-fill-dialog.tsx",
    source: "feature",
    featureSlice: "brand",
    variants: [],
    props: ["open", "onClose"],
    description: "AI-powered auto-fill dialog for brand data.",
  },
  {
    name: "LegalManager",
    atomicLevel: "organism",
    filePath: "features/brand/components/legal/legal-manager.tsx",
    source: "feature",
    featureSlice: "brand",
    variants: [],
    props: [],
    description: "Manager for legal documents (terms, privacy).",
  },
  {
    name: "LegalForm",
    atomicLevel: "molecule",
    filePath: "features/brand/components/legal/legal-form.tsx",
    source: "feature",
    featureSlice: "brand",
    variants: [],
    props: ["type", "onSubmit"],
    description: "Form for editing legal documents.",
  },

  // ==========================================================================
  // FEATURE: connections (features/connections/components/)
  // ==========================================================================
  {
    name: "WhatsAppView",
    atomicLevel: "organism",
    filePath: "features/connections/components/whatsapp-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "WhatsApp connection config view.",
  },
  {
    name: "ManyChatView",
    atomicLevel: "organism",
    filePath: "features/connections/components/manychat-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "ManyChat connection config view.",
  },
  {
    name: "GoogleAnalyticsView",
    atomicLevel: "organism",
    filePath: "features/connections/components/google-analytics-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Google Analytics connection config view.",
  },
  {
    name: "GoogleWorkspaceView",
    atomicLevel: "organism",
    filePath: "features/connections/components/google-workspace-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Google Workspace connection config view.",
  },
  {
    name: "ShopifyView",
    atomicLevel: "organism",
    filePath: "features/connections/components/shopify-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Shopify connection config view.",
  },
  {
    name: "YouTubeView",
    atomicLevel: "organism",
    filePath: "features/connections/components/youtube-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "YouTube connection config view.",
  },
  {
    name: "MetaView",
    atomicLevel: "organism",
    filePath: "features/connections/components/meta-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Meta (Facebook/Instagram) connection config view.",
  },
  {
    name: "GmailView",
    atomicLevel: "organism",
    filePath: "features/connections/components/gmail-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Gmail connection config view.",
  },
  {
    name: "GoogleCalendarView",
    atomicLevel: "organism",
    filePath: "features/connections/components/google-calendar-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Google Calendar connection config view.",
  },
  {
    name: "MailerliteView",
    atomicLevel: "organism",
    filePath: "features/connections/components/mailerlite-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Mailerlite connection config view.",
  },
  {
    name: "TelegramView",
    atomicLevel: "organism",
    filePath: "features/connections/components/telegram-view.tsx",
    source: "feature",
    featureSlice: "connections",
    variants: [],
    props: [],
    description: "Telegram connection config view.",
  },

  // ==========================================================================
  // FEATURE: offer-studio (features/offer-studio/components/) — selected
  // ==========================================================================
  {
    name: "OfferNavRail",
    atomicLevel: "molecule",
    filePath: "features/offer-studio/components/navigation/OfferNavRail.tsx",
    source: "feature",
    featureSlice: "offer-studio",
    variants: [],
    props: [],
    description: "Navigation rail for Offer Studio sections.",
  },
  {
    name: "OfferStudioLayout",
    atomicLevel: "organism",
    filePath: "features/offer-studio/components/container/offer-studio-layout.tsx",
    source: "feature",
    featureSlice: "offer-studio",
    variants: [],
    props: [],
    description: "Layout container for Offer Studio.",
  },
  {
    name: "OfferEditor",
    atomicLevel: "organism",
    filePath: "features/offer-studio/components/editor/offer-editor.tsx",
    source: "feature",
    featureSlice: "offer-studio",
    variants: [],
    props: ["offerId"],
    description: "Main offer editing interface with sections.",
  },
  {
    name: "OfferEditSheetManager",
    atomicLevel: "organism",
    filePath: "features/offer-studio/components/editor/offer-edit-sheet-manager.tsx",
    source: "feature",
    featureSlice: "offer-studio",
    variants: [],
    props: [],
    description: "Sheet manager for offer editing overlays.",
    issues: ["Similar pattern to brand EditSheetManager — potential shared abstraction"],
  },
  {
    name: "OfferLivePreview",
    atomicLevel: "organism",
    filePath: "features/offer-studio/components/editor/offer-live-preview.tsx",
    source: "feature",
    featureSlice: "offer-studio",
    variants: [],
    props: ["offer"],
    description: "Live preview of offer as landing page.",
  },
  {
    name: "AiAssistButton",
    atomicLevel: "atom",
    filePath: "features/offer-studio/components/editor/components/ai-assist-button.tsx",
    source: "feature",
    featureSlice: "offer-studio",
    variants: [],
    props: ["onClick", "loading"],
    description: "AI auto-fill trigger button.",
    issues: ["Could be promoted to shared/ — useful across studios"],
  },

  // ==========================================================================
  // FEATURE: audit (features/audit/components/)
  // ==========================================================================
  {
    name: "AuditDashboard",
    atomicLevel: "organism",
    filePath: "features/audit/components/AuditDashboard.tsx",
    source: "feature",
    featureSlice: "audit",
    variants: [],
    props: [],
    description: "Main audit/conversation trace dashboard.",
  },
  {
    name: "TraceInspector",
    atomicLevel: "organism",
    filePath: "features/audit/components/trace-inspector.tsx",
    source: "feature",
    featureSlice: "audit",
    variants: [],
    props: ["traceId"],
    description: "LangGraph trace visualization and inspection.",
  },
  {
    name: "ContextPanel",
    atomicLevel: "molecule",
    filePath: "features/audit/components/context-panel.tsx",
    source: "feature",
    featureSlice: "audit",
    variants: [],
    props: ["context"],
    description: "Context data panel for trace inspection.",
  },
  {
    name: "NodeDetailsPanel",
    atomicLevel: "molecule",
    filePath: "features/audit/components/node-details-panel.tsx",
    source: "feature",
    featureSlice: "audit",
    variants: [],
    props: ["node"],
    description: "Details panel for a single graph node in trace.",
  },
  {
    name: "UserList",
    atomicLevel: "molecule",
    filePath: "features/audit/components/user-list.tsx",
    source: "feature",
    featureSlice: "audit",
    variants: [],
    props: ["users"],
    description: "User list for filtering audit conversations.",
  },
  {
    name: "ChatTimeline",
    atomicLevel: "molecule",
    filePath: "features/audit/components/chat-timeline.tsx",
    source: "feature",
    featureSlice: "audit",
    variants: [],
    props: ["messages"],
    description: "Chat message timeline visualization.",
  },
  {
    name: "NodeIcons",
    atomicLevel: "atom",
    filePath: "features/audit/components/node-icons.tsx",
    source: "feature",
    featureSlice: "audit",
    variants: [],
    props: ["nodeType"],
    description: "Icon set for graph node types.",
  },

  // ==========================================================================
  // FEATURE: admin (features/admin/components/)
  // ==========================================================================
  {
    name: "TenantsList",
    atomicLevel: "organism",
    filePath: "features/admin/components/tenants-list.tsx",
    source: "feature",
    featureSlice: "admin",
    variants: [],
    props: [],
    description: "Admin tenant management list.",
  },

  // ==========================================================================
  // FEATURE: settings (features/settings/components/)
  // ==========================================================================
  {
    name: "SettingsView",
    atomicLevel: "organism",
    filePath: "features/settings/components/SettingsView.tsx",
    source: "feature",
    featureSlice: "settings",
    variants: [],
    props: [],
    description: "Main settings page layout with tabs.",
  },
  {
    name: "TeamView",
    atomicLevel: "organism",
    filePath: "features/settings/components/team-view.tsx",
    source: "feature",
    featureSlice: "settings",
    variants: [],
    props: [],
    description: "Team member management view.",
  },
  {
    name: "WebhookView",
    atomicLevel: "organism",
    filePath: "features/settings/components/webhook-view.tsx",
    source: "feature",
    featureSlice: "settings",
    variants: [],
    props: [],
    description: "Webhook configuration view.",
  },
  {
    name: "AiKeysForm",
    atomicLevel: "molecule",
    filePath: "features/settings/components/ai-keys-form.tsx",
    source: "feature",
    featureSlice: "settings",
    variants: [],
    props: [],
    description: "Form for configuring AI API keys.",
  },
  {
    name: "GeneralSettingsForm",
    atomicLevel: "molecule",
    filePath: "features/settings/components/general-settings-form.tsx",
    source: "feature",
    featureSlice: "settings",
    variants: [],
    props: [],
    description: "General tenant settings form.",
  },
  {
    name: "ProfileView",
    atomicLevel: "organism",
    filePath: "features/settings/components/profile-view.tsx",
    source: "feature",
    featureSlice: "settings",
    variants: [],
    props: [],
    description: "User profile settings view.",
  },
];
