import type { ComponentEntry } from "./types";

// SHADCN PRIMITIVES (components/ui/) + SHARED COMPONENTS
export const REGISTRY_PRIMITIVES: ComponentEntry[] = [
  // ==========================================================================
  // SHADCN PRIMITIVES (components/ui/) — 37 files
  // ==========================================================================

  // --- Atoms ---
  {
    name: "Accordion",
    atomicLevel: "atom",
    filePath: "components/ui/accordion.tsx",
    source: "shadcn",
    variants: [],
    props: ["type", "collapsible", "value", "onValueChange"],
    description: "Expandable/collapsible content sections.",
  },
  {
    name: "Alert",
    atomicLevel: "atom",
    filePath: "components/ui/alert.tsx",
    source: "shadcn",
    variants: ["default", "destructive"],
    props: ["variant"],
    description: "Contextual feedback messages.",
  },
  {
    name: "Avatar",
    atomicLevel: "atom",
    filePath: "components/ui/avatar.tsx",
    source: "shadcn",
    variants: [],
    props: ["src", "alt", "fallback"],
    description: "User or entity avatar with fallback.",
  },
  {
    name: "Badge",
    atomicLevel: "atom",
    filePath: "components/ui/badge.tsx",
    source: "shadcn",
    variants: ["default", "secondary", "destructive", "outline"],
    props: ["variant"],
    description: "Small status/label indicator with CVA variants.",
  },
  {
    name: "Button",
    atomicLevel: "atom",
    filePath: "components/ui/button.tsx",
    source: "shadcn",
    variants: ["default", "destructive", "outline", "secondary", "ghost", "link"],
    props: ["variant", "size", "asChild"],
    description: "Primary action trigger with CVA variants and sizes.",
  },
  {
    name: "LoadingButton",
    atomicLevel: "atom",
    filePath: "components/ui/loading-button.tsx",
    source: "shared",
    variants: [],
    props: ["loading", "loadingText", "...ButtonProps"],
    description: "Button wrapper that shows a spinner and optional loading text when loading=true.",
  },
  {
    name: "Checkbox",
    atomicLevel: "atom",
    filePath: "components/ui/checkbox.tsx",
    source: "shadcn",
    variants: [],
    props: ["checked", "onCheckedChange", "disabled"],
    description: "Boolean toggle input.",
  },
  {
    name: "Collapsible",
    atomicLevel: "atom",
    filePath: "components/ui/collapsible.tsx",
    source: "shadcn",
    variants: [],
    props: ["open", "onOpenChange"],
    description: "Radix collapsible primitive wrapper.",
  },
  {
    name: "Input",
    atomicLevel: "atom",
    filePath: "components/ui/input.tsx",
    source: "shadcn",
    variants: [],
    props: ["type", "placeholder", "disabled"],
    description: "Text input field. No CVA — uses raw className merge.",
    issues: ["No CVA variants for size/state — relies on className override"],
  },
  {
    name: "Label",
    atomicLevel: "atom",
    filePath: "components/ui/label.tsx",
    source: "shadcn",
    variants: [],
    props: ["htmlFor"],
    description: "Form field label tied to Radix Label primitive.",
  },
  {
    name: "Progress",
    atomicLevel: "atom",
    filePath: "components/ui/progress.tsx",
    source: "shadcn",
    variants: [],
    props: ["value", "max"],
    description: "Progress bar indicator.",
  },
  {
    name: "RadioGroup",
    atomicLevel: "atom",
    filePath: "components/ui/radio-group.tsx",
    source: "shadcn",
    variants: [],
    props: ["value", "onValueChange", "disabled"],
    description: "Radio button group selection.",
  },
  {
    name: "ScrollArea",
    atomicLevel: "atom",
    filePath: "components/ui/scroll-area.tsx",
    source: "shadcn",
    variants: [],
    props: ["className"],
    description: "Custom scrollbar area using Radix ScrollArea.",
  },
  {
    name: "Select",
    atomicLevel: "atom",
    filePath: "components/ui/select.tsx",
    source: "shadcn",
    variants: [],
    props: ["value", "onValueChange", "placeholder"],
    description: "Standard dropdown select using Radix Select.",
  },
  {
    name: "Separator",
    atomicLevel: "atom",
    filePath: "components/ui/separator.tsx",
    source: "shadcn",
    variants: [],
    props: ["orientation", "decorative"],
    description: "Visual divider (horizontal/vertical).",
  },
  {
    name: "Skeleton",
    atomicLevel: "atom",
    filePath: "components/ui/skeleton.tsx",
    source: "shadcn",
    variants: [],
    props: ["className"],
    description: "Loading placeholder animation.",
  },
  {
    name: "Switch",
    atomicLevel: "atom",
    filePath: "components/ui/switch.tsx",
    source: "shadcn",
    variants: [],
    props: ["checked", "onCheckedChange", "disabled"],
    description: "Toggle switch input.",
  },
  {
    name: "Textarea",
    atomicLevel: "atom",
    filePath: "components/ui/textarea.tsx",
    source: "shadcn",
    variants: [],
    props: ["placeholder", "rows", "disabled"],
    description: "Multi-line text input. No CVA.",
    issues: ["No CVA variants — same pattern issue as Input"],
  },
  {
    name: "Tooltip",
    atomicLevel: "atom",
    filePath: "components/ui/tooltip.tsx",
    source: "shadcn",
    variants: [],
    props: ["content", "side", "align"],
    description: "Hover tooltip using Radix Tooltip.",
  },

  // --- Molecules (compose multiple atoms or have complex internal state) ---
  {
    name: "AlertDialog",
    atomicLevel: "molecule",
    filePath: "components/ui/alert-dialog.tsx",
    source: "shadcn",
    variants: [],
    props: ["open", "onOpenChange"],
    description: "Confirmation dialog with action/cancel. Composes overlay + content + buttons.",
  },
  {
    name: "Calendar",
    atomicLevel: "molecule",
    filePath: "components/ui/calendar.tsx",
    source: "shadcn",
    variants: [],
    props: ["mode", "selected", "onSelect", "disabled"],
    description: "Date picker calendar using react-day-picker.",
  },
  {
    name: "Card",
    atomicLevel: "molecule",
    filePath: "components/ui/card.tsx",
    source: "shadcn",
    variants: [],
    props: ["className"],
    description: "Content container with Header/Content/Footer/Title/Description sub-components.",
    issues: ["No CVA — could benefit from variant support (elevated, outlined, flat)"],
  },
  {
    name: "Command",
    atomicLevel: "molecule",
    filePath: "components/ui/command.tsx",
    source: "shadcn",
    variants: [],
    props: ["value", "onValueChange", "filter"],
    description: "Command palette / searchable list (cmdk). Composes input + list + items.",
  },
  {
    name: "Dialog",
    atomicLevel: "molecule",
    filePath: "components/ui/dialog.tsx",
    source: "shadcn",
    variants: [],
    props: ["open", "onOpenChange"],
    description: "Modal dialog with overlay, content, header, footer.",
  },
  {
    name: "DropdownMenu",
    atomicLevel: "molecule",
    filePath: "components/ui/dropdown-menu.tsx",
    source: "shadcn",
    variants: [],
    props: ["open", "onOpenChange"],
    description: "Context/dropdown menu with items, sub-menus, separators.",
  },
  {
    name: "Form",
    atomicLevel: "molecule",
    filePath: "components/ui/form.tsx",
    source: "shadcn",
    variants: [],
    props: ["control", "name", "render"],
    description: "react-hook-form integration with FormField/FormItem/FormControl/FormMessage.",
  },
  {
    name: "Popover",
    atomicLevel: "molecule",
    filePath: "components/ui/popover.tsx",
    source: "shadcn",
    variants: [],
    props: ["open", "onOpenChange"],
    description: "Floating popover panel triggered by a button.",
  },
  {
    name: "Sheet",
    atomicLevel: "molecule",
    filePath: "components/ui/sheet.tsx",
    source: "shadcn",
    variants: ["top", "bottom", "left", "right"],
    props: ["open", "onOpenChange", "side"],
    description: "Slide-out panel with CVA side variants.",
  },
  {
    name: "DetailPanel",
    atomicLevel: "molecule",
    filePath: "components/ui/detail-panel.tsx",
    source: "shared",
    variants: [],
    props: ["open", "onClose", "className"],
    description:
      "Copilot-aware slide-out detail panel. Positions itself to the left of the CopilotSidebar (respects open/rail width). Use instead of Sheet when the panel must coexist with the copilot.",
  },
  {
    name: "Table",
    atomicLevel: "molecule",
    filePath: "components/ui/table.tsx",
    source: "shadcn",
    variants: [],
    props: ["className"],
    description: "HTML table wrapper with Header/Body/Row/Head/Cell/Caption/Footer.",
  },
  {
    name: "Tabs",
    atomicLevel: "molecule",
    filePath: "components/ui/tabs.tsx",
    source: "shadcn",
    variants: [],
    props: ["value", "onValueChange", "defaultValue"],
    description: "Tab navigation with TabsList/TabsTrigger/TabsContent.",
  },

  // --- Custom UI (non-standard Shadcn — project additions) ---
  {
    name: "CurrencySelector",
    atomicLevel: "molecule",
    filePath: "components/ui/currency-selector.tsx",
    source: "shadcn",
    variants: [],
    props: ["value", "onValueChange"],
    description: "Currency picker using Command + Popover composition.",
    issues: ["Custom addition to ui/ — should be in shared/ or feature/"],
  },
  {
    name: "FieldInfo",
    atomicLevel: "atom",
    filePath: "components/ui/field-info.tsx",
    source: "shadcn",
    variants: [],
    props: ["text"],
    description: "Info icon with tooltip for form field hints.",
    issues: ["Custom addition to ui/ — not a Shadcn primitive"],
  },
  {
    name: "HighlightedText",
    atomicLevel: "atom",
    filePath: "components/ui/highlighted-text.tsx",
    source: "shadcn",
    variants: [],
    props: ["text", "highlight", "className"],
    description: "Text with search-term highlighting.",
    issues: ["Custom addition to ui/ — should be in shared/"],
  },
  {
    name: "RichSelect",
    atomicLevel: "molecule",
    filePath: "components/ui/rich-select.tsx",
    source: "shadcn",
    variants: [],
    props: ["value", "onValueChange", "options"],
    description: "Enhanced select with rich option rendering.",
    issues: ["Custom addition to ui/ — wraps Select with extra features"],
  },
  {
    name: "SmartDatetimePicker",
    atomicLevel: "molecule",
    filePath: "components/ui/smart-datetime-picker.tsx",
    source: "shadcn",
    variants: [],
    props: ["value", "onChange", "minDate"],
    description: "Date + time picker combining Calendar + time input.",
    issues: ["Custom addition to ui/ — complex molecule in atom directory"],
  },
  {
    name: "Sonner",
    atomicLevel: "atom",
    filePath: "components/ui/sonner.tsx",
    source: "shadcn",
    variants: [],
    props: ["theme", "position"],
    description: "Toast notification provider (sonner library wrapper).",
  },
  {
    name: "TimezoneSelect",
    atomicLevel: "molecule",
    filePath: "components/ui/timezone-select.tsx",
    source: "shadcn",
    variants: [],
    props: ["value", "onValueChange"],
    description: "Timezone picker using Command + Popover composition.",
    issues: ["Custom addition to ui/ — should be in shared/ or feature/"],
  },

  // ==========================================================================
  // SHARED COMPONENTS (components/shared/)
  // ==========================================================================

  {
    name: "ErrorBoundary",
    atomicLevel: "atom",
    filePath: "components/shared/error-boundary.tsx",
    source: "shared",
    variants: [],
    props: ["children"],
    description: "React error boundary with fallback UI.",
    issues: ["Class component — could be updated to use react-error-boundary package"],
  },
  {
    name: "DevelopmentTools",
    atomicLevel: "atom",
    filePath: "components/shared/development-tools.tsx",
    source: "shared",
    variants: [],
    props: [],
    description: "React Query DevTools loader (dev-only).",
  },
  {
    name: "ModeToggle",
    atomicLevel: "atom",
    filePath: "components/shared/mode-toggle.tsx",
    source: "shared",
    variants: [],
    props: [],
    description: "Dark/light mode toggle button using next-themes.",
  },
  {
    name: "AppSidebar",
    atomicLevel: "organism",
    filePath: "components/shared/layout/app-sidebar.tsx",
    source: "shared",
    variants: [],
    props: [],
    description: "Main application sidebar navigation.",
  },
  {
    name: "SidebarContext",
    atomicLevel: "atom",
    filePath: "components/shared/layout/sidebar-context.tsx",
    source: "shared",
    variants: [],
    props: [],
    description: "React context provider for sidebar open/collapsed state.",
  },
  {
    name: "TenantSwitcher",
    atomicLevel: "molecule",
    filePath: "components/shared/layout/tenant-switcher.tsx",
    source: "shared",
    variants: [],
    props: [],
    description: "Dropdown for switching active tenant (multitenant).",
  },
];
