/**
 * Component Registry — Single source of truth for all frontend components.
 *
 * Machine-readable catalog used by:
 * 1. Playground page (/playground/design-system) for visual browsing
 * 2. Claude (AI) before generating any new component — check what exists first
 * 3. Audit tooling to detect duplications and inconsistencies
 *
 * Last audited: 2026-03-18
 */

import type { ComponentEntry, DesignToken } from './types';

// ---------------------------------------------------------------------------
// COMPONENT REGISTRY
// ---------------------------------------------------------------------------

export const COMPONENT_REGISTRY: ComponentEntry[] = [
  // ==========================================================================
  // SHADCN PRIMITIVES (components/ui/) — 37 files
  // ==========================================================================

  // --- Atoms ---
  {
    name: 'Accordion',
    atomicLevel: 'atom',
    filePath: 'components/ui/accordion.tsx',
    source: 'shadcn',
    variants: [],
    props: ['type', 'collapsible', 'value', 'onValueChange'],
    description: 'Expandable/collapsible content sections.',
  },
  {
    name: 'Alert',
    atomicLevel: 'atom',
    filePath: 'components/ui/alert.tsx',
    source: 'shadcn',
    variants: ['default', 'destructive'],
    props: ['variant'],
    description: 'Contextual feedback messages.',
  },
  {
    name: 'Avatar',
    atomicLevel: 'atom',
    filePath: 'components/ui/avatar.tsx',
    source: 'shadcn',
    variants: [],
    props: ['src', 'alt', 'fallback'],
    description: 'User or entity avatar with fallback.',
  },
  {
    name: 'Badge',
    atomicLevel: 'atom',
    filePath: 'components/ui/badge.tsx',
    source: 'shadcn',
    variants: ['default', 'secondary', 'destructive', 'outline'],
    props: ['variant'],
    description: 'Small status/label indicator with CVA variants.',
  },
  {
    name: 'Button',
    atomicLevel: 'atom',
    filePath: 'components/ui/button.tsx',
    source: 'shadcn',
    variants: ['default', 'destructive', 'outline', 'secondary', 'ghost', 'link'],
    props: ['variant', 'size', 'asChild'],
    description: 'Primary action trigger with CVA variants and sizes.',
  },
  {
    name: 'Checkbox',
    atomicLevel: 'atom',
    filePath: 'components/ui/checkbox.tsx',
    source: 'shadcn',
    variants: [],
    props: ['checked', 'onCheckedChange', 'disabled'],
    description: 'Boolean toggle input.',
  },
  {
    name: 'Collapsible',
    atomicLevel: 'atom',
    filePath: 'components/ui/collapsible.tsx',
    source: 'shadcn',
    variants: [],
    props: ['open', 'onOpenChange'],
    description: 'Radix collapsible primitive wrapper.',
  },
  {
    name: 'Input',
    atomicLevel: 'atom',
    filePath: 'components/ui/input.tsx',
    source: 'shadcn',
    variants: [],
    props: ['type', 'placeholder', 'disabled'],
    description: 'Text input field. No CVA — uses raw className merge.',
    issues: ['No CVA variants for size/state — relies on className override'],
  },
  {
    name: 'Label',
    atomicLevel: 'atom',
    filePath: 'components/ui/label.tsx',
    source: 'shadcn',
    variants: [],
    props: ['htmlFor'],
    description: 'Form field label tied to Radix Label primitive.',
  },
  {
    name: 'Progress',
    atomicLevel: 'atom',
    filePath: 'components/ui/progress.tsx',
    source: 'shadcn',
    variants: [],
    props: ['value', 'max'],
    description: 'Progress bar indicator.',
  },
  {
    name: 'RadioGroup',
    atomicLevel: 'atom',
    filePath: 'components/ui/radio-group.tsx',
    source: 'shadcn',
    variants: [],
    props: ['value', 'onValueChange', 'disabled'],
    description: 'Radio button group selection.',
  },
  {
    name: 'ScrollArea',
    atomicLevel: 'atom',
    filePath: 'components/ui/scroll-area.tsx',
    source: 'shadcn',
    variants: [],
    props: ['className'],
    description: 'Custom scrollbar area using Radix ScrollArea.',
  },
  {
    name: 'Select',
    atomicLevel: 'atom',
    filePath: 'components/ui/select.tsx',
    source: 'shadcn',
    variants: [],
    props: ['value', 'onValueChange', 'placeholder'],
    description: 'Standard dropdown select using Radix Select.',
  },
  {
    name: 'Separator',
    atomicLevel: 'atom',
    filePath: 'components/ui/separator.tsx',
    source: 'shadcn',
    variants: [],
    props: ['orientation', 'decorative'],
    description: 'Visual divider (horizontal/vertical).',
  },
  {
    name: 'Skeleton',
    atomicLevel: 'atom',
    filePath: 'components/ui/skeleton.tsx',
    source: 'shadcn',
    variants: [],
    props: ['className'],
    description: 'Loading placeholder animation.',
  },
  {
    name: 'Switch',
    atomicLevel: 'atom',
    filePath: 'components/ui/switch.tsx',
    source: 'shadcn',
    variants: [],
    props: ['checked', 'onCheckedChange', 'disabled'],
    description: 'Toggle switch input.',
  },
  {
    name: 'Textarea',
    atomicLevel: 'atom',
    filePath: 'components/ui/textarea.tsx',
    source: 'shadcn',
    variants: [],
    props: ['placeholder', 'rows', 'disabled'],
    description: 'Multi-line text input. No CVA.',
    issues: ['No CVA variants — same pattern issue as Input'],
  },
  {
    name: 'Tooltip',
    atomicLevel: 'atom',
    filePath: 'components/ui/tooltip.tsx',
    source: 'shadcn',
    variants: [],
    props: ['content', 'side', 'align'],
    description: 'Hover tooltip using Radix Tooltip.',
  },

  // --- Molecules (compose multiple atoms or have complex internal state) ---
  {
    name: 'AlertDialog',
    atomicLevel: 'molecule',
    filePath: 'components/ui/alert-dialog.tsx',
    source: 'shadcn',
    variants: [],
    props: ['open', 'onOpenChange'],
    description: 'Confirmation dialog with action/cancel. Composes overlay + content + buttons.',
  },
  {
    name: 'Calendar',
    atomicLevel: 'molecule',
    filePath: 'components/ui/calendar.tsx',
    source: 'shadcn',
    variants: [],
    props: ['mode', 'selected', 'onSelect', 'disabled'],
    description: 'Date picker calendar using react-day-picker.',
  },
  {
    name: 'Card',
    atomicLevel: 'molecule',
    filePath: 'components/ui/card.tsx',
    source: 'shadcn',
    variants: [],
    props: ['className'],
    description: 'Content container with Header/Content/Footer/Title/Description sub-components.',
    issues: ['No CVA — could benefit from variant support (elevated, outlined, flat)'],
  },
  {
    name: 'Command',
    atomicLevel: 'molecule',
    filePath: 'components/ui/command.tsx',
    source: 'shadcn',
    variants: [],
    props: ['value', 'onValueChange', 'filter'],
    description: 'Command palette / searchable list (cmdk). Composes input + list + items.',
  },
  {
    name: 'Dialog',
    atomicLevel: 'molecule',
    filePath: 'components/ui/dialog.tsx',
    source: 'shadcn',
    variants: [],
    props: ['open', 'onOpenChange'],
    description: 'Modal dialog with overlay, content, header, footer.',
  },
  {
    name: 'DropdownMenu',
    atomicLevel: 'molecule',
    filePath: 'components/ui/dropdown-menu.tsx',
    source: 'shadcn',
    variants: [],
    props: ['open', 'onOpenChange'],
    description: 'Context/dropdown menu with items, sub-menus, separators.',
  },
  {
    name: 'Form',
    atomicLevel: 'molecule',
    filePath: 'components/ui/form.tsx',
    source: 'shadcn',
    variants: [],
    props: ['control', 'name', 'render'],
    description: 'react-hook-form integration with FormField/FormItem/FormControl/FormMessage.',
  },
  {
    name: 'Popover',
    atomicLevel: 'molecule',
    filePath: 'components/ui/popover.tsx',
    source: 'shadcn',
    variants: [],
    props: ['open', 'onOpenChange'],
    description: 'Floating popover panel triggered by a button.',
  },
  {
    name: 'Sheet',
    atomicLevel: 'molecule',
    filePath: 'components/ui/sheet.tsx',
    source: 'shadcn',
    variants: ['top', 'bottom', 'left', 'right'],
    props: ['open', 'onOpenChange', 'side'],
    description: 'Slide-out panel with CVA side variants.',
  },
  {
    name: 'DetailPanel',
    atomicLevel: 'molecule',
    filePath: 'components/ui/detail-panel.tsx',
    source: 'shared',
    variants: [],
    props: ['open', 'onClose', 'className'],
    description:
      'Copilot-aware slide-out detail panel. Positions itself to the left of the CopilotPanel (respects open/rail width). Use instead of Sheet when the panel must coexist with the copilot.',
  },
  {
    name: 'Table',
    atomicLevel: 'molecule',
    filePath: 'components/ui/table.tsx',
    source: 'shadcn',
    variants: [],
    props: ['className'],
    description: 'HTML table wrapper with Header/Body/Row/Head/Cell/Caption/Footer.',
  },
  {
    name: 'Tabs',
    atomicLevel: 'molecule',
    filePath: 'components/ui/tabs.tsx',
    source: 'shadcn',
    variants: [],
    props: ['value', 'onValueChange', 'defaultValue'],
    description: 'Tab navigation with TabsList/TabsTrigger/TabsContent.',
  },

  // --- Custom UI (non-standard Shadcn — project additions) ---
  {
    name: 'CurrencySelector',
    atomicLevel: 'molecule',
    filePath: 'components/ui/currency-selector.tsx',
    source: 'shadcn',
    variants: [],
    props: ['value', 'onValueChange'],
    description: 'Currency picker using Command + Popover composition.',
    issues: ['Custom addition to ui/ — should be in shared/ or feature/'],
  },
  {
    name: 'FieldInfo',
    atomicLevel: 'atom',
    filePath: 'components/ui/field-info.tsx',
    source: 'shadcn',
    variants: [],
    props: ['text'],
    description: 'Info icon with tooltip for form field hints.',
    issues: ['Custom addition to ui/ — not a Shadcn primitive'],
  },
  {
    name: 'HighlightedText',
    atomicLevel: 'atom',
    filePath: 'components/ui/highlighted-text.tsx',
    source: 'shadcn',
    variants: [],
    props: ['text', 'highlight', 'className'],
    description: 'Text with search-term highlighting.',
    issues: ['Custom addition to ui/ — should be in shared/'],
  },
  {
    name: 'RichSelect',
    atomicLevel: 'molecule',
    filePath: 'components/ui/rich-select.tsx',
    source: 'shadcn',
    variants: [],
    props: ['value', 'onValueChange', 'options'],
    description: 'Enhanced select with rich option rendering.',
    issues: ['Custom addition to ui/ — wraps Select with extra features'],
  },
  {
    name: 'SmartDatetimePicker',
    atomicLevel: 'molecule',
    filePath: 'components/ui/smart-datetime-picker.tsx',
    source: 'shadcn',
    variants: [],
    props: ['value', 'onChange', 'minDate'],
    description: 'Date + time picker combining Calendar + time input.',
    issues: ['Custom addition to ui/ — complex molecule in atom directory'],
  },
  {
    name: 'Sonner',
    atomicLevel: 'atom',
    filePath: 'components/ui/sonner.tsx',
    source: 'shadcn',
    variants: [],
    props: ['theme', 'position'],
    description: 'Toast notification provider (sonner library wrapper).',
  },
  {
    name: 'TimezoneSelect',
    atomicLevel: 'molecule',
    filePath: 'components/ui/timezone-select.tsx',
    source: 'shadcn',
    variants: [],
    props: ['value', 'onValueChange'],
    description: 'Timezone picker using Command + Popover composition.',
    issues: ['Custom addition to ui/ — should be in shared/ or feature/'],
  },

  // ==========================================================================
  // SHARED COMPONENTS (components/shared/)
  // ==========================================================================

  {
    name: 'ErrorBoundary',
    atomicLevel: 'atom',
    filePath: 'components/shared/error-boundary.tsx',
    source: 'shared',
    variants: [],
    props: ['children'],
    description: 'React error boundary with fallback UI.',
    issues: ['Class component — could be updated to use react-error-boundary package'],
  },
  {
    name: 'DevelopmentTools',
    atomicLevel: 'atom',
    filePath: 'components/shared/development-tools.tsx',
    source: 'shared',
    variants: [],
    props: [],
    description: 'React Query DevTools loader (dev-only).',
  },
  {
    name: 'ModeToggle',
    atomicLevel: 'atom',
    filePath: 'components/shared/mode-toggle.tsx',
    source: 'shared',
    variants: [],
    props: [],
    description: 'Dark/light mode toggle button using next-themes.',
  },
  {
    name: 'AppSidebar',
    atomicLevel: 'organism',
    filePath: 'components/shared/layout/app-sidebar.tsx',
    source: 'shared',
    variants: [],
    props: [],
    description: 'Main application sidebar navigation.',
  },
  {
    name: 'SidebarContext',
    atomicLevel: 'atom',
    filePath: 'components/shared/layout/sidebar-context.tsx',
    source: 'shared',
    variants: [],
    props: [],
    description: 'React context provider for sidebar open/collapsed state.',
  },
  {
    name: 'TenantSwitcher',
    atomicLevel: 'molecule',
    filePath: 'components/shared/layout/tenant-switcher.tsx',
    source: 'shared',
    variants: [],
    props: [],
    description: 'Dropdown for switching active tenant (multitenant).',
  },

  // ==========================================================================
  // FEATURE: sales (features/sales/components/)
  // ==========================================================================

  // --- Atoms ---
  {
    name: 'ScoreRing',
    atomicLevel: 'atom',
    filePath: 'features/sales/components/atoms/ScoreRing.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['score', 'size'],
    description: 'Circular score visualization ring.',
  },
  {
    name: 'ActionIcon',
    atomicLevel: 'atom',
    filePath: 'features/sales/components/atoms/ActionIcon.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['action', 'size'],
    description: 'Icon representing a sales action type.',
  },
  {
    name: 'LeadAvatar',
    atomicLevel: 'atom',
    filePath: 'features/sales/components/atoms/LeadAvatar.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['name', 'imageUrl', 'size'],
    description: 'Lead profile avatar with initials fallback.',
    issues: ['Duplicates Avatar from shadcn — could extend it instead'],
  },
  {
    name: 'TemperatureBadge',
    atomicLevel: 'atom',
    filePath: 'features/sales/components/atoms/TemperatureBadge.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['temperature'],
    description: 'Color-coded lead temperature indicator (hot/warm/cold).',
  },

  // --- Molecules ---
  {
    name: 'IdentityHeader',
    atomicLevel: 'molecule',
    filePath: 'features/sales/components/molecules/IdentityHeader.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['lead'],
    description: 'Lead identity display with avatar, name, contact info.',
  },
  {
    name: 'LeadCard',
    atomicLevel: 'molecule',
    filePath: 'features/sales/components/molecules/LeadCard.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['lead', 'onClick'],
    description: 'Kanban card for a single lead with score, temperature, summary.',
  },

  // --- Organisms ---
  {
    name: 'LeadCommandCenter',
    atomicLevel: 'organism',
    filePath: 'features/sales/components/organisms/LeadCommandCenter.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['leadId'],
    description: 'Full lead detail panel with tabs, timeline, actions.',
  },
  {
    name: 'PipelineBoard',
    atomicLevel: 'organism',
    filePath: 'features/sales/components/organisms/PipelineBoard.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['stages', 'leads'],
    description: 'Kanban board for sales pipeline with drag-and-drop lanes.',
  },

  // --- Other sales components (unclassified in source) ---
  {
    name: 'SalesDashboard',
    atomicLevel: 'organism',
    filePath: 'features/sales/components/sales-dashboard.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: [],
    description: 'Main sales dashboard page component.',
    issues: ['Organism-level but not in organisms/ directory'],
  },
  {
    name: 'GenerateLinkModal',
    atomicLevel: 'molecule',
    filePath: 'features/sales/components/generate-link-modal.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['open', 'onClose'],
    description: 'Modal for generating shareable payment/scheduling links.',
    issues: ['Not in molecules/ directory'],
  },
  {
    name: 'AvailabilityView',
    atomicLevel: 'organism',
    filePath: 'features/sales/components/availability-view.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: [],
    description: 'Availability configuration view for scheduling.',
    issues: ['Not in organisms/ directory'],
  },
  {
    name: 'EventTypeForm',
    atomicLevel: 'molecule',
    filePath: 'features/sales/components/event-type-form.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['eventType', 'onSubmit'],
    description: 'Form for creating/editing scheduling event types.',
    issues: ['Not in molecules/ directory'],
  },
  {
    name: 'EventTypeView',
    atomicLevel: 'organism',
    filePath: 'features/sales/components/event-type-view.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: [],
    description: 'List/manage event types for scheduling.',
    issues: ['Not in organisms/ directory'],
  },
  {
    name: 'PaymentGatewayConfig',
    atomicLevel: 'organism',
    filePath: 'features/sales/components/overlay/payment-gateway-config.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: [],
    description: 'Payment gateway configuration overlay.',
  },
  {
    name: 'AppointmentSheet',
    atomicLevel: 'molecule',
    filePath: 'features/sales/components/overlay/appointment-sheet.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['open', 'onClose', 'appointmentId'],
    description: 'Side sheet for viewing/editing appointment details.',
  },
  {
    name: 'SalesInboxSheet',
    atomicLevel: 'organism',
    filePath: 'features/sales/components/overlay/sales-inbox-sheet.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['open', 'onClose'],
    description: 'Side sheet showing sales conversation inbox.',
  },
  {
    name: 'AvailabilityModal',
    atomicLevel: 'molecule',
    filePath: 'features/sales/components/overlay/availability-modal.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['open', 'onClose'],
    description: 'Modal for setting availability hours.',
  },
  {
    name: 'CalendarWidget',
    atomicLevel: 'molecule',
    filePath: 'features/sales/components/dashboard/calendar-widget.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: [],
    description: 'Dashboard calendar showing upcoming appointments.',
  },
  {
    name: 'ActivityFeedWidget',
    atomicLevel: 'molecule',
    filePath: 'features/sales/components/dashboard/activity-feed-widget.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: [],
    description: 'Dashboard widget showing recent sales activity.',
  },
  {
    name: 'ConversionCommandCenter',
    atomicLevel: 'organism',
    filePath: 'features/sales/components/dashboard/conversion-command-center.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: [],
    description: 'Main conversion metrics and actions dashboard section.',
  },
  {
    name: 'SalesLane',
    atomicLevel: 'molecule',
    filePath: 'features/sales/components/dashboard/lanes/sales-lane.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['leads', 'stage'],
    description: 'Single lane in the pipeline kanban board.',
  },
  {
    name: 'AgendaLane',
    atomicLevel: 'molecule',
    filePath: 'features/sales/components/dashboard/lanes/agenda-lane.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['appointments'],
    description: 'Agenda/calendar lane for scheduled items.',
  },
  {
    name: 'OpportunityLane',
    atomicLevel: 'molecule',
    filePath: 'features/sales/components/dashboard/lanes/opportunity-lane.tsx',
    source: 'feature',
    featureSlice: 'sales',
    variants: [],
    props: ['opportunities'],
    description: 'Pipeline lane for active opportunities.',
  },

  // ==========================================================================
  // FEATURE: marketing-studio (features/marketing-studio/components/)
  // ==========================================================================

  // --- Organisms (dashboard containers) ---
  {
    name: 'MetricsDashboard',
    atomicLevel: 'organism',
    filePath: 'features/marketing-studio/components/metrics-dashboard/MetricsDashboard.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: [],
    description: 'Main Growth Studio dashboard — bowtie funnel with stage cards + detail panels.',
  },
  {
    name: 'MetricSidebar',
    atomicLevel: 'organism',
    filePath: 'features/marketing-studio/components/metrics-dashboard/sidebar/MetricSidebar.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['children'],
    description: 'Sidebar container for metric details.',
  },
  {
    name: 'SidebarContent',
    atomicLevel: 'organism',
    filePath: 'features/marketing-studio/components/metrics-dashboard/sidebar/SidebarContent.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['stageId'],
    description: 'Polymorphic sidebar content renderer per bowtie stage.',
  },

  // --- Molecules (stage/channel widgets) ---
  {
    name: 'StageCard',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/metrics-dashboard/stage-widgets/StageCard.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['stage', 'onClick', 'active'],
    description: 'Bowtie funnel stage card with KPIs.',
  },
  {
    name: 'StageSummaryRow',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/metrics-dashboard/stage-widgets/StageSummaryRow.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['label', 'value', 'trend'],
    description: 'Summary row inside a stage card.',
  },
  {
    name: 'ChannelGroup',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/metrics-dashboard/channel-widgets/ChannelGroup.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['group', 'channels'],
    description: 'Grouped channel display with collapsible rows.',
  },
  {
    name: 'ChannelGroupCard',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/metrics-dashboard/channel-widgets/ChannelGroupCard.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['group'],
    description: 'Card wrapper for a channel group.',
    issues: ['Potential overlap with ChannelGroup'],
  },
  {
    name: 'ChannelRow',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/metrics-dashboard/channel-widgets/ChannelRow.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['channel', 'metrics'],
    description: 'Single channel row with metrics, icon, bottleneck badges.',
  },
  {
    name: 'CampaignDrillDown',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/metrics-dashboard/channel-widgets/CampaignDrillDown.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['campaigns'],
    description: 'Expandable campaign-level metrics within a channel.',
  },
  {
    name: 'CandidatosBanner',
    atomicLevel: 'atom',
    filePath: 'features/marketing-studio/components/metrics-dashboard/channel-widgets/CandidatosBanner.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: [],
    description: 'Proximamente banner for upcoming features.',
  },
  {
    name: 'ConnectionBadge',
    atomicLevel: 'atom',
    filePath: 'features/marketing-studio/components/metrics-dashboard/channel-widgets/ConnectionBadge.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['connected', 'label'],
    description: 'Badge showing connection status of a channel.',
  },
  {
    name: 'CostLink',
    atomicLevel: 'atom',
    filePath: 'features/marketing-studio/components/metrics-dashboard/channel-widgets/CostLink.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['href'],
    description: 'Link to cost configuration page.',
  },
  {
    name: 'EvangelistCard',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/metrics-dashboard/evangelist-widgets/EvangelistCard.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['evangelist'],
    description: 'Card for top evangelist/referrer stats.',
  },
  {
    name: 'ExpansionGroup',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/metrics-dashboard/offer-widgets/ExpansionGroup.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['offers'],
    description: 'Group display for expansion/upsell offers.',
  },
  {
    name: 'ExpansionOfferRow',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/metrics-dashboard/offer-widgets/ExpansionOfferRow.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['offer'],
    description: 'Row for a single expansion offer metrics.',
  },
  {
    name: 'HealthBar',
    atomicLevel: 'atom',
    filePath: 'features/marketing-studio/components/metrics-dashboard/offer-widgets/HealthBar.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['segments'],
    description: 'Proportional health bar with CSS widths (no chart library).',
  },
  {
    name: 'KpiTooltip',
    atomicLevel: 'atom',
    filePath: 'features/marketing-studio/components/metrics-dashboard/channel-widgets/KpiTooltip.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['label', 'hint'],
    description: 'Reusable KPI label with plain-Spanish tooltip hint.',
    issues: ['Could be promoted to shared/ — useful across features'],
  },
  {
    name: 'MiniFunnel',
    atomicLevel: 'atom',
    filePath: 'features/marketing-studio/components/metrics-dashboard/channel-widgets/MiniFunnel.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['stages'],
    description: 'Miniature funnel visualization.',
  },
  {
    name: 'NpsSummaryCard',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/metrics-dashboard/evangelist-widgets/NpsSummaryCard.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['npsData'],
    description: 'NPS score summary with promoter/passive/detractor bar.',
  },
  {
    name: 'OfferCard',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/metrics-dashboard/offer-widgets/OfferCard.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['offer'],
    description: 'Card for offer metrics in sales/adoption detail.',
  },
  {
    name: 'OfferHealthCard',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/metrics-dashboard/offer-widgets/OfferHealthCard.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['offer', 'health'],
    description: 'Offer card with health indicators.',
    issues: ['Overlaps with OfferCard — could be merged'],
  },
  {
    name: 'OfferLadder',
    atomicLevel: 'organism',
    filePath: 'features/marketing-studio/components/metrics-dashboard/offer-widgets/OfferLadder.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['adquisicion', 'expansion', 'onMetricClick'],
    description: 'Visual offer ladder showing revenue groups by acquisition/expansion tiers.',
  },
  {
    name: 'RevenueGroupHeader',
    atomicLevel: 'atom',
    filePath: 'features/marketing-studio/components/metrics-dashboard/channel-widgets/RevenueGroupHeader.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['title', 'total'],
    description: 'Header for revenue group sections.',
  },
  {
    name: 'TierGroup',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/metrics-dashboard/channel-widgets/TierGroup.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['tier', 'offers'],
    description: 'Group of offers by value tier.',
  },

  // --- Detail Panels (organisms — complex composed views) ---
  {
    name: 'AttractionDetail',
    atomicLevel: 'organism',
    filePath: 'features/marketing-studio/components/metrics-dashboard/detail-panels/AttractionDetail.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: [],
    description: 'Attraction stage detail panel with channel groups.',
  },
  {
    name: 'CaptureDetail',
    atomicLevel: 'organism',
    filePath: 'features/marketing-studio/components/metrics-dashboard/detail-panels/CaptureDetail.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: [],
    description: 'Capture stage detail panel with lead sources.',
  },
  {
    name: 'NurtureDetail',
    atomicLevel: 'organism',
    filePath: 'features/marketing-studio/components/metrics-dashboard/detail-panels/NurtureDetail.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: [],
    description: 'Nurture stage detail panel with email/retargeting channels.',
  },
  {
    name: 'OpportunityDetail',
    atomicLevel: 'organism',
    filePath: 'features/marketing-studio/components/metrics-dashboard/detail-panels/OpportunityDetail.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: [],
    description: 'Opportunity stage detail panel with pipeline metrics.',
  },
  {
    name: 'SalesDetail',
    atomicLevel: 'organism',
    filePath: 'features/marketing-studio/components/metrics-dashboard/detail-panels/SalesDetail.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: [],
    description: 'Sales/Ventas stage detail panel with offer tiers.',
  },
  {
    name: 'AdoptionDetail',
    atomicLevel: 'organism',
    filePath: 'features/marketing-studio/components/metrics-dashboard/detail-panels/AdoptionDetail.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: [],
    description: 'Adoption stage detail panel with onboarding health.',
  },
  {
    name: 'ExpansionDetail',
    atomicLevel: 'organism',
    filePath: 'features/marketing-studio/components/metrics-dashboard/detail-panels/ExpansionDetail.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: [],
    description: 'Expansion stage detail panel with upsell/cross-sell.',
  },
  {
    name: 'EvangelizationDetail',
    atomicLevel: 'organism',
    filePath: 'features/marketing-studio/components/metrics-dashboard/detail-panels/EvangelizationDetail.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: [],
    description: 'Evangelization stage detail panel with NPS + referrals.',
  },
  {
    name: 'PlaceholderDetail',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/metrics-dashboard/detail-panels/PlaceholderDetail.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['stageId'],
    description: 'Placeholder for future stage detail panels.',
  },
  {
    name: 'BottleneckBanner',
    atomicLevel: 'atom',
    filePath: 'features/marketing-studio/components/metrics-dashboard/detail-panels/BottleneckBanner.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['bottleneck'],
    description: 'Warning banner for stage bottleneck metrics.',
    issues: ['Could be promoted to shared/ — reusable pattern'],
  },
  {
    name: 'DetailSkeleton',
    atomicLevel: 'atom',
    filePath: 'features/marketing-studio/components/metrics-dashboard/ui/DetailSkeleton.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: [],
    description: 'Loading skeleton for detail panels.',
  },
  {
    name: 'DetailEmpty',
    atomicLevel: 'atom',
    filePath: 'features/marketing-studio/components/metrics-dashboard/ui/DetailEmpty.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: [],
    description: 'Empty state for detail panels.',
  },
  {
    name: 'DetailError',
    atomicLevel: 'atom',
    filePath: 'features/marketing-studio/components/metrics-dashboard/ui/DetailError.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: [],
    description: 'Error state for detail panels.',
  },
  {
    name: 'ActionPanel',
    atomicLevel: 'organism',
    filePath: 'features/marketing-studio/components/metrics-dashboard/action-widgets/ActionPanel.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: [],
    description: 'Action trigger panel for stage-specific automations.',
  },

  // --- Strategy Canvas ---
  {
    name: 'StrategyCanvas',
    atomicLevel: 'organism',
    filePath: 'features/marketing-studio/components/strategy-canvas/StrategyCanvas.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: [],
    description: 'Visual strategy/funnel canvas with nodes and links.',
  },
  {
    name: 'ActionDetailsDrawer',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/strategy-canvas/drawer/ActionDetailsDrawer.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['action'],
    description: 'Slide-out drawer for strategy action details.',
  },
  {
    name: 'BaseLink',
    atomicLevel: 'atom',
    filePath: 'features/marketing-studio/components/strategy-canvas/links/BaseLink.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['from', 'to'],
    description: 'SVG link connector between canvas nodes.',
  },
  {
    name: 'NodeFactory',
    atomicLevel: 'molecule',
    filePath: 'features/marketing-studio/components/strategy-canvas/nodes/NodeFactory.tsx',
    source: 'feature',
    featureSlice: 'marketing-studio',
    variants: [],
    props: ['nodeType', 'data'],
    description: 'Factory component rendering the correct node type on canvas.',
  },

  // ==========================================================================
  // FEATURE: brand (features/brand/components/)
  // ==========================================================================
  {
    name: 'BrandNavRail',
    atomicLevel: 'molecule',
    filePath: 'features/brand/components/navigation/brand-nav-rail.tsx',
    source: 'feature',
    featureSlice: 'brand',
    variants: [],
    props: [],
    description: 'Vertical navigation rail for Brand Studio sections.',
  },
  {
    name: 'BrandEmptyState',
    atomicLevel: 'atom',
    filePath: 'features/brand/components/empty-state/brand-empty-state.tsx',
    source: 'feature',
    featureSlice: 'brand',
    variants: [],
    props: [],
    description: 'Empty state for Brand Studio when no brand exists.',
  },
  {
    name: 'BrandStudioLayout',
    atomicLevel: 'organism',
    filePath: 'features/brand/components/container/brand-studio-layout.tsx',
    source: 'feature',
    featureSlice: 'brand',
    variants: [],
    props: [],
    description: 'Layout container for Brand Studio with nav + content.',
  },
  {
    name: 'EditSheetManager',
    atomicLevel: 'organism',
    filePath: 'features/brand/components/forms/edit-sheet-manager.tsx',
    source: 'feature',
    featureSlice: 'brand',
    variants: [],
    props: [],
    description: 'Sheet manager for editing brand sections.',
  },
  {
    name: 'SmartFillDialog',
    atomicLevel: 'molecule',
    filePath: 'features/brand/components/smart-fill/smart-fill-dialog.tsx',
    source: 'feature',
    featureSlice: 'brand',
    variants: [],
    props: ['open', 'onClose'],
    description: 'AI-powered auto-fill dialog for brand data.',
  },
  {
    name: 'LegalManager',
    atomicLevel: 'organism',
    filePath: 'features/brand/components/legal/legal-manager.tsx',
    source: 'feature',
    featureSlice: 'brand',
    variants: [],
    props: [],
    description: 'Manager for legal documents (terms, privacy).',
  },
  {
    name: 'LegalForm',
    atomicLevel: 'molecule',
    filePath: 'features/brand/components/legal/legal-form.tsx',
    source: 'feature',
    featureSlice: 'brand',
    variants: [],
    props: ['type', 'onSubmit'],
    description: 'Form for editing legal documents.',
  },

  // ==========================================================================
  // FEATURE: connections (features/connections/components/)
  // ==========================================================================
  {
    name: 'WhatsAppView',
    atomicLevel: 'organism',
    filePath: 'features/connections/components/whatsapp-view.tsx',
    source: 'feature',
    featureSlice: 'connections',
    variants: [],
    props: [],
    description: 'WhatsApp connection config view.',
  },
  {
    name: 'ManyChatView',
    atomicLevel: 'organism',
    filePath: 'features/connections/components/manychat-view.tsx',
    source: 'feature',
    featureSlice: 'connections',
    variants: [],
    props: [],
    description: 'ManyChat connection config view.',
  },
  {
    name: 'GoogleAnalyticsView',
    atomicLevel: 'organism',
    filePath: 'features/connections/components/google-analytics-view.tsx',
    source: 'feature',
    featureSlice: 'connections',
    variants: [],
    props: [],
    description: 'Google Analytics connection config view.',
  },
  {
    name: 'GoogleWorkspaceView',
    atomicLevel: 'organism',
    filePath: 'features/connections/components/google-workspace-view.tsx',
    source: 'feature',
    featureSlice: 'connections',
    variants: [],
    props: [],
    description: 'Google Workspace connection config view.',
  },
  {
    name: 'ShopifyView',
    atomicLevel: 'organism',
    filePath: 'features/connections/components/shopify-view.tsx',
    source: 'feature',
    featureSlice: 'connections',
    variants: [],
    props: [],
    description: 'Shopify connection config view.',
  },
  {
    name: 'YouTubeView',
    atomicLevel: 'organism',
    filePath: 'features/connections/components/youtube-view.tsx',
    source: 'feature',
    featureSlice: 'connections',
    variants: [],
    props: [],
    description: 'YouTube connection config view.',
  },
  {
    name: 'MetaView',
    atomicLevel: 'organism',
    filePath: 'features/connections/components/meta-view.tsx',
    source: 'feature',
    featureSlice: 'connections',
    variants: [],
    props: [],
    description: 'Meta (Facebook/Instagram) connection config view.',
  },
  {
    name: 'GmailView',
    atomicLevel: 'organism',
    filePath: 'features/connections/components/gmail-view.tsx',
    source: 'feature',
    featureSlice: 'connections',
    variants: [],
    props: [],
    description: 'Gmail connection config view.',
  },
  {
    name: 'GoogleCalendarView',
    atomicLevel: 'organism',
    filePath: 'features/connections/components/google-calendar-view.tsx',
    source: 'feature',
    featureSlice: 'connections',
    variants: [],
    props: [],
    description: 'Google Calendar connection config view.',
  },
  {
    name: 'MailerliteView',
    atomicLevel: 'organism',
    filePath: 'features/connections/components/mailerlite-view.tsx',
    source: 'feature',
    featureSlice: 'connections',
    variants: [],
    props: [],
    description: 'Mailerlite connection config view.',
  },
  {
    name: 'TelegramView',
    atomicLevel: 'organism',
    filePath: 'features/connections/components/telegram-view.tsx',
    source: 'feature',
    featureSlice: 'connections',
    variants: [],
    props: [],
    description: 'Telegram connection config view.',
  },

  // ==========================================================================
  // FEATURE: offer-studio (features/offer-studio/components/) — selected
  // ==========================================================================
  {
    name: 'OfferNavRail',
    atomicLevel: 'molecule',
    filePath: 'features/offer-studio/components/navigation/OfferNavRail.tsx',
    source: 'feature',
    featureSlice: 'offer-studio',
    variants: [],
    props: [],
    description: 'Navigation rail for Offer Studio sections.',
  },
  {
    name: 'OfferStudioLayout',
    atomicLevel: 'organism',
    filePath: 'features/offer-studio/components/container/offer-studio-layout.tsx',
    source: 'feature',
    featureSlice: 'offer-studio',
    variants: [],
    props: [],
    description: 'Layout container for Offer Studio.',
  },
  {
    name: 'OfferEditor',
    atomicLevel: 'organism',
    filePath: 'features/offer-studio/components/editor/offer-editor.tsx',
    source: 'feature',
    featureSlice: 'offer-studio',
    variants: [],
    props: ['offerId'],
    description: 'Main offer editing interface with sections.',
  },
  {
    name: 'OfferEditSheetManager',
    atomicLevel: 'organism',
    filePath: 'features/offer-studio/components/editor/offer-edit-sheet-manager.tsx',
    source: 'feature',
    featureSlice: 'offer-studio',
    variants: [],
    props: [],
    description: 'Sheet manager for offer editing overlays.',
    issues: ['Similar pattern to brand EditSheetManager — potential shared abstraction'],
  },
  {
    name: 'OfferLivePreview',
    atomicLevel: 'organism',
    filePath: 'features/offer-studio/components/editor/offer-live-preview.tsx',
    source: 'feature',
    featureSlice: 'offer-studio',
    variants: [],
    props: ['offer'],
    description: 'Live preview of offer as landing page.',
  },
  {
    name: 'AiAssistButton',
    atomicLevel: 'atom',
    filePath: 'features/offer-studio/components/editor/components/ai-assist-button.tsx',
    source: 'feature',
    featureSlice: 'offer-studio',
    variants: [],
    props: ['onClick', 'loading'],
    description: 'AI auto-fill trigger button.',
    issues: ['Could be promoted to shared/ — useful across studios'],
  },
  {
    name: 'RichEnumSelect',
    atomicLevel: 'molecule',
    filePath: 'features/offer-studio/components/editor/ui/rich-enum-select.tsx',
    source: 'feature',
    featureSlice: 'offer-studio',
    variants: [],
    props: ['options', 'value', 'onChange'],
    description: 'Rich select for enum values with descriptions.',
    issues: ['Similar to RichSelect in ui/ — potential duplication'],
  },
  {
    name: 'ContextualHint',
    atomicLevel: 'atom',
    filePath: 'features/offer-studio/components/editor/ui/contextual-hint.tsx',
    source: 'feature',
    featureSlice: 'offer-studio',
    variants: [],
    props: ['text'],
    description: 'Contextual hint text for form fields.',
    issues: ['Similar to FieldInfo in ui/ — potential duplication'],
  },
  {
    name: 'OfferContextPanel',
    atomicLevel: 'molecule',
    filePath: 'features/offer-studio/components/editor/ui/offer-context-panel.tsx',
    source: 'feature',
    featureSlice: 'offer-studio',
    variants: [],
    props: [],
    description: 'Side panel showing offer context during editing.',
  },

  // ==========================================================================
  // FEATURE: audit (features/audit/components/)
  // ==========================================================================
  {
    name: 'AuditDashboard',
    atomicLevel: 'organism',
    filePath: 'features/audit/components/AuditDashboard.tsx',
    source: 'feature',
    featureSlice: 'audit',
    variants: [],
    props: [],
    description: 'Main audit/conversation trace dashboard.',
  },
  {
    name: 'TraceInspector',
    atomicLevel: 'organism',
    filePath: 'features/audit/components/trace-inspector.tsx',
    source: 'feature',
    featureSlice: 'audit',
    variants: [],
    props: ['traceId'],
    description: 'LangGraph trace visualization and inspection.',
  },
  {
    name: 'ContextPanel',
    atomicLevel: 'molecule',
    filePath: 'features/audit/components/context-panel.tsx',
    source: 'feature',
    featureSlice: 'audit',
    variants: [],
    props: ['context'],
    description: 'Context data panel for trace inspection.',
  },
  {
    name: 'NodeDetailsPanel',
    atomicLevel: 'molecule',
    filePath: 'features/audit/components/node-details-panel.tsx',
    source: 'feature',
    featureSlice: 'audit',
    variants: [],
    props: ['node'],
    description: 'Details panel for a single graph node in trace.',
  },
  {
    name: 'UserList',
    atomicLevel: 'molecule',
    filePath: 'features/audit/components/user-list.tsx',
    source: 'feature',
    featureSlice: 'audit',
    variants: [],
    props: ['users'],
    description: 'User list for filtering audit conversations.',
  },
  {
    name: 'ChatTimeline',
    atomicLevel: 'molecule',
    filePath: 'features/audit/components/chat-timeline.tsx',
    source: 'feature',
    featureSlice: 'audit',
    variants: [],
    props: ['messages'],
    description: 'Chat message timeline visualization.',
  },
  {
    name: 'NodeIcons',
    atomicLevel: 'atom',
    filePath: 'features/audit/components/node-icons.tsx',
    source: 'feature',
    featureSlice: 'audit',
    variants: [],
    props: ['nodeType'],
    description: 'Icon set for graph node types.',
  },

  // ==========================================================================
  // FEATURE: admin (features/admin/components/)
  // ==========================================================================
  {
    name: 'TenantsList',
    atomicLevel: 'organism',
    filePath: 'features/admin/components/tenants-list.tsx',
    source: 'feature',
    featureSlice: 'admin',
    variants: [],
    props: [],
    description: 'Admin tenant management list.',
  },

  // ==========================================================================
  // FEATURE: settings (features/settings/components/)
  // ==========================================================================
  {
    name: 'SettingsView',
    atomicLevel: 'organism',
    filePath: 'features/settings/components/SettingsView.tsx',
    source: 'feature',
    featureSlice: 'settings',
    variants: [],
    props: [],
    description: 'Main settings page layout with tabs.',
  },
  {
    name: 'TeamView',
    atomicLevel: 'organism',
    filePath: 'features/settings/components/team-view.tsx',
    source: 'feature',
    featureSlice: 'settings',
    variants: [],
    props: [],
    description: 'Team member management view.',
  },
  {
    name: 'WebhookView',
    atomicLevel: 'organism',
    filePath: 'features/settings/components/webhook-view.tsx',
    source: 'feature',
    featureSlice: 'settings',
    variants: [],
    props: [],
    description: 'Webhook configuration view.',
  },
  {
    name: 'AiKeysForm',
    atomicLevel: 'molecule',
    filePath: 'features/settings/components/ai-keys-form.tsx',
    source: 'feature',
    featureSlice: 'settings',
    variants: [],
    props: [],
    description: 'Form for configuring AI API keys.',
  },
  {
    name: 'GeneralSettingsForm',
    atomicLevel: 'molecule',
    filePath: 'features/settings/components/general-settings-form.tsx',
    source: 'feature',
    featureSlice: 'settings',
    variants: [],
    props: [],
    description: 'General tenant settings form.',
  },
  {
    name: 'ProfileView',
    atomicLevel: 'organism',
    filePath: 'features/settings/components/profile-view.tsx',
    source: 'feature',
    featureSlice: 'settings',
    variants: [],
    props: [],
    description: 'User profile settings view.',
  },
];

// ---------------------------------------------------------------------------
// DESIGN TOKENS
// ---------------------------------------------------------------------------

export const DESIGN_TOKENS: DesignToken[] = [
  // --- Colors (from globals.css CSS variables) ---
  { category: 'color', name: 'Background', cssVar: '--background', tailwindClass: 'bg-background', value: 'hsl(0 0% 100%)' },
  { category: 'color', name: 'Foreground', cssVar: '--foreground', tailwindClass: 'text-foreground', value: 'hsl(222.2 84% 4.9%)' },
  { category: 'color', name: 'Primary', cssVar: '--primary', tailwindClass: 'bg-primary', value: 'hsl(222.2 47.4% 11.2%)' },
  { category: 'color', name: 'Primary Foreground', cssVar: '--primary-foreground', tailwindClass: 'text-primary-foreground', value: 'hsl(210 40% 98%)' },
  { category: 'color', name: 'Secondary', cssVar: '--secondary', tailwindClass: 'bg-secondary', value: 'hsl(210 40% 96.1%)' },
  { category: 'color', name: 'Secondary Foreground', cssVar: '--secondary-foreground', tailwindClass: 'text-secondary-foreground', value: 'hsl(222.2 47.4% 11.2%)' },
  { category: 'color', name: 'Muted', cssVar: '--muted', tailwindClass: 'bg-muted', value: 'hsl(210 40% 96.1%)' },
  { category: 'color', name: 'Muted Foreground', cssVar: '--muted-foreground', tailwindClass: 'text-muted-foreground', value: 'hsl(215.4 16.3% 46.9%)' },
  { category: 'color', name: 'Accent', cssVar: '--accent', tailwindClass: 'bg-accent', value: 'hsl(210 40% 96.1%)' },
  { category: 'color', name: 'Accent Foreground', cssVar: '--accent-foreground', tailwindClass: 'text-accent-foreground', value: 'hsl(222.2 47.4% 11.2%)' },
  { category: 'color', name: 'Destructive', cssVar: '--destructive', tailwindClass: 'bg-destructive', value: 'hsl(0 84.2% 60.2%)' },
  { category: 'color', name: 'Destructive Foreground', cssVar: '--destructive-foreground', tailwindClass: 'text-destructive-foreground', value: 'hsl(210 40% 98%)' },
  { category: 'color', name: 'Card', cssVar: '--card', tailwindClass: 'bg-card', value: 'hsl(0 0% 100%)' },
  { category: 'color', name: 'Card Foreground', cssVar: '--card-foreground', tailwindClass: 'text-card-foreground', value: 'hsl(222.2 84% 4.9%)' },
  { category: 'color', name: 'Popover', cssVar: '--popover', tailwindClass: 'bg-popover', value: 'hsl(0 0% 100%)' },
  { category: 'color', name: 'Popover Foreground', cssVar: '--popover-foreground', tailwindClass: 'text-popover-foreground', value: 'hsl(222.2 84% 4.9%)' },
  { category: 'color', name: 'Border', cssVar: '--border', tailwindClass: 'border-border', value: 'hsl(214.3 31.8% 91.4%)' },
  { category: 'color', name: 'Input', cssVar: '--input', tailwindClass: 'border-input', value: 'hsl(214.3 31.8% 91.4%)' },
  { category: 'color', name: 'Ring', cssVar: '--ring', tailwindClass: 'ring-ring', value: 'hsl(222.2 84% 4.9%)' },

  // --- Typography ---
  { category: 'typography', name: 'Text XS', tailwindClass: 'text-xs', value: '0.75rem / 1rem' },
  { category: 'typography', name: 'Text SM', tailwindClass: 'text-sm', value: '0.875rem / 1.25rem' },
  { category: 'typography', name: 'Text Base', tailwindClass: 'text-base', value: '1rem / 1.5rem' },
  { category: 'typography', name: 'Text LG', tailwindClass: 'text-lg', value: '1.125rem / 1.75rem' },
  { category: 'typography', name: 'Text XL', tailwindClass: 'text-xl', value: '1.25rem / 1.75rem' },
  { category: 'typography', name: 'Text 2XL', tailwindClass: 'text-2xl', value: '1.5rem / 2rem' },
  { category: 'typography', name: 'Text 3XL', tailwindClass: 'text-3xl', value: '1.875rem / 2.25rem' },
  { category: 'typography', name: 'Font Normal', tailwindClass: 'font-normal', value: '400' },
  { category: 'typography', name: 'Font Medium', tailwindClass: 'font-medium', value: '500' },
  { category: 'typography', name: 'Font Semibold', tailwindClass: 'font-semibold', value: '600' },
  { category: 'typography', name: 'Font Bold', tailwindClass: 'font-bold', value: '700' },

  // --- Spacing ---
  { category: 'spacing', name: 'Space 1', tailwindClass: 'p-1', value: '0.25rem (4px)' },
  { category: 'spacing', name: 'Space 2', tailwindClass: 'p-2', value: '0.5rem (8px)' },
  { category: 'spacing', name: 'Space 3', tailwindClass: 'p-3', value: '0.75rem (12px)' },
  { category: 'spacing', name: 'Space 4', tailwindClass: 'p-4', value: '1rem (16px)' },
  { category: 'spacing', name: 'Space 6', tailwindClass: 'p-6', value: '1.5rem (24px)' },
  { category: 'spacing', name: 'Space 8', tailwindClass: 'p-8', value: '2rem (32px)' },
  { category: 'spacing', name: 'Space 12', tailwindClass: 'p-12', value: '3rem (48px)' },
  { category: 'spacing', name: 'Space 16', tailwindClass: 'p-16', value: '4rem (64px)' },

  // --- Border Radius ---
  { category: 'radius', name: 'Radius SM', cssVar: '--radius-sm', tailwindClass: 'rounded-sm', value: 'calc(var(--radius) - 4px)' },
  { category: 'radius', name: 'Radius MD', cssVar: '--radius-md', tailwindClass: 'rounded-md', value: 'calc(var(--radius) - 2px)' },
  { category: 'radius', name: 'Radius LG', cssVar: '--radius-lg', tailwindClass: 'rounded-lg', value: 'var(--radius) = 0.5rem' },
  { category: 'radius', name: 'Radius Full', tailwindClass: 'rounded-full', value: '9999px' },

  // --- Shadows ---
  { category: 'shadow', name: 'Shadow SM', tailwindClass: 'shadow-sm', value: '0 1px 2px 0 rgb(0 0 0 / 0.05)' },
  { category: 'shadow', name: 'Shadow', tailwindClass: 'shadow', value: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)' },
  { category: 'shadow', name: 'Shadow MD', tailwindClass: 'shadow-md', value: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)' },
  { category: 'shadow', name: 'Shadow LG', tailwindClass: 'shadow-lg', value: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)' },
];

// ---------------------------------------------------------------------------
// HELPER FUNCTIONS
// ---------------------------------------------------------------------------

/** Get all components at a specific atomic level */
export function getByLevel(level: ComponentEntry['atomicLevel']): ComponentEntry[] {
  return COMPONENT_REGISTRY.filter(c => c.atomicLevel === level);
}

/** Get all components from a specific source */
export function getBySource(source: ComponentEntry['source']): ComponentEntry[] {
  return COMPONENT_REGISTRY.filter(c => c.source === source);
}

/** Get all components with issues */
export function getWithIssues(): ComponentEntry[] {
  return COMPONENT_REGISTRY.filter(c => c.issues && c.issues.length > 0);
}

/** Get components for a specific feature slice */
export function getByFeature(featureSlice: string): ComponentEntry[] {
  return COMPONENT_REGISTRY.filter(c => c.featureSlice === featureSlice);
}

/** Get tokens by category */
export function getTokensByCategory(category: DesignToken['category']): DesignToken[] {
  return DESIGN_TOKENS.filter(t => t.category === category);
}

/** Registry stats */
export function getStats() {
  const atoms = getByLevel('atom').length;
  const molecules = getByLevel('molecule').length;
  const organisms = getByLevel('organism').length;
  const withIssues = getWithIssues().length;
  return {
    total: COMPONENT_REGISTRY.length,
    atoms,
    molecules,
    organisms,
    withIssues,
    bySource: {
      shadcn: getBySource('shadcn').length,
      shared: getBySource('shared').length,
      feature: getBySource('feature').length,
    },
  };
}
