import type { ComponentEntry } from "./types";

// FEATURE: growth-studio (features/growth-studio/components/)
export const REGISTRY_GROWTH: ComponentEntry[] = [
  // ==========================================================================
  // FEATURE: growth-studio (features/growth-studio/components/)
  // ==========================================================================

  // --- Organisms (dashboard containers) ---
  {
    name: "MetricSidebar",
    atomicLevel: "organism",
    filePath: "features/growth-studio/components/metrics-dashboard/sidebar/MetricSidebar.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["children"],
    description: "Sidebar container for metric details.",
  },
  {
    name: "SidebarContent",
    atomicLevel: "organism",
    filePath: "features/growth-studio/components/metrics-dashboard/sidebar/SidebarContent.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["stageId"],
    description: "Polymorphic sidebar content renderer per bowtie stage.",
  },

  // --- Molecules (stage/channel widgets) ---
  {
    name: "StageCard",
    atomicLevel: "molecule",
    filePath: "features/growth-studio/components/metrics-dashboard/stage-widgets/StageCard.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["stage", "onClick", "active"],
    description: "Bowtie funnel stage card with KPIs.",
  },
  {
    name: "StageSummaryRow",
    atomicLevel: "molecule",
    filePath:
      "features/growth-studio/components/metrics-dashboard/stage-widgets/StageSummaryRow.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["label", "value", "trend"],
    description: "Summary row inside a stage card.",
  },
  {
    name: "ChannelGroup",
    atomicLevel: "molecule",
    filePath:
      "features/growth-studio/components/metrics-dashboard/channel-widgets/ChannelGroup.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["group", "channels"],
    description: "Grouped channel display with collapsible rows.",
  },
  {
    name: "ChannelGroupCard",
    atomicLevel: "molecule",
    filePath:
      "features/growth-studio/components/metrics-dashboard/channel-widgets/ChannelGroupCard.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["group"],
    description: "Card wrapper for a channel group.",
    issues: ["Potential overlap with ChannelGroup"],
  },
  {
    name: "ChannelRow",
    atomicLevel: "molecule",
    filePath: "features/growth-studio/components/metrics-dashboard/channel-widgets/ChannelRow.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["channel", "metrics"],
    description: "Single channel row with metrics, icon, bottleneck badges.",
  },
  {
    name: "CampaignDrillDown",
    atomicLevel: "molecule",
    filePath:
      "features/growth-studio/components/metrics-dashboard/channel-widgets/CampaignDrillDown.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["campaigns"],
    description: "Expandable campaign-level metrics within a channel.",
  },
  {
    name: "CandidatosBanner",
    atomicLevel: "atom",
    filePath:
      "features/growth-studio/components/metrics-dashboard/channel-widgets/CandidatosBanner.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: [],
    description: "Proximamente banner for upcoming features.",
  },
  {
    name: "ConnectionBadge",
    atomicLevel: "atom",
    filePath:
      "features/growth-studio/components/metrics-dashboard/channel-widgets/ConnectionBadge.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["connected", "label"],
    description: "Badge showing connection status of a channel.",
  },
  {
    name: "CostLink",
    atomicLevel: "atom",
    filePath: "features/growth-studio/components/metrics-dashboard/channel-widgets/CostLink.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["href"],
    description: "Link to cost configuration page.",
  },
  {
    name: "EvangelistCard",
    atomicLevel: "molecule",
    filePath:
      "features/growth-studio/components/metrics-dashboard/evangelist-widgets/EvangelistCard.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["evangelist"],
    description: "Card for top evangelist/referrer stats.",
  },
  {
    name: "ExpansionGroup",
    atomicLevel: "molecule",
    filePath:
      "features/growth-studio/components/metrics-dashboard/offer-widgets/ExpansionGroup.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["offers"],
    description: "Group display for expansion/upsell offers.",
  },
  {
    name: "ExpansionOfferRow",
    atomicLevel: "molecule",
    filePath:
      "features/growth-studio/components/metrics-dashboard/offer-widgets/ExpansionOfferRow.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["offer"],
    description: "Row for a single expansion offer metrics.",
  },
  {
    name: "HealthBar",
    atomicLevel: "atom",
    filePath: "features/growth-studio/components/metrics-dashboard/offer-widgets/HealthBar.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["segments"],
    description: "Proportional health bar with CSS widths (no chart library).",
  },
  {
    name: "KpiTooltip",
    atomicLevel: "atom",
    filePath: "features/growth-studio/components/metrics-dashboard/channel-widgets/KpiTooltip.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["label", "hint"],
    description: "Reusable KPI label with plain-Spanish tooltip hint.",
    issues: ["Could be promoted to shared/ — useful across features"],
  },
  {
    name: "MiniFunnel",
    atomicLevel: "atom",
    filePath: "features/growth-studio/components/metrics-dashboard/channel-widgets/MiniFunnel.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["stages"],
    description: "Miniature funnel visualization.",
  },
  {
    name: "NpsSummaryCard",
    atomicLevel: "molecule",
    filePath:
      "features/growth-studio/components/metrics-dashboard/evangelist-widgets/NpsSummaryCard.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["npsData"],
    description: "NPS score summary with promoter/passive/detractor bar.",
  },
  {
    name: "OfferCard",
    atomicLevel: "molecule",
    filePath: "features/growth-studio/components/metrics-dashboard/offer-widgets/OfferCard.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["offer"],
    description: "Card for offer metrics in sales/adoption detail.",
  },
  {
    name: "OfferHealthCard",
    atomicLevel: "molecule",
    filePath:
      "features/growth-studio/components/metrics-dashboard/offer-widgets/OfferHealthCard.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["offer", "health"],
    description: "Offer card with health indicators.",
    issues: ["Overlaps with OfferCard — could be merged"],
  },
  {
    name: "OfferLadder",
    atomicLevel: "organism",
    filePath: "features/growth-studio/components/metrics-dashboard/offer-widgets/OfferLadder.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["adquisicion", "expansion", "onMetricClick"],
    description: "Visual offer ladder showing revenue groups by acquisition/expansion tiers.",
  },
  {
    name: "RevenueGroupHeader",
    atomicLevel: "atom",
    filePath:
      "features/growth-studio/components/metrics-dashboard/channel-widgets/RevenueGroupHeader.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["title", "total"],
    description: "Header for revenue group sections.",
  },
  {
    name: "TierGroup",
    atomicLevel: "molecule",
    filePath: "features/growth-studio/components/metrics-dashboard/channel-widgets/TierGroup.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["tier", "offers"],
    description: "Group of offers by value tier.",
  },

  // --- Detail Panels (organisms — complex composed views) ---
  {
    name: "AttractionDetail",
    atomicLevel: "organism",
    filePath:
      "features/growth-studio/components/metrics-dashboard/detail-panels/AttractionDetail.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: [],
    description: "Attraction stage detail panel with channel groups.",
  },
  {
    name: "CaptureDetail",
    atomicLevel: "organism",
    filePath: "features/growth-studio/components/metrics-dashboard/detail-panels/CaptureDetail.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: [],
    description: "Capture stage detail panel with lead sources.",
  },
  {
    name: "NurtureDetail",
    atomicLevel: "organism",
    filePath: "features/growth-studio/components/metrics-dashboard/detail-panels/NurtureDetail.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: [],
    description: "Nurture stage detail panel with email/retargeting channels.",
  },
  {
    name: "OpportunityDetail",
    atomicLevel: "organism",
    filePath:
      "features/growth-studio/components/metrics-dashboard/detail-panels/OpportunityDetail.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: [],
    description: "Opportunity stage detail panel with pipeline metrics.",
  },
  {
    name: "SalesDetail",
    atomicLevel: "organism",
    filePath: "features/growth-studio/components/metrics-dashboard/detail-panels/SalesDetail.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: [],
    description: "Sales/Ventas stage detail panel with offer tiers.",
  },
  {
    name: "AdoptionDetail",
    atomicLevel: "organism",
    filePath:
      "features/growth-studio/components/metrics-dashboard/detail-panels/AdoptionDetail.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: [],
    description: "Adoption stage detail panel with onboarding health.",
  },
  {
    name: "ExpansionDetail",
    atomicLevel: "organism",
    filePath:
      "features/growth-studio/components/metrics-dashboard/detail-panels/ExpansionDetail.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: [],
    description: "Expansion stage detail panel with upsell/cross-sell.",
  },
  {
    name: "EvangelizationDetail",
    atomicLevel: "organism",
    filePath:
      "features/growth-studio/components/metrics-dashboard/detail-panels/EvangelizationDetail.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: [],
    description: "Evangelization stage detail panel with NPS + referrals.",
  },
  {
    name: "PlaceholderDetail",
    atomicLevel: "molecule",
    filePath:
      "features/growth-studio/components/metrics-dashboard/detail-panels/PlaceholderDetail.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["stageId"],
    description: "Placeholder for future stage detail panels.",
  },
  {
    name: "BottleneckBanner",
    atomicLevel: "atom",
    filePath:
      "features/growth-studio/components/metrics-dashboard/detail-panels/BottleneckBanner.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["bottleneck"],
    description: "Warning banner for stage bottleneck metrics.",
    issues: ["Could be promoted to shared/ — reusable pattern"],
  },
  {
    name: "DetailSkeleton",
    atomicLevel: "atom",
    filePath: "features/growth-studio/components/metrics-dashboard/ui/DetailSkeleton.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: [],
    description: "Loading skeleton for detail panels.",
  },
  {
    name: "DetailEmpty",
    atomicLevel: "atom",
    filePath: "features/growth-studio/components/metrics-dashboard/ui/DetailEmpty.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: [],
    description: "Empty state for detail panels.",
  },
  {
    name: "DetailError",
    atomicLevel: "atom",
    filePath: "features/growth-studio/components/metrics-dashboard/ui/DetailError.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: [],
    description: "Error state for detail panels.",
  },
  {
    name: "ActionPanel",
    atomicLevel: "organism",
    filePath: "features/growth-studio/components/metrics-dashboard/action-widgets/ActionPanel.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: [],
    description: "Action trigger panel for stage-specific automations.",
  },

  // --- Strategy Canvas ---
  {
    name: "StrategyCanvas",
    atomicLevel: "organism",
    filePath: "features/growth-studio/components/strategy-canvas/StrategyCanvas.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: [],
    description: "Visual strategy/funnel canvas with nodes and links.",
  },
  {
    name: "ActionDetailsDrawer",
    atomicLevel: "molecule",
    filePath: "features/growth-studio/components/strategy-canvas/drawer/ActionDetailsDrawer.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["action"],
    description: "Slide-out drawer for strategy action details.",
  },
  {
    name: "BaseLink",
    atomicLevel: "atom",
    filePath: "features/growth-studio/components/strategy-canvas/links/BaseLink.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["from", "to"],
    description: "SVG link connector between canvas nodes.",
  },
  {
    name: "NodeFactory",
    atomicLevel: "molecule",
    filePath: "features/growth-studio/components/strategy-canvas/nodes/NodeFactory.tsx",
    source: "feature",
    featureSlice: "growth-studio",
    variants: [],
    props: ["nodeType", "data"],
    description: "Factory component rendering the correct node type on canvas.",
  },
];
