import { OfferArchetype, OfferValueLevel, OfferDeliveryModel } from "../types";

export type TicketHint = "free" | "low" | "mid" | "high" | "ultra";

export interface FormatPreset {
  id: string;
  archetype: OfferArchetype;
  label: string;
  description: string;
  icon: string; // Lucide icon name
  format_hint: string;
  delivery_model: OfferDeliveryModel;
  suggested_value_level: OfferValueLevel;
  specific_details_defaults: Record<string, unknown>;
  ticket_hint: TicketHint;
  tags: string[];
}

const PRODUCTO_PRESETS: FormatPreset[] = [
  {
    id: "producto_ebook",
    archetype: OfferArchetype.PRODUCTO,
    label: "Ebook / Guia",
    description: "Contenido descargable que educa y posiciona tu expertise.",
    icon: "BookOpen",
    format_hint: "Ebook / Guia",
    delivery_model: OfferDeliveryModel.DIY,
    suggested_value_level: OfferValueLevel.LEAD_MAGNET,
    specific_details_defaults: {},
    ticket_hint: "free",
    tags: ["lead-magnet", "contenido", "digital"],
  },
  {
    id: "producto_curso",
    archetype: OfferArchetype.PRODUCTO,
    label: "Curso Grabado",
    description: "Videos pregrabados con estructura modular y acceso inmediato.",
    icon: "Video",
    format_hint: "Curso Grabado",
    delivery_model: OfferDeliveryModel.DIY,
    suggested_value_level: OfferValueLevel.ACTIVACION,
    specific_details_defaults: {},
    ticket_hint: "low",
    tags: ["curso", "video", "autodirigido"],
  },
  {
    id: "producto_kit",
    archetype: OfferArchetype.PRODUCTO,
    label: "Kit / Toolkit",
    description: "Paquete de plantillas, checklists y recursos listos para usar.",
    icon: "Package",
    format_hint: "Kit / Toolkit",
    delivery_model: OfferDeliveryModel.DIY,
    suggested_value_level: OfferValueLevel.ACTIVACION,
    specific_details_defaults: {},
    ticket_hint: "low",
    tags: ["plantillas", "herramientas", "digital"],
  },
  {
    id: "producto_fisico",
    archetype: OfferArchetype.PRODUCTO,
    label: "Producto Fisico",
    description: "Producto tangible con envio y logistica incluida.",
    icon: "Box",
    format_hint: "Producto Fisico",
    delivery_model: OfferDeliveryModel.DIY,
    suggested_value_level: OfferValueLevel.TRANSFORMACION,
    specific_details_defaults: {},
    ticket_hint: "mid",
    tags: ["fisico", "envio", "tangible"],
  },
  {
    id: "producto_custom",
    archetype: OfferArchetype.PRODUCTO,
    label: "Personalizado",
    description: "Define tu propio formato de producto.",
    icon: "Settings",
    format_hint: "",
    delivery_model: OfferDeliveryModel.DIY,
    suggested_value_level: OfferValueLevel.ACTIVACION,
    specific_details_defaults: {},
    ticket_hint: "low",
    tags: ["custom"],
  },
];

const PROGRAMA_PRESETS: FormatPreset[] = [
  {
    id: "programa_masterclass",
    archetype: OfferArchetype.PROGRAMA,
    label: "Masterclass",
    description: "Sesion intensiva de alto valor sobre un tema especifico.",
    icon: "Presentation",
    format_hint: "Masterclass",
    delivery_model: OfferDeliveryModel.DWY,
    suggested_value_level: OfferValueLevel.ACTIVACION,
    specific_details_defaults: {},
    ticket_hint: "low",
    tags: ["live", "intensivo", "sesion"],
  },
  {
    id: "programa_bootcamp",
    archetype: OfferArchetype.PROGRAMA,
    label: "Bootcamp / Cohorte",
    description: "Programa grupal con fechas fijas y entregables semanales.",
    icon: "GraduationCap",
    format_hint: "Bootcamp / Cohorte",
    delivery_model: OfferDeliveryModel.DWY,
    suggested_value_level: OfferValueLevel.TRANSFORMACION,
    specific_details_defaults: {},
    ticket_hint: "mid",
    tags: ["cohorte", "grupal", "transformacion"],
  },
  {
    id: "programa_certificacion",
    archetype: OfferArchetype.PROGRAMA,
    label: "Certificacion",
    description: "Programa formal con evaluacion y credencial al completar.",
    icon: "Award",
    format_hint: "Certificacion",
    delivery_model: OfferDeliveryModel.DWY,
    suggested_value_level: OfferValueLevel.TRANSFORMACION,
    specific_details_defaults: {},
    ticket_hint: "mid",
    tags: ["certificado", "formal", "credencial"],
  },
  {
    id: "programa_evergreen",
    archetype: OfferArchetype.PROGRAMA,
    label: "Curso Evergreen",
    description: "Programa autodirigido disponible todo el anio, sin cohorte.",
    icon: "Infinity",
    format_hint: "Curso Evergreen",
    delivery_model: OfferDeliveryModel.DIY,
    suggested_value_level: OfferValueLevel.ACTIVACION,
    specific_details_defaults: {},
    ticket_hint: "low",
    tags: ["evergreen", "autodirigido", "escalable"],
  },
  {
    id: "programa_custom",
    archetype: OfferArchetype.PROGRAMA,
    label: "Personalizado",
    description: "Define tu propio formato de programa.",
    icon: "Settings",
    format_hint: "",
    delivery_model: OfferDeliveryModel.DWY,
    suggested_value_level: OfferValueLevel.ACTIVACION,
    specific_details_defaults: {},
    ticket_hint: "low",
    tags: ["custom"],
  },
];

const SERVICIO_PRESETS: FormatPreset[] = [
  {
    id: "servicio_mentoria",
    archetype: OfferArchetype.SERVICIO,
    label: "Mentoria 1:1",
    description: "Acompaniamiento personalizado con sesiones individuales.",
    icon: "UserCheck",
    format_hint: "Mentoria 1:1",
    delivery_model: OfferDeliveryModel.DFY,
    suggested_value_level: OfferValueLevel.MAXIMIZACION,
    specific_details_defaults: {},
    ticket_hint: "high",
    tags: ["1on1", "mentoria", "premium"],
  },
  {
    id: "servicio_dfy",
    archetype: OfferArchetype.SERVICIO,
    label: "Servicio DFY",
    description: "Tu equipo ejecuta todo: el cliente solo aprueba resultados.",
    icon: "Wrench",
    format_hint: "Servicio DFY",
    delivery_model: OfferDeliveryModel.DFY,
    suggested_value_level: OfferValueLevel.MAXIMIZACION,
    specific_details_defaults: {},
    ticket_hint: "high",
    tags: ["done-for-you", "agencia", "ejecucion"],
  },
  {
    id: "servicio_vip_day",
    archetype: OfferArchetype.SERVICIO,
    label: "VIP Day",
    description: "Dia intensivo dedicado a resolver un problema especifico.",
    icon: "Zap",
    format_hint: "VIP Day",
    delivery_model: OfferDeliveryModel.DFY,
    suggested_value_level: OfferValueLevel.TRANSFORMACION,
    specific_details_defaults: {},
    ticket_hint: "mid",
    tags: ["intensivo", "premium", "dia"],
  },
  {
    id: "servicio_retainer",
    archetype: OfferArchetype.SERVICIO,
    label: "Retainer",
    description: "Servicio mensual recurrente con horas o entregables fijos.",
    icon: "CalendarClock",
    format_hint: "Retainer Mensual",
    delivery_model: OfferDeliveryModel.DFY,
    suggested_value_level: OfferValueLevel.TRANSFORMACION,
    specific_details_defaults: {},
    ticket_hint: "mid",
    tags: ["recurrente", "mensual", "retainer"],
  },
  {
    id: "servicio_custom",
    archetype: OfferArchetype.SERVICIO,
    label: "Personalizado",
    description: "Define tu propio formato de servicio.",
    icon: "Settings",
    format_hint: "",
    delivery_model: OfferDeliveryModel.DFY,
    suggested_value_level: OfferValueLevel.ACTIVACION,
    specific_details_defaults: {},
    ticket_hint: "low",
    tags: ["custom"],
  },
];

const MEMBRESIA_PRESETS: FormatPreset[] = [
  {
    id: "membresia_comunidad",
    archetype: OfferArchetype.MEMBRESIA,
    label: "Comunidad",
    description: "Espacio de networking y soporte continuo entre miembros.",
    icon: "Users",
    format_hint: "Comunidad",
    delivery_model: OfferDeliveryModel.DIY,
    suggested_value_level: OfferValueLevel.ACTIVACION,
    specific_details_defaults: {},
    ticket_hint: "low",
    tags: ["comunidad", "networking", "soporte"],
  },
  {
    id: "membresia_biblioteca",
    archetype: OfferArchetype.MEMBRESIA,
    label: "Biblioteca",
    description: "Acceso a una biblioteca creciente de contenido exclusivo.",
    icon: "Library",
    format_hint: "Biblioteca de Contenido",
    delivery_model: OfferDeliveryModel.DIY,
    suggested_value_level: OfferValueLevel.ACTIVACION,
    specific_details_defaults: {},
    ticket_hint: "low",
    tags: ["contenido", "biblioteca", "digital"],
  },
  {
    id: "membresia_mastermind",
    archetype: OfferArchetype.MEMBRESIA,
    label: "Mastermind",
    description: "Grupo selecto con sesiones de estrategia y accountability.",
    icon: "Brain",
    format_hint: "Mastermind",
    delivery_model: OfferDeliveryModel.DWY,
    suggested_value_level: OfferValueLevel.MAXIMIZACION,
    specific_details_defaults: {},
    ticket_hint: "high",
    tags: ["mastermind", "estrategia", "grupal"],
  },
  {
    id: "membresia_inner_circle",
    archetype: OfferArchetype.MEMBRESIA,
    label: "Inner Circle",
    description: "El nivel mas exclusivo: acceso directo, eventos privados y mas.",
    icon: "Crown",
    format_hint: "Inner Circle",
    delivery_model: OfferDeliveryModel.DWY,
    suggested_value_level: OfferValueLevel.MAXIMIZACION,
    specific_details_defaults: {},
    ticket_hint: "ultra",
    tags: ["exclusivo", "vip", "premium"],
  },
  {
    id: "membresia_custom",
    archetype: OfferArchetype.MEMBRESIA,
    label: "Personalizado",
    description: "Define tu propio formato de membresia.",
    icon: "Settings",
    format_hint: "",
    delivery_model: OfferDeliveryModel.DIY,
    suggested_value_level: OfferValueLevel.ACTIVACION,
    specific_details_defaults: {},
    ticket_hint: "low",
    tags: ["custom"],
  },
];

const EXPERIENCIA_PRESETS: FormatPreset[] = [
  {
    id: "experiencia_retiro",
    archetype: OfferArchetype.EXPERIENCIA,
    label: "Retiro",
    description: "Experiencia inmersiva de varios dias en un lugar especial.",
    icon: "Mountain",
    format_hint: "Retiro Inmersivo",
    delivery_model: OfferDeliveryModel.DWY,
    suggested_value_level: OfferValueLevel.MAXIMIZACION,
    specific_details_defaults: {},
    ticket_hint: "high",
    tags: ["retiro", "inmersivo", "presencial"],
  },
  {
    id: "experiencia_evento",
    archetype: OfferArchetype.EXPERIENCIA,
    label: "Evento / Conferencia",
    description: "Evento con speakers, networking y activaciones de marca.",
    icon: "CalendarDays",
    format_hint: "Evento / Conferencia",
    delivery_model: OfferDeliveryModel.DWY,
    suggested_value_level: OfferValueLevel.TRANSFORMACION,
    specific_details_defaults: {},
    ticket_hint: "mid",
    tags: ["evento", "conferencia", "speakers"],
  },
  {
    id: "experiencia_taller",
    archetype: OfferArchetype.EXPERIENCIA,
    label: "Taller Presencial",
    description: "Workshop practico donde los participantes aprenden haciendo.",
    icon: "Hammer",
    format_hint: "Taller Presencial",
    delivery_model: OfferDeliveryModel.DWY,
    suggested_value_level: OfferValueLevel.ACTIVACION,
    specific_details_defaults: {},
    ticket_hint: "low",
    tags: ["taller", "presencial", "practico"],
  },
  {
    id: "experiencia_summit",
    archetype: OfferArchetype.EXPERIENCIA,
    label: "Summit Virtual",
    description: "Evento online con multiples expertos y sesiones en vivo.",
    icon: "Monitor",
    format_hint: "Summit Virtual",
    delivery_model: OfferDeliveryModel.DIY,
    suggested_value_level: OfferValueLevel.ACTIVACION,
    specific_details_defaults: {},
    ticket_hint: "low",
    tags: ["virtual", "summit", "online"],
  },
  {
    id: "experiencia_custom",
    archetype: OfferArchetype.EXPERIENCIA,
    label: "Personalizado",
    description: "Define tu propio formato de experiencia.",
    icon: "Settings",
    format_hint: "",
    delivery_model: OfferDeliveryModel.DWY,
    suggested_value_level: OfferValueLevel.ACTIVACION,
    specific_details_defaults: {},
    ticket_hint: "low",
    tags: ["custom"],
  },
];

export const FORMAT_PRESETS: Record<OfferArchetype, FormatPreset[]> = {
  [OfferArchetype.PRODUCTO]: PRODUCTO_PRESETS,
  [OfferArchetype.PROGRAMA]: PROGRAMA_PRESETS,
  [OfferArchetype.SERVICIO]: SERVICIO_PRESETS,
  [OfferArchetype.MEMBRESIA]: MEMBRESIA_PRESETS,
  [OfferArchetype.EXPERIENCIA]: EXPERIENCIA_PRESETS,
};

export const ALL_PRESETS: FormatPreset[] = Object.values(FORMAT_PRESETS).flat();

export function getPresetById(id: string): FormatPreset | undefined {
  return ALL_PRESETS.find((preset) => preset.id === id);
}

export const TICKET_HINT_LABELS: Record<TicketHint, string> = {
  free: "Gratis",
  low: "Low Ticket",
  mid: "Mid Ticket",
  high: "High Ticket",
  ultra: "Ultra High",
};

export const VALUE_LEVEL_LABELS: Record<OfferValueLevel, string> = {
  [OfferValueLevel.LEAD_MAGNET]: "Lead Magnet",
  [OfferValueLevel.ACTIVACION]: "Activacion",
  [OfferValueLevel.TRANSFORMACION]: "Transformacion",
  [OfferValueLevel.MAXIMIZACION]: "Maximizacion",
  [OfferValueLevel.CORPORATIVO]: "Corporativo",
};

export const DELIVERY_MODEL_LABELS: Record<OfferDeliveryModel, string> = {
  [OfferDeliveryModel.DIY]: "DIY",
  [OfferDeliveryModel.DWY]: "DWY",
  [OfferDeliveryModel.DFY]: "DFY",
  [OfferDeliveryModel.HYBRID]: "Hibrido",
};
