"""Architecture fitness: BE Pydantic ↔ FE zod schema alignment (Story 2B T-5).

Ensures the three analytics copilot tool input schemas stay in sync between
the BE Pydantic models and the FE zod schemas exported via
``npm run schema:export``.

What is checked
---------------
1. ``additionalProperties: false`` present on every exported FE schema
   (mirrors Pydantic ``extra="forbid"``).
2. Every property present in the BE schema also appears in the FE schema
   and vice-versa (no field added on one side without updating the other).
3. Enum values for string-enum fields (``stage``, ``channel``, ``period``)
   match exactly between BE and FE.

Accepted asymmetries (R-4 from 06-tickets.yaml)
------------------------------------------------
- ``required`` list: zod lists fields with ``.default()`` as required; Pydantic
  does not. The test therefore does NOT compare ``required`` lists — only
  field presence and enum values matter for the contract.
- Optional vs nullable: Pydantic marks optional fields as ``anyOf[T, null]``;
  zod marks them optional (absent from ``required``). The test compares enum
  values extracted from the property definition regardless of wrapping shape.

Generation
----------
The FE export is generated by running::

    npm run schema:export

from ``frontend/``. This produces ``frontend/dist/growth-studio-zod-schemas.json``
which this test loads. The test runs the npm script via ``subprocess`` when
the artifact is absent (or stale) so it can run offline in a clean checkout.

Drift detection
---------------
To verify the test catches drift, run::

    python -c "
    import json, pathlib
    p = pathlib.Path('frontend/dist/growth-studio-zod-schemas.json')
    d = json.loads(p.read_text())
    # Simulate drift: remove a stage slug
    d['StageFilterParams']['properties']['stage']['enum'].pop()
    p.write_text(json.dumps(d))
    "
    pytest tests/architecture/test_be_fe_schema_alignment_growth_studio.py -v

Expected output: FAIL with clear diff message pointing to the drifted enum.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

import pytest

# ─── Paths ───────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parents[3]  # backend/ → tests/ → architecture/ → ..3 = AISALESHT/
FRONTEND_DIR = REPO_ROOT / "frontend"
FE_EXPORT_FILE = FRONTEND_DIR / "dist" / "growth-studio-zod-schemas.json"
NPM_SCRIPT = "schema:export"


# ─── Helpers ─────────────────────────────────────────────────────────────────


def _run_npm_export() -> None:
    """Run ``npm run schema:export`` in the frontend directory.

    Called when the export artifact is absent so the test is self-healing
    in a clean checkout. Fails the test with a clear message if npm errors.
    """
    result = subprocess.run(  # noqa: S603
        ["npm", "run", NPM_SCRIPT],  # noqa: S607
        cwd=FRONTEND_DIR,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        pytest.fail(
            f"npm run {NPM_SCRIPT} failed (exit {result.returncode}):\nstdout: {result.stdout}\nstderr: {result.stderr}"
        )


def _load_fe_schemas() -> dict[str, Any]:
    """Load the FE zod JSON schema export; regenerate if absent."""
    if not FE_EXPORT_FILE.exists():
        _run_npm_export()
    return json.loads(FE_EXPORT_FILE.read_text())  # type: ignore[return-value]


def _extract_enum_values(prop_schema: dict[str, Any]) -> list[str] | None:
    """Extract enum values from a JSON Schema property, handling anyOf wrapping.

    Pydantic optional fields are ``anyOf[{enum: [...]}, {type: "null"}]``.
    Zod optional fields are plain ``{enum: [...]}`` (not in required list).
    Both representations are normalised to a plain sorted list for comparison.
    """
    # Direct enum field
    if "enum" in prop_schema:
        return sorted(str(v) for v in prop_schema["enum"])

    # Pydantic anyOf nullable pattern: anyOf: [{enum: [...]}, {type: "null"}]
    if "anyOf" in prop_schema:
        for branch in prop_schema["anyOf"]:
            if "enum" in branch:
                return sorted(str(v) for v in branch["enum"])

    return None


# ─── Fixtures ─────────────────────────────────────────────────────────────────


@pytest.fixture(scope="module")
def be_schemas() -> dict[str, Any]:
    """Load BE Pydantic JSON schemas (model_json_schema)."""
    from src.modules.copilot.application.tools._analytics_inputs import (
        ChannelOverviewParams,
        StageFilterParams,
        TriggerEtlRefreshParams,
    )

    return {
        "StageFilterParams": StageFilterParams.model_json_schema(),
        "ChannelOverviewParams": ChannelOverviewParams.model_json_schema(),
        "TriggerEtlRefreshParams": TriggerEtlRefreshParams.model_json_schema(),
    }


@pytest.fixture(scope="module")
def fe_schemas() -> dict[str, Any]:
    """Load FE zod JSON schema export (generated via npm run schema:export)."""
    return _load_fe_schemas()


# ─── Tests ────────────────────────────────────────────────────────────────────


class TestSchemaExportExists:
    """Sanity checks on the export artifact itself."""

    def test_all_three_schemas_exported(self, fe_schemas: dict[str, Any]) -> None:
        """Export file must contain all three input schemas."""
        expected = {"StageFilterParams", "ChannelOverviewParams", "TriggerEtlRefreshParams"}
        missing = expected - set(fe_schemas.keys())
        assert not missing, (
            f"FE schema export is missing schemas: {missing}. "
            "Run 'npm run schema:export' in frontend/ and verify the script covers all three schemas."
        )

    def test_fe_schemas_are_objects(self, fe_schemas: dict[str, Any]) -> None:
        """Each exported schema must be a valid JSON Schema object."""
        for name, schema in fe_schemas.items():
            assert isinstance(schema, dict), f"{name}: expected a JSON Schema dict, got {type(schema)}"
            assert "properties" in schema, f"{name}: missing 'properties' key — not a valid object schema"


class TestAdditionalPropertiesForbidden:
    """Both sides must declare extra='forbid' / .strict() to block payload injection."""

    @pytest.mark.parametrize("schema_name", ["StageFilterParams", "ChannelOverviewParams", "TriggerEtlRefreshParams"])
    def test_be_additional_properties_false(self, be_schemas: dict[str, Any], schema_name: str) -> None:
        """BE Pydantic schema must have additionalProperties: false (extra='forbid')."""
        schema = be_schemas[schema_name]
        assert schema.get("additionalProperties") is False, (
            f"BE {schema_name}: expected additionalProperties=false (Pydantic extra='forbid'). "
            "Adversarial defense requires this — removing it allows tenant_id payload smuggling."
        )

    @pytest.mark.parametrize("schema_name", ["StageFilterParams", "ChannelOverviewParams", "TriggerEtlRefreshParams"])
    def test_fe_additional_properties_false(self, fe_schemas: dict[str, Any], schema_name: str) -> None:
        """FE zod schema must have additionalProperties: false (.strict())."""
        schema = fe_schemas[schema_name]
        assert schema.get("additionalProperties") is False, (
            f"FE {schema_name}: expected additionalProperties=false (zod .strict()). "
            "Adversarial defense requires this — mirrors Pydantic extra='forbid'."
        )


class TestFieldNamesAlignment:
    """Every field present in BE must exist in FE and vice-versa."""

    @pytest.mark.parametrize("schema_name", ["StageFilterParams", "ChannelOverviewParams", "TriggerEtlRefreshParams"])
    def test_be_fields_present_in_fe(
        self, be_schemas: dict[str, Any], fe_schemas: dict[str, Any], schema_name: str
    ) -> None:
        """Fields defined in BE Pydantic must all exist in FE zod schema."""
        be_props = set(be_schemas[schema_name].get("properties", {}).keys())
        fe_props = set(fe_schemas[schema_name].get("properties", {}).keys())
        missing_in_fe = be_props - fe_props
        assert not missing_in_fe, (
            f"{schema_name}: BE fields missing from FE zod schema: {missing_in_fe}. "
            "Update frontend/scripts/export-zod-schemas.ts to include all BE fields."
        )

    @pytest.mark.parametrize("schema_name", ["StageFilterParams", "ChannelOverviewParams", "TriggerEtlRefreshParams"])
    def test_fe_fields_present_in_be(
        self, be_schemas: dict[str, Any], fe_schemas: dict[str, Any], schema_name: str
    ) -> None:
        """Fields defined in FE zod must all exist in BE Pydantic schema."""
        be_props = set(be_schemas[schema_name].get("properties", {}).keys())
        fe_props = set(fe_schemas[schema_name].get("properties", {}).keys())
        extra_in_fe = fe_props - be_props
        assert not extra_in_fe, (
            f"{schema_name}: FE zod fields absent from BE Pydantic schema: {extra_in_fe}. "
            "Remove the extra fields from frontend/scripts/export-zod-schemas.ts "
            "or add them to backend/src/modules/copilot/application/tools/_analytics_inputs.py."
        )


class TestEnumValueAlignment:
    """Enum values (stage slugs, channel slugs, period values) must match exactly."""

    @pytest.mark.parametrize(
        "schema_name,field_name",
        [
            ("StageFilterParams", "stage"),
            ("StageFilterParams", "channel"),
            ("StageFilterParams", "period"),
            ("ChannelOverviewParams", "channel"),
            ("TriggerEtlRefreshParams", "channel"),
        ],
    )
    def test_enum_values_match(
        self,
        be_schemas: dict[str, Any],
        fe_schemas: dict[str, Any],
        schema_name: str,
        field_name: str,
    ) -> None:
        """Enum values for a field must be identical between BE and FE."""
        be_prop = be_schemas[schema_name].get("properties", {}).get(field_name)
        fe_prop = fe_schemas[schema_name].get("properties", {}).get(field_name)

        assert be_prop is not None, f"BE {schema_name}.{field_name} not found in schema"
        assert fe_prop is not None, f"FE {schema_name}.{field_name} not found in schema"

        be_enum = _extract_enum_values(be_prop)
        fe_enum = _extract_enum_values(fe_prop)

        assert be_enum is not None, (
            f"BE {schema_name}.{field_name} has no enum values — expected a Literal type; got: {{be_prop}}"
        )
        assert fe_enum is not None, (
            f"FE {schema_name}.{field_name} has no enum values — expected a z.enum() type; got: {{fe_prop}}"
        )

        assert be_enum == fe_enum, (
            f"{schema_name}.{field_name} enum mismatch:\n"
            f"  BE  ({len(be_enum)} values): {be_enum}\n"
            f"  FE  ({len(fe_enum)} values): {fe_enum}\n"
            "Update the out-of-sync side to match. "
            "BE canonical values live in: backend/src/modules/copilot/application/tools/_analytics_inputs.py. "
            "FE canonical values live in: frontend/scripts/export-zod-schemas.ts "
            "(sourced from frontend/src/features/growth-studio/lib/registries/)."
        )


class TestDriftDetection:
    """Meta-test: verify the test itself catches intentional drift.

    This class documents the drift scenarios that would cause failures,
    serving as executable specification for future maintainers.
    """

    def test_stage_enum_count_matches_registry(self, be_schemas: dict[str, Any]) -> None:
        """BE stage enum must have exactly 5 values (one per funnel stage)."""
        stage_prop = be_schemas["StageFilterParams"]["properties"]["stage"]
        stage_enums = _extract_enum_values(stage_prop)
        assert stage_enums is not None
        assert len(stage_enums) == 5, (
            f"Expected exactly 5 stage slugs (one per funnel stage), got {len(stage_enums)}: {stage_enums}. "
            "If a new stage was added, update both BE Literal and FE registry."
        )

    def test_channel_enum_count_matches_registry(self, be_schemas: dict[str, Any]) -> None:
        """BE channel enum must have exactly 5 values (matching CHANNEL_REGISTRY)."""
        channel_prop = be_schemas["ChannelOverviewParams"]["properties"]["channel"]
        channel_enums = _extract_enum_values(channel_prop)
        assert channel_enums is not None
        assert len(channel_enums) == 5, (
            f"Expected exactly 5 channel slugs (matching CHANNEL_REGISTRY), got {len(channel_enums)}: {channel_enums}. "
            "If a new channel was added, update both BE Literal and FE registry."
        )

    def test_period_enum_has_three_values(self, be_schemas: dict[str, Any]) -> None:
        """Period enum must offer exactly 3 time windows: 7d, 30d, 90d."""
        period_prop = be_schemas["StageFilterParams"]["properties"]["period"]
        period_enums = _extract_enum_values(period_prop)
        assert period_enums is not None
        assert sorted(period_enums) == sorted(["7d", "30d", "90d"]), (
            f"Expected period values ['7d', '30d', '90d'], got {period_enums}. "
            "Update BE Literal and FE zod enum if time windows change."
        )
