export const OAUTH_MESSAGE_TYPES = {
  GOOGLE_SUCCESS: "GOOGLE_OAUTH_SUCCESS",
  GOOGLE_ERROR: "GOOGLE_OAUTH_ERROR",
  META_SUCCESS: "META_OAUTH_SUCCESS",
  META_ERROR: "META_OAUTH_ERROR",
} as const;

export const POPUP_CLOSE_DELAY = 1500;
