from sqlalchemy import Column, String, DateTime, ForeignKey, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.sql import func
import uuid
from src.shared.domain.base_entity import Base

class GalleryImageModel(Base):
    """
    Images specific to a Product/Offer with AI-generated metadata.
    Stored in static/offers/{offer_id}/gallery/
    """
    __tablename__ = "offer_gallery_images"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id = Column(UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=True)
    offer_id = Column(UUID(as_uuid=True), ForeignKey("products.id"), nullable=False, index=True)
    
    # File Info
    filename = Column(String, nullable=False)
    file_path = Column(String, nullable=False) # Local storage path
    public_url = Column(String, nullable=False) # URL accessible by frontend
    
    # Metadata
    user_description = Column(Text, nullable=True) # Optional user description
    ai_description = Column(Text, nullable=True) # Generated by AI
    ai_colors = Column(JSONB, default=[]) # List of hex codes
    
    # Processing Status
    status = Column(String, default="processing") # processing, completed, failed
    error_message = Column(Text, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationship
    # offer = relationship("src.modules.offer.infrastructure.models.product_model.ProductModel")
