"""OutboxService — application service for enqueuing domain events.

Exposes two public entry points:
- ``enqueue_sync`` — for synchronous Session callers (75%+ of sites).
- ``enqueue_async_from_sync_caller`` — for AsyncSession callers.

Both methods require a session argument (no session = ValueError).
Caller is responsible for session.commit().
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import structlog

from src.shared.domain_events.outbox.domain.outbox_entry import OutboxEntry
from src.shared.domain_events.outbox.infrastructure.repository import OutboxRepositoryImpl

if TYPE_CHECKING:
    from sqlalchemy.ext.asyncio import AsyncSession
    from sqlalchemy.orm import Session

    from src.shared.domain_events.outbox.domain.event import DomainEvent

logger = structlog.get_logger(__name__)


class OutboxService:
    """SSoT enqueue API for domain events via transactional outbox.

    Builder + adapter consume this path. Guarantees:
    - Session is always required (no fire-and-forget without DB context).
    - Caller is responsible for commit (respects caller's unit-of-work).
    - Idempotency deduplication via (tenant_id, idempotency_key) unique constraint.
    - NEVER dispatches handlers in-memory (OutboxDispatcher does that).
    """

    def __init__(self, repo: OutboxRepositoryImpl | None = None) -> None:
        """Initialize with optional repo injection for testing."""
        self._repo = repo or OutboxRepositoryImpl()

    def enqueue_sync(
        self,
        event: DomainEvent,
        *,
        session: Session,
        idempotency_key: str | None = None,
    ) -> None:
        """Insert outbox entry inside a synchronous Session transaction.

        Args:
            event: Domain event to persist.
            session: Synchronous SQLAlchemy Session. MANDATORY.
            idempotency_key: Optional natural key. Autogenerated if None.

        Raises:
            ValueError: If session is None.
        """
        if session is None:
            msg = (
                "OutboxService.enqueue_sync requires a session. "
                "Use EventBusAdapter with session=None for fire-and-forget (legacy path)."
            )
            raise ValueError(msg)
        entry = OutboxEntry.from_event(event, idempotency_key=idempotency_key)
        self._repo.append_sync(entry, session=session)
        logger.info(
            "outbox_enqueued_sync",
            tenant_id=str(event.tenant_id),
            event_name=event.event_name,
            idempotency_key=entry.idempotency_key,
            entry_id=str(entry.id),
        )

    async def enqueue_async_from_sync_caller(
        self,
        event: DomainEvent,
        *,
        session: AsyncSession,
        idempotency_key: str | None = None,
    ) -> None:
        """Insert outbox entry inside an AsyncSession transaction.

        Args:
            event: Domain event to persist.
            session: Async SQLAlchemy AsyncSession. MANDATORY.
            idempotency_key: Optional natural key. Autogenerated if None.

        Raises:
            ValueError: If session is None.
        """
        if session is None:
            msg = "OutboxService.enqueue_async_from_sync_caller requires a session."
            raise ValueError(msg)
        entry = OutboxEntry.from_event(event, idempotency_key=idempotency_key)
        await self._repo.append(entry, session=session)
        logger.info(
            "outbox_enqueued_async",
            tenant_id=str(event.tenant_id),
            event_name=event.event_name,
            idempotency_key=entry.idempotency_key,
            entry_id=str(entry.id),
        )
