/**
 * TypeScript mirror of CONTRACT.md §5 (camelCase).
 * Wire format is snake_case (Pydantic default) — mapping happens in the API layer.
 */

export type ModelTier = "nano" | "mini" | "reasoning" | "heavy";

export interface ConversationSummary {
  id: string;
  title: string | null;
  titleAutoGenerated: boolean;
  updatedAt: string; // ISO 8601
  messageCount: number;
  totalTokens: number;
  lastTierUsed: ModelTier | null;
  hasProcedure: boolean;
  procedureProgress: number | null; // 0..1
  archivedAt: string | null;
}

export interface ConversationListResponse {
  items: ConversationSummary[];
  nextCursor: string | null;
}

export type ConversationMessageRole = "user" | "assistant" | "tool";
export type ConversationMessageStatus = "sending" | "streaming" | "sent" | "error";

export interface ConversationMessage {
  id: string;
  role: ConversationMessageRole;
  content: string;
  blocks: Record<string, unknown>[] | null;
  status: ConversationMessageStatus;
  createdAt: string; // ISO 8601 UTC
  tokensUsed: number | null;
  metadata: Record<string, unknown> | null;
}

export interface ConversationDetail extends ConversationSummary {
  messages: ConversationMessage[];
}

export interface PatchConversationRequest {
  title?: string;
  archived?: boolean;
}

export interface RevertRequest {
  mutationIds?: string[]; // UUID[]; omit = revert all
}

export interface RevertFailure {
  id: string;
  error: string;
}

export interface RevertResponse {
  revertedCount: number;
  failed: RevertFailure[];
}

export interface SlashCommand {
  name: string; // e.g. "llena-identidad"
  description: string;
  skillId: string;
}

export interface PlanStep {
  order: number;
  label: string;
  toolName: string;
  estimatedTokens: number;
}

export interface PlanState {
  steps: PlanStep[];
  estimatedCostUsd: number;
  status: "pending" | "approved" | "rejected";
}

export interface PlanApproveResponse {
  status: "approved";
}

export interface PlanRejectResponse {
  status: "rejected";
}

// SSE event additions
export interface TierDecisionEvent {
  tier: ModelTier;
  reason: string;
  classifierUsed: "rule" | "llm" | "default";
  confidence: number;
}

export interface MutationAppliedEvent {
  id: string;
  domain: string;
  entityId: string | null;
  fieldPath: string;
  canRevert: boolean;
}

// ── Wire-to-domain mapping helpers ──────────────────────────────────

/** Maps a snake_case wire ConversationSummary to camelCase domain type. */
export function mapConversationSummary(wire: Record<string, unknown>): ConversationSummary {
  return {
    id: wire.id as string,
    title: (wire.title as string | null) ?? null,
    titleAutoGenerated: Boolean(wire.title_auto_generated),
    updatedAt: wire.updated_at as string,
    messageCount: (wire.message_count as number) ?? 0,
    totalTokens: (wire.total_tokens as number) ?? 0,
    lastTierUsed: (wire.last_tier_used as ModelTier | null) ?? null,
    hasProcedure: Boolean(wire.has_procedure),
    procedureProgress: (wire.procedure_progress as number | null) ?? null,
    archivedAt: (wire.archived_at as string | null) ?? null,
  };
}

/** Maps a snake_case wire ConversationListResponse to camelCase domain type. */
export function mapConversationListResponse(
  wire: Record<string, unknown>,
): ConversationListResponse {
  const items = (wire.items as Record<string, unknown>[]) ?? [];
  return {
    items: items.map(mapConversationSummary),
    nextCursor: (wire.next_cursor as string | null) ?? null,
  };
}

/** Maps a snake_case wire ConversationMessageDTO to camelCase domain type. */
export function mapConversationMessage(wire: Record<string, unknown>): ConversationMessage {
  return {
    id: wire.id as string,
    role: wire.role as ConversationMessageRole,
    content: (wire.content as string) ?? "",
    blocks: (wire.blocks as Record<string, unknown>[] | null) ?? null,
    status: (wire.status as ConversationMessageStatus) ?? "sent",
    createdAt: wire.created_at as string,
    tokensUsed: (wire.tokens_used as number | null) ?? null,
    metadata: (wire.metadata as Record<string, unknown> | null) ?? null,
  };
}

/** Maps a snake_case wire ConversationDetail to camelCase domain type. */
export function mapConversationDetail(wire: Record<string, unknown>): ConversationDetail {
  const summary = mapConversationSummary(wire);
  const messagesRaw = (wire.messages as Record<string, unknown>[]) ?? [];
  return {
    ...summary,
    messages: messagesRaw.map(mapConversationMessage),
  };
}

/** Maps a snake_case wire RevertResponse to camelCase domain type. */
export function mapRevertResponse(wire: Record<string, unknown>): RevertResponse {
  const failed = (wire.failed as { id: string; error: string }[]) ?? [];
  return {
    revertedCount: (wire.reverted_count as number) ?? 0,
    failed,
  };
}

/** Maps a snake_case wire SlashCommand to camelCase domain type. */
export function mapSlashCommand(wire: Record<string, unknown>): SlashCommand {
  return {
    name: wire.name as string,
    description: wire.description as string,
    skillId: (wire.skill_id as string) ?? "",
  };
}
