"""Initial Multitenancy Schema

Revision ID: 16a58268fd71
Revises: 
Create Date: 2026-01-27 09:48:31.884936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16a58268fd71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.add_column('agent_traces', sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'agent_traces', 'tenants', ['tenant_id'], ['id'])
    op.add_column('appointments', sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'appointments', 'tenants', ['tenant_id'], ['id'])
    op.add_column('avatar_definitions', sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'avatar_definitions', 'tenants', ['tenant_id'], ['id'])
    op.add_column('documents', sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'documents', 'tenants', ['tenant_id'], ['id'])
    op.add_column('enrollments', sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'enrollments', 'tenants', ['tenant_id'], ['id'])
    op.add_column('llm_call_logs', sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'llm_call_logs', 'tenants', ['tenant_id'], ['id'])
    op.add_column('marketing_assets', sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'marketing_assets', 'tenants', ['tenant_id'], ['id'])
    op.add_column('messages', sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'messages', 'tenants', ['tenant_id'], ['id'])
    op.add_column('objections', sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'objections', 'tenants', ['tenant_id'], ['id'])
    op.add_column('offer_logs', sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'offer_logs', 'tenants', ['tenant_id'], ['id'])
    op.add_column('products', sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'products', 'tenants', ['tenant_id'], ['id'])
    op.add_column('prompt_versions', sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'prompt_versions', 'tenants', ['tenant_id'], ['id'])
    op.add_column('sensitive_data', sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'sensitive_data', 'tenants', ['tenant_id'], ['id'])
    op.add_column('users', sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.alter_column('users', 'custom_system_instruction',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'custom_system_instruction',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'sensitive_data', type_='foreignkey')
    op.drop_column('sensitive_data', 'tenant_id')
    op.drop_constraint(None, 'prompt_versions', type_='foreignkey')
    op.drop_column('prompt_versions', 'tenant_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'tenant_id')
    op.drop_constraint(None, 'offer_logs', type_='foreignkey')
    op.drop_column('offer_logs', 'tenant_id')
    op.drop_constraint(None, 'objections', type_='foreignkey')
    op.drop_column('objections', 'tenant_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'tenant_id')
    op.drop_constraint(None, 'marketing_assets', type_='foreignkey')
    op.drop_column('marketing_assets', 'tenant_id')
    op.drop_constraint(None, 'llm_call_logs', type_='foreignkey')
    op.drop_column('llm_call_logs', 'tenant_id')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_column('enrollments', 'tenant_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'tenant_id')
    op.drop_constraint(None, 'avatar_definitions', type_='foreignkey')
    op.drop_column('avatar_definitions', 'tenant_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'tenant_id')
    op.drop_constraint(None, 'agent_traces', type_='foreignkey')
    op.drop_column('agent_traces', 'tenant_id')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
