"""add_offer_value_stack_fields

Revision ID: 172756e46378
Revises: 9c6fc3c2980b
Create Date: 2026-02-02 22:19:56.663126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '172756e46378'
down_revision: Union[str, None] = '9c6fc3c2980b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('primary_outcome', sa.String(), nullable=True))
    op.add_column('products', sa.Column('time_to_value', sa.String(), nullable=True))
    op.add_column('products', sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('guarantee_terms', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('includes_offers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'includes_offers')
    op.drop_column('products', 'guarantee_terms')
    op.drop_column('products', 'prerequisites')
    op.drop_column('products', 'time_to_value')
    op.drop_column('products', 'primary_outcome')
    # ### end Alembic commands ###
