"""fix_multitenant_user_constraint

Revision ID: 28260b11b4aa
Revises: d25f28231eee
Create Date: 2026-02-15 21:11:53.878346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import SQLAlchemyError


# revision identifiers, used by Alembic.
revision: str = '28260b11b4aa'
down_revision: Union[str, None] = 'd25f28231eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # 1. Add column (MANDATORY)
    # Check if column exists first to be safe (idempotency), but do NOT catch errors if add_column fails.
    # We want it to fail if it can't add the column.
    
    columns = [c['name'] for c in inspector.get_columns('tenants')]
    if 'clerk_org_id' not in columns:
        print("Adding column clerk_org_id to tenants...")
        op.add_column('tenants', sa.Column('clerk_org_id', sa.String(), nullable=True))
        op.create_index(op.f('ix_tenants_clerk_org_id'), 'tenants', ['clerk_org_id'], unique=False)
    else:
        print("Column clerk_org_id already exists in tenants.")
    
    # 2. Drop constraint safely (Optional-ish, but good for cleanup)
    # We catch errors here because dropping constraints is tricky with names.
    try:
        constraints = inspector.get_unique_constraints('users')
        constraint_names = [c['name'] for c in constraints]
        
        # Constraints we want to remove
        target_constraints = ['users_email_key1', 'users_email_key', 'uq_users_email']
        
        for target in target_constraints:
            if target in constraint_names:
                op.drop_constraint(target, 'users', type_='unique')
                print(f"Dropped constraint: {target}")
    except Exception as e:
        print(f"Warning dropping constraints: {e}")

    # 3. Create new constraint
    try:
        user_columns = [c['name'] for c in inspector.get_columns('users')]
        if 'tenant_id' in user_columns:
            # Check if constraint already exists
            constraints = inspector.get_unique_constraints('users')
            constraint_names = [c['name'] for c in constraints]
            
            if 'uq_user_email_tenant' not in constraint_names:
                op.create_unique_constraint('uq_user_email_tenant', 'users', ['email', 'tenant_id'])
                print("Created constraint uq_user_email_tenant")
            else:
                print("Constraint uq_user_email_tenant already exists")
        else:
             print("CRITICAL WARNING: Column 'tenant_id' missing in users table. Skipping constraint creation.")
    except Exception as e:
        print(f"Warning creating uq_user_email_tenant: {e}")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if constraint exists before dropping
    try:
        constraints = inspector.get_unique_constraints('users')
        constraint_names = [c['name'] for c in constraints]
        if 'uq_user_email_tenant' in constraint_names:
            op.drop_constraint('uq_user_email_tenant', 'users', type_='unique')
    except Exception:
        pass

    # Check if constraint to recreate exists
    try:
        constraints = inspector.get_unique_constraints('users')
        constraint_names = [c['name'] for c in constraints]
        if 'users_email_key' not in constraint_names:
            op.create_unique_constraint('users_email_key', 'users', ['email'])
    except Exception:
        pass

    # Check if index exists before dropping
    try:
        indexes = inspector.get_indexes('tenants')
        index_names = [i['name'] for i in indexes]
        if 'ix_tenants_clerk_org_id' in index_names:
            op.drop_index(op.f('ix_tenants_clerk_org_id'), table_name='tenants')
    except Exception:
        pass
        
    # Check if column exists before dropping
    try:
        columns = [c['name'] for c in inspector.get_columns('tenants')]
        if 'clerk_org_id' in columns:
            op.drop_column('tenants', 'clerk_org_id')
    except Exception:
        pass
    # ### end Alembic commands ###
