"""fix_multitenant_user_constraint

Revision ID: 28260b11b4aa
Revises: d25f28231eee
Create Date: 2026-02-15 21:11:53.878346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28260b11b4aa'
down_revision: Union[str, None] = 'd25f28231eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('clerk_org_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_tenants_clerk_org_id'), 'tenants', ['clerk_org_id'], unique=False)
    op.drop_constraint(op.f('users_email_key1'), 'users', type_='unique')
    op.create_unique_constraint('uq_user_email_tenant', 'users', ['email', 'tenant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_email_tenant', 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key1'), 'users', ['email'])
    op.drop_index(op.f('ix_tenants_clerk_org_id'), table_name='tenants')
    op.drop_column('tenants', 'clerk_org_id')
    # ### end Alembic commands ###
