"""fix_multitenant_user_constraint

Revision ID: 28260b11b4aa
Revises: d25f28231eee
Create Date: 2026-02-15 21:11:53.878346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import SQLAlchemyError


# revision identifiers, used by Alembic.
revision: str = '28260b11b4aa'
down_revision: Union[str, None] = 'd25f28231eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add column (Safe operation)
    # Check if column exists first to be safe (idempotency)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('tenants')]
    if 'clerk_org_id' not in columns:
        op.add_column('tenants', sa.Column('clerk_org_id', sa.String(), nullable=True))
        op.create_index(op.f('ix_tenants_clerk_org_id'), 'tenants', ['clerk_org_id'], unique=False)
    
    # 2. Drop constraint safely
    # Production might have different constraint names or none at all.
    # We inspect existing constraints on 'users' table.
    try:
        constraints = inspector.get_unique_constraints('users')
        constraint_names = [c['name'] for c in constraints]
        
        # Constraints we want to remove
        target_constraints = ['users_email_key1', 'users_email_key', 'uq_users_email']
        
        for target in target_constraints:
            if target in constraint_names:
                op.drop_constraint(target, 'users', type_='unique')
                print(f"Dropped constraint: {target}")
    except Exception as e:
        print(f"Error checking/dropping constraints: {e}")

    # 3. Create new constraint
    # We use a try/except block to avoid failure if it already exists partially
    try:
        op.create_unique_constraint('uq_user_email_tenant', 'users', ['email', 'tenant_id'])
    except Exception as e:
        print(f"Warning creating uq_user_email_tenant (might exist): {e}")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_email_tenant', 'users', type_='unique')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_tenants_clerk_org_id'), table_name='tenants')
    op.drop_column('tenants', 'clerk_org_id')
    # ### end Alembic commands ###
