"""add_offer_id_to_gallery_images

Revision ID: 3d6ac283c93d
Revises: 8bd6b013a46e
Create Date: 2026-02-25 16:58:02.214550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d6ac283c93d'
down_revision: Union[str, None] = '8bd6b013a46e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery_images', sa.Column('offer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_gallery_images_offer_id'), 'gallery_images', ['offer_id'], unique=False)
    op.create_foreign_key('fk_gallery_images_offer_id', 'gallery_images', 'products', ['offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_gallery_images_offer_id', 'gallery_images', type_='foreignkey')
    op.drop_index(op.f('ix_gallery_images_offer_id'), table_name='gallery_images')
    op.drop_column('gallery_images', 'offer_id')
    # ### end Alembic commands ###
