"""add landing_page_config to products

Revision ID: 70d8a5c3e9a1
Revises: 6ff69443dd82
Create Date: 2026-02-11 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70d8a5c3e9a1'
down_revision = '66a20b0fa0fc' # Corrected previous head
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('landing_page_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'landing_page_config')
    # ### end Alembic commands ###
