"""fix_products_schema_timestamps

Revision ID: 94469ab70585
Revises: 3d6ac283c93d
Create Date: 2026-02-25 18:25:52.329872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94469ab70585'
down_revision: Union[str, None] = '3d6ac283c93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Products table updates only
    op.add_column('products', sa.Column('marketing_pain_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('marketing_desires', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('support_duration_days', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('onboarding_action', sa.String(), nullable=True))
    op.add_column('products', sa.Column('onboarding_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('calendar_type_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('checkout_page_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('vsl_link', sa.String(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'vsl_link')
    op.drop_column('products', 'checkout_page_url')
    op.drop_column('products', 'calendar_type_id')
    op.drop_column('products', 'onboarding_url')
    op.drop_column('products', 'onboarding_action')
    op.drop_column('products', 'support_duration_days')
    op.drop_column('products', 'marketing_desires')
    op.drop_column('products', 'marketing_pain_points')
    # ### end Alembic commands ###
