"""user_tenant_m2m

Revision ID: f43d58dc53c2
Revises: 28260b11b4aa
Create Date: 2026-02-17 02:10:54.107128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f43d58dc53c2'
down_revision: Union[str, None] = '28260b11b4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tenants',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id')
    )
    
    # Data migration: Copy existing user-tenant relationships
    conn = op.get_bind()
    conn.execute(sa.text("""
        INSERT INTO user_tenants (user_id, tenant_id, role, created_at)
        SELECT id, tenant_id, 'admin', NOW()
        FROM users
        WHERE tenant_id IS NOT NULL
    """))

    # Use IF EXISTS to handle production DBs where constraints may have different names
    op.execute('ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_user_email_tenant')
    op.execute('ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_users_email_tenant')
    op.create_unique_constraint(None, 'users', ['email'])
    op.execute('ALTER TABLE users DROP CONSTRAINT IF EXISTS users_tenant_id_fkey1')
    op.execute('ALTER TABLE users DROP COLUMN IF EXISTS tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_tenant_id_fkey1'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_user_email_tenant'), 'users', ['email', 'tenant_id'])
    op.drop_table('user_tenants')
    # ### end Alembic commands ###
