# This file is used by Shopify CLI to manage your app's configuration.
# To push this configuration to Shopify, run: `shopify app config push`

client_id = "d2bf80a34c0f7db6f4c33cb37bd5dc88"
name = "nicolify-dev"
application_url = "https://dev-app.nicolify.com"
embedded = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
uri = "https://dev-api.nicolify.com/api/v1/connections/shopify/compliance/customers/data_request"
compliance_topics = [ "customers/data_request" ]

[[webhooks.subscriptions]]
uri = "https://dev-api.nicolify.com/api/v1/connections/shopify/compliance/customers/redact"
compliance_topics = [ "customers/redact" ]

[[webhooks.subscriptions]]
uri = "https://dev-api.nicolify.com/api/v1/connections/shopify/compliance/shop/redact"
compliance_topics = [ "shop/redact" ]

[auth]
redirect_urls = [
  "https://dev-app.nicolify.com/api/auth/shopify/callback"
]

[access_scopes]
# Scopes requested by the backend
scopes = "write_customers,write_orders,read_analytics,read_customer_events,read_cart_transforms,read_all_cart_transforms,read_channels,read_checkouts,read_companies,read_custom_pixels,read_customers,read_customer_data_erasure,read_customer_merge,read_price_rules,read_discounts,read_discounts_allocator_functions,read_discovery,read_draft_orders,read_fulfillments,read_gift_card_transactions,read_gift_cards,read_inventory,read_inventory_shipments,read_inventory_shipments_received_items,read_locales,read_locations,read_marketing_integrated_campaigns,read_marketing_events,read_markets,read_markets_home,read_merchant_managed_fulfillment_orders,read_metaobject_definitions,read_metaobjects,read_online_store_navigation,read_online_store_pages,read_order_edits,read_orders,read_packing_slip_templates,read_payment_terms,read_payment_customizations,read_product_feeds,read_product_listings,read_products,read_publications,read_purchase_options,read_reports,read_resource_feedbacks,read_returns,read_script_tags,read_shipping,read_shopify_payments_payouts,read_shopify_payments_disputes,read_content,read_store_credit_account_transactions,read_third_party_fulfillment_orders,read_translations,read_pixels"

[pos]
embedded = false
