"""Extraction Contract — Single source of truth for the analytics ETL pipeline.

This module is the canonical reference for what the ETL extracts, from which
external sources, when, how, and where the data lands. It is the answer to
the question "where does this metric come from?" without having to read every
provider implementation.

The contract is enforced by ``tests/architecture/test_extraction_contract.py``:

* Every entry in :data:`EXTRACTION_CONTRACTS` must reference a real provider
  class registered in :data:`PROVIDER_REGISTRY`.
* Every provider in ``PROVIDER_REGISTRY`` must have an entry here.
* Every metric in :mod:`metric_catalog` whose ``providers`` tuple lists a
  provider must appear in that provider's :class:`ChannelOutput`.

The human-readable Markdown rendering lives at
``docs/etl/extraction-contract.md`` and is regenerated by
``backend/scripts/generate_extraction_contract_doc.py``.

When you add a new provider or change what an existing provider extracts:

1. Update the implementation in ``infrastructure/providers/{name}_provider.py``.
2. Update the corresponding entry here.
3. Run the architecture test to confirm there is no drift.
4. Regenerate the Markdown doc.
"""

from dataclasses import dataclass
from enum import StrEnum

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class ExtractionMode(StrEnum):
    """How and when a provider's extraction is invoked."""

    DAILY_ETL = "daily_etl"
    """Pulled from ``run_tenant_extraction`` enqueued by the tick scheduler at
    3am local time. Hits the provider's daily endpoint and writes one row per
    (channel, metric, day) into ``official_metrics``."""

    PERIOD_BACKFILL = "period_backfill"
    """Pulled from ``run_period_extraction`` for NON_AGGREGABLE metrics
    (reach, users, frequency, repeat_customers, …). Writes to
    ``period_metrics`` for an entire week/month/quarter at once."""

    INITIAL_LOAD = "initial_load"
    """Pulled from ``run_initial_load`` when a tenant connects a new provider
    or manually re-extracts (capped at ``ETLConfig.MAX_LOOKBACK_DAYS``).
    Same code path as DAILY_ETL but iterates a longer window."""

    CAMPAIGN_SYNC = "campaign_sync"
    """Pulled from ``run_campaign_sync`` to refresh campaign/ad-set/ad
    hierarchy metadata (NOT metrics). Writes to ``ad_campaigns``,
    ``ad_sets``, ``ads``, ``ad_recommendations``."""

    SCHEDULED_EXTERNAL = "scheduled_external"
    """Independent cron job (e.g. ``run_mailerlite_etl_sync`` every 6 hours)
    that bypasses the tick scheduler."""

    WEBHOOK_INGESTED = "webhook_ingested"
    """Data does not come from this provider's pull. It is delivered by
    inbound webhooks (Manychat, Shopify, Mailerlite). The ``extract_metrics``
    method is a no-op pass-through so the scheduler can still include it in
    cache invalidation flows."""

    INTERNAL_DB = "internal_db"
    """Provider reads from our own database (no external API). Used by
    ``crm_internal``."""


class ProviderStatus(StrEnum):
    """Operational status of the provider in production."""

    PRODUCTION = "production"
    """Working end-to-end. Verified populating real rows recently."""

    PARTIAL = "partial"
    """Working but with documented limitations (sub-extractor failures,
    missing channel coverage, etc.)."""

    BROKEN = "broken"
    """Registered in PROVIDER_REGISTRY but currently failing in production.
    See ``known_issues``."""

    PASS_THROUGH = "pass_through"
    """By design returns an empty ExtractionResult. Data arrives via another
    path (webhook ingestion, internal DB)."""

    DEPRECATED = "deprecated"
    """Should not be used; kept for backwards compatibility."""


class AuthType(StrEnum):
    """How a provider authenticates against its external source."""

    OAUTH2_REFRESH = "oauth2_with_refresh"
    """Standard OAuth 2.0 with refresh token rotation."""

    LONG_LIVED_TOKEN = "long_lived_token"
    """Long-lived access token without refresh (Meta system user, Mailerlite
    API key, etc.)."""

    SHOPIFY_ADMIN_TOKEN = "shopify_admin_token"
    """Shopify Admin API token issued during the OAuth handshake."""

    API_KEY = "api_key"
    """Static API key passed in headers/query params."""

    INTERNAL = "internal"
    """No external auth — uses our own DB session."""


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class APIEndpoint:
    """An external HTTP endpoint that a provider hits during extraction."""

    description: str
    url_template: str
    docs_url: str | None = None


@dataclass(frozen=True)
class MetricMapping:
    """Maps a single metric a provider emits to its canonical catalog name.

    The ``canonical_name`` should match an entry in :mod:`metric_catalog` for
    metrics that are part of the public catalog. Provider-specific metrics
    that are not in the catalog (e.g. ``meta_video_p25``) are still listed
    here so the contract is exhaustive.
    """

    canonical_name: str
    api_field: str
    unit: str  # count | currency | percentage | seconds | json
    notes: str | None = None


@dataclass(frozen=True)
class ChannelOutput:
    """One channel slug a provider populates, with the metrics it emits.

    A provider can produce multiple ChannelOutput entries — for example,
    MetaProvider produces ``ig-organic`` and ``meta-ads`` (and ``fb-organic``).
    """

    channel_slug: str
    stage: str
    metrics: tuple[MetricMapping, ...]
    description: str = ""


@dataclass(frozen=True)
class ProviderContract:
    """Complete contract for one ETL provider."""

    # ── Identity ──
    provider_name: str
    """Name registered in :data:`PROVIDER_REGISTRY`. Must match
    ``BaseMetricsProvider.provider_name()`` for the class."""

    display_name: str
    """Human-friendly name for docs and the admin UI."""

    status: ProviderStatus

    # ── Code location ──
    module_path: str
    """Dotted import path of the provider module, e.g.
    ``src.modules.analytics.infrastructure.providers.meta_provider``."""

    class_name: str
    """Class name inside ``module_path``."""

    # ── Authentication ──
    auth_type: AuthType
    auth_provider: str
    """Human description of where the credentials come from. e.g.
    ``Meta Graph API (system user token)``."""

    required_credentials: tuple[str, ...]
    """Keys that must be present in the credentials dict passed to
    ``extract_metrics``. Used by tests + docs."""

    # ── Connection mapping ──
    serves_channel_types: tuple[str, ...]
    """The ``channel_type`` values from ``channel_connections`` that should
    resolve to this provider via ``CHANNEL_TYPE_TO_PROVIDERS``. Note: there
    is currently a bug in ``etl_service.run_all_providers`` that uses
    ``conn.channel_type`` directly as the provider name, so only the
    channel types that exactly match ``provider_name`` are picked up. See
    ``known_issues`` on individual providers."""

    # ── External APIs ──
    api_endpoints: tuple[APIEndpoint, ...]

    # ── Schedule / mode ──
    extraction_modes: tuple[ExtractionMode, ...]
    cron_schedule: str
    """Plain-language description of when this provider runs in production.
    e.g. ``Daily at 3am tenant-local time + on-demand initial-load``."""

    # ── Multi-stage ──
    is_multi_stage: bool
    stages_supported: tuple[str, ...]
    has_period_extraction: bool

    # ── Output ──
    channel_outputs: tuple[ChannelOutput, ...]
    storage_tables: tuple[str, ...]
    """Tables this provider's data lands in. Includes intermediate tables
    written by the pipeline (e.g. ``staging_metrics``)."""

    # ── Status info ──
    known_issues: tuple[str, ...] = ()
    last_verified: str = "unverified"
    notes: str = ""


# ---------------------------------------------------------------------------
# Storage targets reference
# ---------------------------------------------------------------------------


STORAGE_TABLES_DOC: dict[str, str] = {
    "staging_metrics": (
        "Raw extracted rows before deduplication & promotion to official. "
        "One row per (extraction_run, channel, metric, day). Wiped at the start "
        "of every run for that (tenant, provider) pair."
    ),
    "official_metrics": (
        "Authoritative daily metrics. Natural key: "
        "(tenant_id, provider, channel_slug, metric_name, metric_date). "
        "Upserted from staging via ON CONFLICT."
    ),
    "metric_aggregations": (
        "Pre-computed rollups: daily, weekly, monthly, quarterly, last_30_days. "
        "Replaced wholesale per (tenant, channel) at the end of each run."
    ),
    "period_metrics": (
        "NON_AGGREGABLE metrics (reach, users, frequency, repeat_customers, "
        "ig_accounts_engaged, meta_video_avg_watch_time) extracted per "
        "weekly/monthly/quarterly bucket. These cannot be summed across days."
    ),
    "extraction_runs": (
        "Audit log of every ETL invocation. Tracks status, duration, "
        "metrics_count, rows_extracted, sub_extractor_failures, "
        "rate_limit_headroom, period_start/end, extraction_type."
    ),
    "ad_campaigns": (
        "Meta Ads campaign hierarchy snapshot. Populated by ``run_campaign_sync`` (separate from metrics extraction)."
    ),
    "ad_sets": "Meta ad set hierarchy snapshot.",
    "ads": "Meta individual ads + creative snapshot.",
    "ad_recommendations": "Meta-suggested optimizations per object.",
    "channel_cost_settings": (
        "User-configured manual costs (e.g. agency fees). NOT populated by the ETL — written from the Connections UI."
    ),
    "journey_events": (
        "Customer event timeline. Populated by inbound webhooks "
        "(Shopify checkout/order, Manychat dm/comment, Mailerlite open/click). "
        "The ``crm_internal`` provider reads from this table for cold-contact "
        "metrics."
    ),
}


# ---------------------------------------------------------------------------
# Channel-type → provider mapping (intended)
# ---------------------------------------------------------------------------
#
# This is the mapping that ``etl_service.run_all_providers`` SHOULD use to
# resolve which provider handles each ``channel_connections.channel_type``
# value. As of 2026-04-11 the code uses ``conn.channel_type`` directly which
# silently drops every connection whose channel_type does not equal a
# provider name verbatim. Fixing this is in the post-deploy backlog.

CHANNEL_TYPE_TO_PROVIDERS: dict[str, tuple[str, ...]] = {
    "meta": ("meta",),
    "facebook_page": ("meta",),
    "instagram_account": ("meta",),
    "meta_ads_account": ("meta",),
    "meta_pixel": ("meta_pixel",),
    "google_analytics": ("google_analytics", "search_console"),
    "google_ads": ("google_ads",),
    "search_console": ("search_console",),
    "youtube": ("youtube",),
    "youtube_analytics": ("youtube",),
    "tiktok": ("tiktok",),
    "tiktok_ads": ("tiktok",),
    "shopify": ("shopify",),
    "mailerlite": ("mailerlite",),
    "mailchimp": ("mailerlite",),  # alias — same provider handles via different account
    "activecampaign": ("mailerlite",),
    "manychat": ("manychat",),
    # connection-only types with no metrics extraction (yet):
    # gmail, google_calendar, telegram, whatsapp, whatsapp_cloud
}


# ---------------------------------------------------------------------------
# Contract registry
# ---------------------------------------------------------------------------


_LAST_VERIFIED = "2026-04-11"
"""Date this contract was last hand-verified against production data and
provider source code."""


def _meta_contract() -> ProviderContract:
    return ProviderContract(
        provider_name="meta",
        display_name="Meta (Facebook + Instagram + Meta Ads)",
        status=ProviderStatus.PARTIAL,
        module_path="src.modules.analytics.infrastructure.providers.meta_provider",
        class_name="MetaProvider",
        auth_type=AuthType.LONG_LIVED_TOKEN,
        auth_provider="Meta Graph API (system user token)",
        required_credentials=(
            "access_token",
            "ads_account_id",  # numeric — used as act_{id}
            "instagram_business_account_id",  # optional, enables ig-organic
            "page_id",  # optional, enables fb-organic
        ),
        serves_channel_types=(
            "meta",
            "facebook_page",
            "instagram_account",
            "meta_ads_account",
        ),
        api_endpoints=(
            APIEndpoint(
                description="Meta Ads insights with day-level breakdown",
                url_template="https://graph.facebook.com/v24.0/act_{ads_account_id}/insights",
                docs_url="https://developers.facebook.com/docs/marketing-api/insights",
            ),
            APIEndpoint(
                description="Instagram organic insights (period=day, ≤30d chunks)",
                url_template="https://graph.facebook.com/v24.0/{ig_user_id}/insights",
                docs_url="https://developers.facebook.com/docs/instagram-api/reference/ig-user/insights",
            ),
            APIEndpoint(
                description="Instagram media count + profile metadata",
                url_template="https://graph.facebook.com/v24.0/{ig_user_id}",
            ),
            APIEndpoint(
                description="Facebook page insights (organic)",
                url_template="https://graph.facebook.com/v24.0/{page_id}/insights",
                docs_url="https://developers.facebook.com/docs/graph-api/reference/page/insights/",
            ),
        ),
        extraction_modes=(
            ExtractionMode.DAILY_ETL,
            ExtractionMode.INITIAL_LOAD,
            ExtractionMode.PERIOD_BACKFILL,
        ),
        cron_schedule=(
            "Daily at 03:00 tenant-local time via run_tick_scheduler. "
            "Period extraction also enqueued at week/month/quarter boundaries."
        ),
        is_multi_stage=False,
        stages_supported=("attraction",),
        has_period_extraction=True,
        channel_outputs=(
            ChannelOutput(
                channel_slug="meta-ads",
                stage="attraction",
                description="Paid Meta Ads at the ad-account level (act_{id})",
                metrics=(
                    MetricMapping("reach", "reach", "count"),
                    MetricMapping("impressions", "impressions", "count"),
                    MetricMapping("clicks", "clicks", "count"),
                    MetricMapping("spend", "spend", "currency"),
                    MetricMapping("frequency", "frequency", "count"),
                    MetricMapping("ctr", "ctr", "percentage"),
                    MetricMapping("cpm", "cpm", "currency"),
                    MetricMapping("cpc", "cpc", "currency"),
                    MetricMapping("meta_cpp", "cpp", "currency"),
                    MetricMapping("conversions", "actions[purchase]", "count"),
                    MetricMapping(
                        "meta_conversion_value",
                        "action_values[purchase]",
                        "currency",
                    ),
                    MetricMapping("meta_purchase_roas", "purchase_roas", "count"),
                    MetricMapping(
                        "meta_inline_link_clicks",
                        "inline_link_clicks",
                        "count",
                    ),
                    MetricMapping("meta_outbound_clicks", "outbound_clicks", "count"),
                    MetricMapping("meta_link_clicks", "actions[link_click]", "count"),
                    MetricMapping(
                        "meta_landing_page_views",
                        "actions[landing_page_view]",
                        "count",
                    ),
                    MetricMapping(
                        "meta_post_engagement",
                        "actions[post_engagement]",
                        "count",
                    ),
                    MetricMapping(
                        "meta_page_engagement",
                        "actions[page_engagement]",
                        "count",
                    ),
                    MetricMapping(
                        "meta_conversations_started",
                        "actions[onsite_conversion.messaging_conversation_started_7d]",
                        "count",
                    ),
                    MetricMapping(
                        "meta_view_content",
                        "actions[offsite_conversion.fb_pixel_view_content]",
                        "count",
                    ),
                    MetricMapping(
                        "meta_add_to_cart",
                        "actions[offsite_conversion.fb_pixel_add_to_cart]",
                        "count",
                    ),
                    MetricMapping(
                        "meta_initiate_checkout",
                        "actions[offsite_conversion.fb_pixel_initiate_checkout]",
                        "count",
                    ),
                    MetricMapping(
                        "meta_cost_per_link_click",
                        "cost_per_inline_link_click",
                        "currency",
                    ),
                    MetricMapping(
                        "meta_cost_per_outbound_click",
                        "cost_per_outbound_click",
                        "currency",
                    ),
                    MetricMapping("meta_video_views", "actions[video_view]", "count"),
                    MetricMapping(
                        "meta_video_p25",
                        "video_p25_watched_actions",
                        "count",
                    ),
                    MetricMapping(
                        "meta_video_p50",
                        "video_p50_watched_actions",
                        "count",
                    ),
                    MetricMapping(
                        "meta_video_p75",
                        "video_p75_watched_actions",
                        "count",
                    ),
                    MetricMapping(
                        "meta_video_p100",
                        "video_p100_watched_actions",
                        "count",
                    ),
                    MetricMapping(
                        "meta_video_30sec",
                        "video_30_sec_watched_actions",
                        "count",
                    ),
                    MetricMapping(
                        "meta_video_avg_watch_time",
                        "video_avg_time_watched_actions",
                        "seconds",
                    ),
                    MetricMapping(
                        "meta_leads",
                        "actions[lead | offsite_conversion.fb_pixel_lead]",
                        "count",
                    ),
                    MetricMapping(
                        "meta_registrations",
                        "actions[offsite_conversion.fb_pixel_complete_registration]",
                        "count",
                    ),
                    MetricMapping(
                        "meta_search_actions",
                        "actions[offsite_conversion.fb_pixel_search]",
                        "count",
                    ),
                    MetricMapping(
                        "meta_cost_per_lead",
                        "derived: spend / meta_leads",
                        "currency",
                    ),
                    MetricMapping(
                        "meta_cost_per_purchase",
                        "derived: spend / conversions",
                        "currency",
                    ),
                    MetricMapping(
                        "meta_impressions_by_age",
                        "/insights?breakdown=age",
                        "json",
                        notes="Stored in extra.breakdowns",
                    ),
                    MetricMapping(
                        "meta_impressions_by_gender",
                        "/insights?breakdown=gender",
                        "json",
                    ),
                    MetricMapping(
                        "meta_impressions_by_placement",
                        "/insights?breakdown=publisher_platform,platform_position",
                        "json",
                    ),
                    MetricMapping(
                        "meta_reach_by_age",
                        "/insights?breakdown=age",
                        "json",
                    ),
                    MetricMapping(
                        "meta_reach_by_gender",
                        "/insights?breakdown=gender",
                        "json",
                    ),
                    MetricMapping(
                        "meta_reach_by_placement",
                        "/insights?breakdown=publisher_platform,platform_position",
                        "json",
                    ),
                    MetricMapping(
                        "meta_spend_by_age",
                        "/insights?breakdown=age",
                        "json",
                    ),
                    MetricMapping(
                        "meta_spend_by_gender",
                        "/insights?breakdown=gender",
                        "json",
                    ),
                    MetricMapping(
                        "meta_spend_by_placement",
                        "/insights?breakdown=publisher_platform,platform_position",
                        "json",
                    ),
                ),
            ),
            ChannelOutput(
                channel_slug="ig-organic",
                stage="attraction",
                description="Instagram organic reach + engagement (period=day)",
                metrics=(
                    MetricMapping("reach", "reach", "count"),
                    MetricMapping("ig_views", "views", "count"),
                    MetricMapping("ig_likes", "likes", "count"),
                    MetricMapping("ig_comments", "comments", "count"),
                    MetricMapping("ig_shares", "shares", "count"),
                    MetricMapping("ig_saves", "saved", "count"),
                    MetricMapping("ig_replies", "replies", "count"),
                    MetricMapping("ig_reposts", "reposts", "count"),
                    MetricMapping("ig_accounts_engaged", "accounts_engaged", "count"),
                    MetricMapping(
                        "ig_profile_links_taps",
                        "profile_links_taps",
                        "count",
                    ),
                    MetricMapping("ig_followers_count", "followers_count", "count"),
                    MetricMapping(
                        "ig_follows_gained",
                        "follows_and_unfollows[follower]",
                        "count",
                    ),
                    MetricMapping(
                        "ig_follows_lost",
                        "follows_and_unfollows[non_follower]",
                        "count",
                    ),
                    MetricMapping(
                        "ig_follows_and_unfollows",
                        "follows_and_unfollows",
                        "count",
                    ),
                    MetricMapping("ig_media_count", "media_count", "count"),
                    MetricMapping("total_interactions", "total_interactions", "count"),
                    MetricMapping(
                        "engagement",
                        "derived: likes + comments + saves + shares",
                        "count",
                    ),
                    MetricMapping(
                        "ig_follower_demographics",
                        "/insights?metric=follower_demographics",
                        "json",
                    ),
                    MetricMapping(
                        "ig_engaged_audience_demographics",
                        "/insights?metric=engaged_audience_demographics",
                        "json",
                    ),
                ),
            ),
            ChannelOutput(
                channel_slug="fb-organic",
                stage="attraction",
                description=(
                    "Facebook page organic reach + engagement. NOTE: not "
                    "currently populated for Visionarias because the page "
                    "credentials are missing — verified empty in production "
                    "as of 2026-04-11."
                ),
                metrics=(
                    MetricMapping("fb_page_reach", "page_impressions_unique", "count"),
                    MetricMapping("fb_page_engagement", "page_engaged_users", "count"),
                ),
            ),
        ),
        storage_tables=(
            "staging_metrics",
            "official_metrics",
            "metric_aggregations",
            "period_metrics",
        ),
        known_issues=(
            "Period extraction for Instagram returns HTTP 400 when calling "
            "/insights with period=week for {reach, accounts_engaged}. The "
            "Meta Ads side of period extraction works fine. Tracked in audit "
            "report 2026-04-11.",
            "fb-organic only emits metrics if credentials.page_id is set; "
            "extract_period_metrics does not currently emit FB organic.",
        ),
        last_verified=_LAST_VERIFIED,
        notes=(
            "Extracts daily ad-level metrics with time_increment=1 to avoid "
            "the contamination bug where a single aggregated row polluted the "
            "last day of the period (Visionarias incident, see "
            "PeriodAggregateError docstring)."
        ),
    )


def _meta_pixel_contract() -> ProviderContract:
    return ProviderContract(
        provider_name="meta_pixel",
        display_name="Meta Pixel (server-side conversion tracking)",
        status=ProviderStatus.PARTIAL,
        module_path="src.modules.analytics.infrastructure.providers.meta_pixel_provider",
        class_name="MetaPixelProvider",
        auth_type=AuthType.LONG_LIVED_TOKEN,
        auth_provider="Meta Marketing API (pixel scope)",
        required_credentials=("asset_id", "access_token"),
        serves_channel_types=("meta_pixel",),
        api_endpoints=(
            APIEndpoint(
                description="Pixel event aggregation (PageView, ViewContent, Lead, AddToCart, Purchase)",
                url_template=(
                    "https://graph.facebook.com/v21.0/{pixel_id}/stats"
                    "?aggregation=event&event=PageView,ViewContent,Lead,AddToCart,Purchase"
                ),
                docs_url="https://developers.facebook.com/docs/marketing-api/reference/ads-pixel/stats/",
            ),
        ),
        extraction_modes=(ExtractionMode.DAILY_ETL, ExtractionMode.INITIAL_LOAD),
        cron_schedule="Daily at 03:00 tenant-local time (when meta_pixel connection exists)",
        is_multi_stage=False,
        stages_supported=("attraction",),
        has_period_extraction=False,
        channel_outputs=(
            ChannelOutput(
                channel_slug="meta-pixel",
                stage="attraction",
                description=(
                    "Pixel event counts aggregated to a single day per call. "
                    "Note: this provider currently emits one row per metric "
                    "with date=end_date even when called over a multi-day "
                    "range — granularity below 1 day is not preserved."
                ),
                metrics=(
                    MetricMapping("pixel_pageviews", "PageView", "count"),
                    MetricMapping("pixel_view_content", "ViewContent", "count"),
                    MetricMapping("pixel_leads", "Lead", "count"),
                    MetricMapping("pixel_add_to_cart", "AddToCart", "count"),
                    MetricMapping("pixel_purchases", "Purchase", "count"),
                ),
            ),
        ),
        storage_tables=("staging_metrics", "official_metrics", "metric_aggregations"),
        known_issues=(
            "Verified empty in production for Visionarias as of 2026-04-11 "
            "even though meta_pixel connection exists. Likely root cause: "
            "etl_service.run_all_providers passes channel_type=='meta_pixel' "
            "but the provider expects credentials.asset_id which is sourced "
            "from a different connection field. See ETL audit 2026-04-11.",
        ),
        last_verified=_LAST_VERIFIED,
    )


def _google_analytics_contract() -> ProviderContract:
    return ProviderContract(
        provider_name="google_analytics",
        display_name="Google Analytics 4",
        status=ProviderStatus.BROKEN,
        module_path="src.modules.analytics.infrastructure.providers.google_analytics_provider",
        class_name="GoogleAnalyticsProvider",
        auth_type=AuthType.OAUTH2_REFRESH,
        auth_provider="Google OAuth (Analytics Data API scope)",
        required_credentials=(
            "client_id",
            "client_secret",
            "refresh_token",
            "token",
            "property_id",
        ),
        serves_channel_types=("google_analytics",),
        api_endpoints=(
            APIEndpoint(
                description="GA4 Data API runReport (sessions, users, events)",
                url_template="https://analyticsdata.googleapis.com/v1beta/properties/{property_id}:runReport",
                docs_url="https://developers.google.com/analytics/devguides/reporting/data/v1",
            ),
        ),
        extraction_modes=(
            ExtractionMode.DAILY_ETL,
            ExtractionMode.INITIAL_LOAD,
            ExtractionMode.PERIOD_BACKFILL,
        ),
        cron_schedule="Daily at 03:00 tenant-local time + period boundaries",
        is_multi_stage=False,
        stages_supported=("attraction",),
        has_period_extraction=True,
        channel_outputs=(
            ChannelOutput(
                channel_slug="website-total",
                stage="attraction",
                description="Site-wide aggregate (no source/medium dimension)",
                metrics=(
                    MetricMapping("sessions", "sessions", "count"),
                    MetricMapping("users", "totalUsers", "count"),
                    MetricMapping("newUsers", "newUsers", "count"),
                    MetricMapping("activeUsers", "activeUsers", "count"),
                    MetricMapping("bounceRate", "bounceRate", "percentage"),
                    MetricMapping("engagedSessions", "engagedSessions", "count"),
                    MetricMapping("engagementRate", "engagementRate", "percentage"),
                    MetricMapping("screenPageViews", "screenPageViews", "count"),
                    MetricMapping(
                        "averageSessionDuration",
                        "averageSessionDuration",
                        "seconds",
                    ),
                    MetricMapping("conversions", "conversions", "count"),
                    MetricMapping(
                        "top_pages",
                        "runReport(dimensions=[pagePath])",
                        "json",
                        notes="Top 20 pages by pageviews, stored in extra.pages",
                    ),
                    MetricMapping(
                        "traffic_sources",
                        "runReport(dimensions=[sessionSource, sessionMedium])",
                        "json",
                        notes="Source/medium breakdown, stored in extra.sources",
                    ),
                    MetricMapping(
                        "device_split",
                        "runReport(dimensions=[deviceCategory])",
                        "json",
                        notes="desktop / mobile / tablet split, stored in extra",
                    ),
                ),
            ),
            ChannelOutput(
                channel_slug="google-organic",
                stage="attraction",
                description="Sessions from source=google AND medium=organic",
                metrics=(
                    MetricMapping("sessions", "sessions", "count"),
                    MetricMapping("users", "totalUsers", "count"),
                ),
            ),
            ChannelOutput(
                channel_slug="direct",
                stage="attraction",
                description="Sessions from (direct) / (none)",
                metrics=(
                    MetricMapping("sessions", "sessions", "count"),
                    MetricMapping("users", "totalUsers", "count"),
                ),
            ),
            ChannelOutput(
                channel_slug="ai-search-organic",
                stage="attraction",
                description=(
                    "Sessions referred by AI search engines: perplexity.ai, "
                    "chatgpt.com, claude.ai, copilot.microsoft.com, "
                    "gemini.google.com, you.com, phind.com"
                ),
                metrics=(
                    MetricMapping("sessions", "sessions", "count"),
                    MetricMapping("users", "totalUsers", "count"),
                ),
            ),
        ),
        storage_tables=(
            "staging_metrics",
            "official_metrics",
            "metric_aggregations",
            "period_metrics",
        ),
        known_issues=(
            "Production token for Visionarias is invalid_grant (expired) as "
            "of 2026-04-11. The provider raises ConnectionRevokedError "
            "for RefreshError/TransportError but no UI surface notifies the "
            "user — they must hit the /etl/status endpoint to discover this.",
        ),
        last_verified=_LAST_VERIFIED,
    )


def _google_ads_contract() -> ProviderContract:
    return ProviderContract(
        provider_name="google_ads",
        display_name="Google Ads + YouTube Ads",
        status=ProviderStatus.PRODUCTION,
        module_path="src.modules.analytics.infrastructure.providers.google_ads_provider",
        class_name="GoogleAdsProvider",
        auth_type=AuthType.OAUTH2_REFRESH,
        auth_provider="Google OAuth (Google Ads scope) + developer token",
        required_credentials=(
            "client_id",
            "client_secret",
            "refresh_token",
            "customer_id",
            "developer_token",  # may also come from GOOGLE_ADS_DEVELOPER_TOKEN env
        ),
        serves_channel_types=("google_ads",),
        api_endpoints=(
            APIEndpoint(
                description="Google Ads API GAQL query (campaign metrics)",
                url_template="https://googleads.googleapis.com/v17/customers/{customer_id}/googleAds:search",
                docs_url="https://developers.google.com/google-ads/api/docs/query/overview",
            ),
        ),
        extraction_modes=(ExtractionMode.DAILY_ETL, ExtractionMode.INITIAL_LOAD),
        cron_schedule="Daily at 03:00 tenant-local time",
        is_multi_stage=False,
        stages_supported=("attraction", "nurturing"),
        has_period_extraction=False,
        channel_outputs=(
            ChannelOutput(
                channel_slug="google-ads",
                stage="attraction",
                description="Search/Display/Shopping campaigns (NON-VIDEO)",
                metrics=(
                    MetricMapping("impressions", "metrics.impressions", "count"),
                    MetricMapping("clicks", "metrics.clicks", "count"),
                    MetricMapping("conversions", "metrics.conversions", "count"),
                    MetricMapping(
                        "spend",
                        "metrics.cost_micros",
                        "currency",
                        notes="Divide by 1_000_000 (cost_micros)",
                    ),
                    MetricMapping(
                        "conversion_value",
                        "metrics.conversions_value",
                        "currency",
                    ),
                    MetricMapping("ctr", "derived: clicks/impressions", "percentage"),
                    MetricMapping("cpc", "derived: spend/clicks", "currency"),
                    MetricMapping(
                        "search_terms",
                        "search_terms_view",
                        "json",
                        notes="JSON snapshot of top 20 search terms",
                    ),
                ),
            ),
            ChannelOutput(
                channel_slug="yt-ads",
                stage="attraction",
                description="VIDEO campaigns (YouTube Ads) routed to a separate slug",
                metrics=(
                    MetricMapping("impressions", "metrics.impressions", "count"),
                    MetricMapping("clicks", "metrics.clicks", "count"),
                    MetricMapping("conversions", "metrics.conversions", "count"),
                    MetricMapping("spend", "metrics.cost_micros", "currency"),
                ),
            ),
            ChannelOutput(
                channel_slug="google-retargeting",
                stage="nurturing",
                description=(
                    "Best-effort: filters base GAQL query rows by campaign "
                    "name containing 'remarketing' or 'retargeting'."
                ),
                metrics=(
                    MetricMapping("impressions", "metrics.impressions", "count"),
                    MetricMapping("clicks", "metrics.clicks", "count"),
                    MetricMapping("spend", "metrics.cost_micros", "currency"),
                    MetricMapping("ctr", "derived", "percentage"),
                    MetricMapping("cpc", "derived", "currency"),
                ),
            ),
        ),
        storage_tables=(
            "staging_metrics",
            "official_metrics",
            "metric_aggregations",
        ),
        known_issues=(
            "Currency resolution falls back to credentials.currency then USD. "
            "If neither is set, spend will be reported in USD even when the "
            "ad account operates in another currency."
        ),
        last_verified=_LAST_VERIFIED,
    )


def _search_console_contract() -> ProviderContract:
    return ProviderContract(
        provider_name="search_console",
        display_name="Google Search Console",
        status=ProviderStatus.BROKEN,
        module_path="src.modules.analytics.infrastructure.providers.search_console_provider",
        class_name="SearchConsoleProvider",
        auth_type=AuthType.OAUTH2_REFRESH,
        auth_provider="Google OAuth (Search Console scope, shares creds with GA)",
        required_credentials=(
            "client_id",
            "client_secret",
            "refresh_token",
            "site_url",
        ),
        serves_channel_types=("search_console",),
        api_endpoints=(
            APIEndpoint(
                description="Search Console searchAnalytics.query",
                url_template="https://searchconsole.googleapis.com/webmasters/v3/sites/{site_url}/searchAnalytics/query",
                docs_url="https://developers.google.com/webmaster-tools/v1/searchanalytics/query",
            ),
        ),
        extraction_modes=(ExtractionMode.DAILY_ETL, ExtractionMode.INITIAL_LOAD),
        cron_schedule="Daily at 03:00 tenant-local time",
        is_multi_stage=False,
        stages_supported=("attraction",),
        has_period_extraction=False,
        channel_outputs=(
            ChannelOutput(
                channel_slug="search-console",
                stage="attraction",
                description="Aggregate impressions/clicks + top 20 query JSON snapshot",
                metrics=(
                    MetricMapping("impressions", "impressions", "count"),
                    MetricMapping("clicks", "clicks", "count"),
                    MetricMapping("ctr", "ctr", "percentage"),
                    MetricMapping("avg_position", "position", "count"),
                    MetricMapping(
                        "top_queries",
                        "rows[query]",
                        "json",
                        notes="Stored in extra.queries (top 20 by clicks)",
                    ),
                ),
            ),
        ),
        storage_tables=("staging_metrics", "official_metrics", "metric_aggregations"),
        known_issues=(
            "Shares OAuth credentials with google_analytics. When the GA "
            "token is invalid_grant, search_console fails too because the "
            "refresh token is the same.",
            "Production for Visionarias is currently failing for the same reason as GA (expired token, 2026-04-11).",
        ),
        last_verified=_LAST_VERIFIED,
    )


def _youtube_contract() -> ProviderContract:
    return ProviderContract(
        provider_name="youtube",
        display_name="YouTube Analytics",
        status=ProviderStatus.PRODUCTION,
        module_path="src.modules.analytics.infrastructure.providers.youtube_provider",
        class_name="YouTubeProvider",
        auth_type=AuthType.OAUTH2_REFRESH,
        auth_provider="Google OAuth (YouTube Analytics scope)",
        required_credentials=("client_id", "client_secret", "refresh_token", "token"),
        serves_channel_types=("youtube", "youtube_analytics"),
        api_endpoints=(
            APIEndpoint(
                description="YouTube Analytics API v2 reports.query",
                url_template="https://youtubeanalytics.googleapis.com/v2/reports",
                docs_url="https://developers.google.com/youtube/analytics/reference/reports/query",
            ),
        ),
        extraction_modes=(ExtractionMode.DAILY_ETL, ExtractionMode.INITIAL_LOAD),
        cron_schedule="Daily at 03:00 tenant-local time",
        is_multi_stage=False,
        stages_supported=("attraction",),
        has_period_extraction=False,
        channel_outputs=(
            ChannelOutput(
                channel_slug="yt-organic",
                stage="attraction",
                description="Channel-level overview + card/end-screen metrics",
                metrics=(
                    MetricMapping("views", "views", "count"),
                    MetricMapping(
                        "watch_time_minutes",
                        "estimatedMinutesWatched",
                        "count",
                    ),
                    MetricMapping(
                        "avg_view_duration",
                        "averageViewDuration",
                        "seconds",
                    ),
                    MetricMapping(
                        "avg_view_percentage",
                        "averageViewPercentage",
                        "percentage",
                    ),
                    MetricMapping("subscribers_gained", "subscribersGained", "count"),
                    MetricMapping("subscribers_lost", "subscribersLost", "count"),
                    MetricMapping("comments", "comments", "count"),
                    MetricMapping("shares", "shares", "count"),
                    MetricMapping(
                        "engagement",
                        "derived: likes + dislikes",
                        "count",
                        notes="Computed; raw likes/dislikes stored in extra",
                    ),
                    MetricMapping("card_clicks", "cardClicks", "count"),
                    MetricMapping("card_impressions", "cardImpressions", "count"),
                    MetricMapping(
                        "end_screen_clicks",
                        "endScreenElementClicks",
                        "count",
                    ),
                    MetricMapping(
                        "end_screen_impressions",
                        "endScreenElementImpressions",
                        "count",
                    ),
                    MetricMapping(
                        "card_click_rate",
                        "derived: card_clicks/card_impressions",
                        "percentage",
                    ),
                    MetricMapping(
                        "end_screen_click_rate",
                        "derived: end_clicks/end_impressions",
                        "percentage",
                    ),
                ),
            ),
        ),
        storage_tables=("staging_metrics", "official_metrics", "metric_aggregations"),
        known_issues=(),
        last_verified=_LAST_VERIFIED,
    )


def _tiktok_contract() -> ProviderContract:
    return ProviderContract(
        provider_name="tiktok",
        display_name="TikTok (organic + ads)",
        status=ProviderStatus.PRODUCTION,
        module_path="src.modules.analytics.infrastructure.providers.tiktok_provider",
        class_name="TikTokProvider",
        auth_type=AuthType.OAUTH2_REFRESH,
        auth_provider="TikTok Business OAuth",
        required_credentials=("access_token", "advertiser_id"),
        serves_channel_types=("tiktok", "tiktok_ads"),
        api_endpoints=(
            APIEndpoint(
                description="TikTok Business organic insights",
                url_template="https://business-api.tiktok.com/open_api/v1.3/...",
                docs_url="https://business-api.tiktok.com/portal/docs",
            ),
            APIEndpoint(
                description="TikTok Ads report (reach, clicks, conversions, spend)",
                url_template="https://business-api.tiktok.com/open_api/v1.3/report/integrated/get/",
            ),
        ),
        extraction_modes=(ExtractionMode.DAILY_ETL, ExtractionMode.INITIAL_LOAD),
        cron_schedule="Daily at 03:00 tenant-local time",
        is_multi_stage=False,
        stages_supported=("attraction", "nurturing"),
        has_period_extraction=False,
        channel_outputs=(
            ChannelOutput(
                channel_slug="tiktok-organic",
                stage="attraction",
                description="Aggregated organic videos (views, engagement)",
                metrics=(
                    MetricMapping("video_views", "video_views", "count"),
                    MetricMapping(
                        "engagement",
                        "derived: likes + comments + shares",
                        "count",
                    ),
                ),
            ),
            ChannelOutput(
                channel_slug="tiktok-ads",
                stage="attraction",
                description="Paid TikTok Ads aggregated across campaigns",
                metrics=(
                    MetricMapping("reach", "reach", "count"),
                    MetricMapping("clicks", "clicks", "count"),
                    MetricMapping("conversions", "conversion", "count"),
                    MetricMapping("spend", "spend", "currency"),
                ),
            ),
            ChannelOutput(
                channel_slug="tiktok-retargeting",
                stage="nurturing",
                description=(
                    "Best-effort retargeting: filters ads report by campaign "
                    "name containing 'retargeting' or 'remarketing'."
                ),
                metrics=(
                    MetricMapping("reach", "reach", "count"),
                    MetricMapping("clicks", "clicks", "count"),
                    MetricMapping("spend", "spend", "currency"),
                ),
            ),
        ),
        storage_tables=("staging_metrics", "official_metrics", "metric_aggregations"),
        known_issues=(
            "Retargeting detection uses substring match on campaign name "
            "instead of TikTok's audience_type filter (TODO in source).",
        ),
        last_verified=_LAST_VERIFIED,
    )


def _shopify_contract() -> ProviderContract:
    return ProviderContract(
        provider_name="shopify",
        display_name="Shopify (orders + checkouts)",
        status=ProviderStatus.PRODUCTION,
        module_path="src.modules.analytics.infrastructure.providers.shopify_provider",
        class_name="ShopifyProvider",
        auth_type=AuthType.SHOPIFY_ADMIN_TOKEN,
        auth_provider="Shopify Admin API token",
        required_credentials=(
            "access_token",
            "shop_domain",  # also accepts shop_url
            "shop_currency",  # optional, defaults USD
        ),
        serves_channel_types=("shopify",),
        api_endpoints=(
            APIEndpoint(
                description="Orders REST API (sales stage)",
                url_template="https://{shop_domain}/admin/api/2026-01/orders.json",
                docs_url="https://shopify.dev/docs/api/admin-rest/2026-01/resources/order",
            ),
            APIEndpoint(
                description="Checkouts REST API (opportunity stage)",
                url_template="https://{shop_domain}/admin/api/2026-01/checkouts.json",
                docs_url="https://shopify.dev/docs/api/admin-rest/2026-01/resources/abandoned-checkouts",
            ),
        ),
        extraction_modes=(
            ExtractionMode.DAILY_ETL,
            ExtractionMode.INITIAL_LOAD,
            ExtractionMode.PERIOD_BACKFILL,
        ),
        cron_schedule="Daily at 03:00 tenant-local time + period boundaries",
        is_multi_stage=True,
        stages_supported=("opportunity", "sales"),
        has_period_extraction=True,
        channel_outputs=(
            ChannelOutput(
                channel_slug="shopify",
                stage="sales",
                description="Order-level revenue, refunds, AOV, units, repeat customers",
                metrics=(
                    MetricMapping("revenue", "total_price (sum)", "currency"),
                    MetricMapping("net_sales", "subtotal_price (sum)", "currency"),
                    MetricMapping("order_count", "count(orders)", "count"),
                    MetricMapping("units_sold", "line_items.quantity (sum)", "count"),
                    MetricMapping(
                        "avg_order_value",
                        "derived: revenue/orders",
                        "currency",
                    ),
                    MetricMapping("refund_count", "count(refunds)", "count"),
                    MetricMapping("refund_amount", "refunds.amount (sum)", "currency"),
                    MetricMapping(
                        "total_discounts",
                        "total_discounts (sum)",
                        "currency",
                    ),
                    MetricMapping("total_tax", "total_tax (sum)", "currency"),
                    MetricMapping(
                        "shipping_revenue",
                        "total_shipping_price_set",
                        "currency",
                    ),
                    MetricMapping(
                        "discount_usage_count",
                        "count(discount_codes)",
                        "count",
                    ),
                    MetricMapping(
                        "repeat_customers",
                        "derived: customers with >1 order in period",
                        "count",
                        notes="Only emitted by extract_period_metrics (not daily)",
                    ),
                ),
            ),
            ChannelOutput(
                channel_slug="abandoned-cart",
                stage="opportunity",
                description="Checkouts with abandoned_checkout_url and no completed_at",
                metrics=(
                    MetricMapping("count", "count(abandoned)", "count"),
                    MetricMapping("value", "abandoned.total_price (sum)", "currency"),
                    MetricMapping(
                        "abandonment_rate",
                        "derived: abandoned/(abandoned+completed)",
                        "percentage",
                    ),
                ),
            ),
            ChannelOutput(
                channel_slug="checkout-init",
                stage="opportunity",
                description="All checkouts initiated (abandoned + completed)",
                metrics=(
                    MetricMapping("count", "count(checkouts)", "count"),
                    MetricMapping("value", "checkouts.total_price (sum)", "currency"),
                ),
            ),
        ),
        storage_tables=(
            "staging_metrics",
            "official_metrics",
            "metric_aggregations",
            "period_metrics",
            "journey_events",  # checkout_initiated, checkout_completed via webhooks
        ),
        known_issues=(),
        last_verified=_LAST_VERIFIED,
        notes=(
            "Multi-stage provider: PROVIDER_STAGES['shopify'] = "
            "['opportunity', 'sales']. extract_metrics dispatches by stage "
            "and emits different channels per stage."
        ),
    )


def _mailerlite_contract() -> ProviderContract:
    return ProviderContract(
        provider_name="mailerlite",
        display_name="MailerLite (email marketing — multi-stage)",
        status=ProviderStatus.PRODUCTION,
        module_path="src.modules.analytics.infrastructure.providers.mailerlite_provider",
        class_name="MailerLiteProvider",
        auth_type=AuthType.API_KEY,
        auth_provider="MailerLite API key (Bearer token)",
        required_credentials=("api_key",),
        serves_channel_types=("mailerlite", "mailchimp", "activecampaign"),
        api_endpoints=(
            APIEndpoint(
                description="MailerLite forms list",
                url_template="https://connect.mailerlite.com/api/forms",
            ),
            APIEndpoint(
                description="MailerLite subscribers list (paginated)",
                url_template="https://connect.mailerlite.com/api/subscribers",
            ),
            APIEndpoint(
                description="MailerLite campaigns list with stats",
                url_template="https://connect.mailerlite.com/api/campaigns",
            ),
            APIEndpoint(
                description="MailerLite automations list with stats",
                url_template="https://connect.mailerlite.com/api/automations",
            ),
        ),
        extraction_modes=(
            ExtractionMode.DAILY_ETL,
            ExtractionMode.INITIAL_LOAD,
            ExtractionMode.SCHEDULED_EXTERNAL,
        ),
        cron_schedule=(
            "Daily at 03:00 tenant-local time PLUS run_mailerlite_etl_sync every 6 hours at minute 15 (UTC)."
        ),
        is_multi_stage=True,
        stages_supported=(
            "capture",
            "nurture",
            "opportunity",
            "delivery",
            "adoption",
            "retention",
            "expansion",
            "evangelization",
        ),
        has_period_extraction=False,
        channel_outputs=(
            ChannelOutput(
                channel_slug="email-capture",
                stage="capture",
                description="Forms + subscriber growth (capture stage)",
                metrics=(
                    MetricMapping("active_subscribers", "subscribers.count", "count"),
                    MetricMapping(
                        "new_subscribers",
                        "subscribers.created_today",
                        "count",
                    ),
                    MetricMapping("form_conversions", "forms.stats.converted", "count"),
                    MetricMapping(
                        "form_conversion_rate",
                        "derived: form.converted / form.viewed",
                        "percentage",
                    ),
                ),
            ),
            ChannelOutput(
                channel_slug="email-nurture",
                stage="nurture",
                description="Newsletter campaigns classified as nurture",
                metrics=(
                    MetricMapping("emails_sent", "campaign.stats.sent", "count"),
                    MetricMapping("opens_count", "campaign.stats.opens_count", "count"),
                    MetricMapping(
                        "clicks_count",
                        "campaign.stats.clicks_count",
                        "count",
                    ),
                    MetricMapping(
                        "unique_opens",
                        "campaign.stats.unique_opens_count",
                        "count",
                    ),
                    MetricMapping(
                        "unique_clicks",
                        "campaign.stats.unique_clicks_count",
                        "count",
                    ),
                    MetricMapping(
                        "open_rate",
                        "campaign.stats.open_rate",
                        "percentage",
                    ),
                    MetricMapping(
                        "click_rate",
                        "campaign.stats.click_rate",
                        "percentage",
                    ),
                    MetricMapping(
                        "click_to_open_rate",
                        "campaign.stats.click_to_open_rate",
                        "percentage",
                    ),
                    MetricMapping(
                        "hard_bounces",
                        "campaign.stats.hard_bounces_count",
                        "count",
                    ),
                    MetricMapping(
                        "soft_bounces",
                        "campaign.stats.soft_bounces_count",
                        "count",
                    ),
                    MetricMapping(
                        "bounce_rate",
                        "derived: (hard+soft)/sent",
                        "percentage",
                    ),
                    MetricMapping(
                        "unsubscribes",
                        "campaign.stats.unsubscribes_count",
                        "count",
                    ),
                    MetricMapping(
                        "unsubscribe_rate",
                        "derived: unsubscribes/sent",
                        "percentage",
                    ),
                    MetricMapping("spam_reports", "campaign.stats.spam_count", "count"),
                    MetricMapping("forwards", "campaign.stats.forwards_count", "count"),
                ),
            ),
            ChannelOutput(
                channel_slug="email-launch",
                stage="opportunity",
                description="Launch campaigns (campaign type=lanzamiento)",
                metrics=(
                    MetricMapping("emails_sent", "campaign.stats.sent", "count"),
                    MetricMapping(
                        "click_rate",
                        "campaign.stats.click_rate",
                        "percentage",
                    ),
                ),
            ),
            ChannelOutput(
                channel_slug="email-delivery",
                stage="delivery",
                description="Onboarding/delivery automation flows",
                metrics=(
                    MetricMapping(
                        "automation_completed",
                        "automation.stats.completed",
                        "count",
                    ),
                ),
            ),
            ChannelOutput(
                channel_slug="email-onboarding",
                stage="adoption",
                description="Adoption automation flows",
                metrics=(
                    MetricMapping(
                        "automation_completed",
                        "automation.stats.completed",
                        "count",
                    ),
                ),
            ),
            ChannelOutput(
                channel_slug="email-retention",
                stage="retention",
                description="Retention campaigns + reactivation derived metric",
                metrics=(
                    MetricMapping("emails_sent", "campaign.stats.sent", "count"),
                    MetricMapping(
                        "reactivation_rate",
                        "derived: reactivated / churned",
                        "percentage",
                    ),
                ),
            ),
            ChannelOutput(
                channel_slug="email-upsell",
                stage="expansion",
                description="Upsell / expansion campaigns",
                metrics=(MetricMapping("emails_sent", "campaign.stats.sent", "count"),),
            ),
            ChannelOutput(
                channel_slug="email-referral",
                stage="evangelization",
                description="Referral / evangelization campaigns",
                metrics=(MetricMapping("emails_sent", "campaign.stats.sent", "count"),),
            ),
        ),
        storage_tables=("staging_metrics", "official_metrics", "metric_aggregations"),
        known_issues=(
            "Multi-stage orchestration is sequential within run_extraction. "
            "If stage A passes and stage B fails, the run row reports the "
            "status of B and the data from A is not rolled back. There is no "
            "single run that summarizes all stages.",
            "Campaign-type classification is keyword-based (Spanish + English) "
            "and falls back to 'attraction' for unknown names.",
        ),
        last_verified=_LAST_VERIFIED,
    )


def _manychat_contract() -> ProviderContract:
    return ProviderContract(
        provider_name="manychat",
        display_name="Manychat (webhook-fed pass-through)",
        status=ProviderStatus.PASS_THROUGH,
        module_path="src.modules.analytics.infrastructure.providers.manychat_provider",
        class_name="ManyChatProvider",
        auth_type=AuthType.INTERNAL,
        auth_provider="None — data arrives via webhooks",
        required_credentials=(),
        serves_channel_types=("manychat",),
        api_endpoints=(),
        extraction_modes=(ExtractionMode.WEBHOOK_INGESTED,),
        cron_schedule=(
            "No cron pull. Data arrives via Manychat webhooks "
            "(see modules/connections marketing_webhooks.py). The "
            "extract_metrics method is a no-op so the scheduler can include "
            "this provider in cache invalidation flows."
        ),
        is_multi_stage=False,
        stages_supported=("capture",),
        has_period_extraction=False,
        channel_outputs=(
            ChannelOutput(
                channel_slug="manychat",
                stage="capture",
                description=(
                    "Conversational entry points (DM triggers, comment "
                    "triggers). Metric values are written by webhook "
                    "handlers, not by this provider."
                ),
                metrics=(),
            ),
        ),
        storage_tables=("official_metrics", "journey_events"),
        known_issues=(
            "Pass-through by design. The fact that ManyChatProvider returns "
            "an empty result is NOT a bug — webhooks populate the metrics "
            "directly. However the audit report from 2026-04-11 incorrectly "
            "flagged this as a stub. The real risk is verifying that the "
            "webhook endpoint is correctly wired in production."
        ),
        last_verified=_LAST_VERIFIED,
    )


def _crm_internal_contract() -> ProviderContract:
    return ProviderContract(
        provider_name="crm_internal",
        display_name="CRM Internal (cold contact metrics from journey_events)",
        status=ProviderStatus.BROKEN,
        module_path="src.modules.analytics.infrastructure.providers.crm_internal_provider",
        class_name="CRMInternalProvider",
        auth_type=AuthType.INTERNAL,
        auth_provider="Reads our own DB via credentials['db_session']",
        required_credentials=("db_session",),
        serves_channel_types=(),  # not exposed via channel_connections
        api_endpoints=(),
        extraction_modes=(ExtractionMode.INTERNAL_DB,),
        cron_schedule="Would run daily but is currently never invoked",
        is_multi_stage=False,
        stages_supported=("attraction",),
        has_period_extraction=False,
        channel_outputs=(
            ChannelOutput(
                channel_slug="cold-contact",
                stage="attraction",
                description=(
                    "Counts of outbound contact attempts and responses from "
                    "journey_events with event_name in {outbound_contact, "
                    "outbound_call, outbound_email} and {outbound_response, "
                    "outbound_reply}."
                ),
                metrics=(
                    MetricMapping(
                        "contacts",
                        "count(OUTBOUND_CONTACT_EVENTS)",
                        "count",
                    ),
                    MetricMapping(
                        "responses",
                        "count(OUTBOUND_RESPONSE_EVENTS)",
                        "count",
                    ),
                ),
            ),
        ),
        storage_tables=("staging_metrics", "official_metrics", "metric_aggregations"),
        known_issues=(
            "BROKEN: requires credentials['db_session'] but neither "
            "etl_service.run_all_providers nor pipeline.py ever passes a DB "
            "session through credentials. The provider returns an empty "
            "result and logs a warning. As a result, cold-contact metrics "
            "never land in official_metrics. Fix requires either passing the "
            "session via pipeline context or refactoring to a separate "
            "extraction path that does not go through ConnectionPort.",
            "There is no row in channel_connections for crm_internal, so "
            "even if the bug above were fixed, run_all_providers would not "
            "discover it. It needs to be invoked as a special case.",
        ),
        last_verified=_LAST_VERIFIED,
    )


EXTRACTION_CONTRACTS: dict[str, ProviderContract] = {
    "meta": _meta_contract(),
    "meta_pixel": _meta_pixel_contract(),
    "google_analytics": _google_analytics_contract(),
    "google_ads": _google_ads_contract(),
    "search_console": _search_console_contract(),
    "youtube": _youtube_contract(),
    "tiktok": _tiktok_contract(),
    "shopify": _shopify_contract(),
    "mailerlite": _mailerlite_contract(),
    "manychat": _manychat_contract(),
    "crm_internal": _crm_internal_contract(),
}


# ---------------------------------------------------------------------------
# Workers / scheduler reference
# ---------------------------------------------------------------------------
#
# Reference for the cron schedule that drives every provider above. Sourced
# from src/workers/settings.py — kept here as docs but the test enforces
# that the scheduler still references the same task names.

WORKER_SCHEDULE_DOC: dict[str, str] = {
    "run_tick_scheduler": (
        "Every minute. Walks every active tenant; if its local time is "
        "exactly 03:00, enqueues run_tenant_extraction(tenant_id, 'all') + "
        "run_campaign_sync(tenant_id, 'meta'). Also detects "
        "weekly/monthly/quarterly period boundaries and enqueues "
        "run_period_extraction for each."
    ),
    "run_tenant_extraction": (
        "Triggered by run_tick_scheduler at 03:00 local. Calls "
        "ETLService.run_all_providers which iterates active connections and "
        "invokes the right provider per channel_type."
    ),
    "run_campaign_sync": (
        "Triggered by run_tick_scheduler. Currently hardcoded to provider="
        "'meta'. Refreshes ad_campaigns/ad_sets/ads/ad_recommendations via "
        "MetaCampaignProvider."
    ),
    "run_period_extraction": (
        "Triggered by run_tick_scheduler when a week/month/quarter boundary "
        "is hit, OR manually via the script in this repo. Calls "
        "ETLService.run_period_extraction which iterates connections that "
        "have has_period_extraction()=True and writes to period_metrics."
    ),
    "run_initial_load": (
        "Triggered by the Connections UI on first connect, or manually via "
        "ARQ enqueue. Loads up to ETLConfig.MAX_LOOKBACK_DAYS (currently 90) "
        "of historical data."
    ),
    "run_mailerlite_etl_sync": (
        "Independent cron — every 6 hours at :15 (00:15, 06:15, 12:15, "
        "18:15 UTC). Refreshes Mailerlite outside the daily 3am window."
    ),
    "run_inactivity_detection": "Daily at 04:00 UTC. CRM scoring batch.",
    "run_frozen_detection": (
        "Every 4 hours at :30 (00:30, 04:30, ..., 20:30 UTC). Sales agent frozen-conversation detector."
    ),
    "cleanup_old_events": "Daily at 03:30 UTC. Trims old copilot events.",
    "poll_domain_verification": ("Every 5 minutes. Polls Cloudflare for tenant_domains DNS status."),
}
