"""Metric Catalog — fuente de verdad semántica para todas las métricas del sistema.

Define qué es cada métrica, cómo agregarla correctamente en períodos multi-día,
y cómo interpretarla para el usuario final.

Clasificación de agregación:
- ADDITIVE: SUM() seguro (clicks, spend, sessions, order_count)
- WEIGHTED_AVERAGE: Requiere denominador (bounceRate ponderado por sessions)
- DERIVED: Recalcular siempre de componentes (CPC = spend/clicks)
- NON_AGGREGABLE: Solo diario; personas únicas no se pueden sumar cross-day
- SNAPSHOT: Último valor del período (active_subscribers es un estado, no flujo)
"""

from __future__ import annotations

from dataclasses import dataclass, field

from luana_core_analytics_engine.domain.enums import AggregationType, MetricUnit


@dataclass(frozen=True)
class MetricDefinition:
    """Defines the semantic contract of a single metric."""

    name: str
    display_name: str
    description: str
    interpretation: str
    unit: MetricUnit  # count, currency, percentage, ratio, seconds, json
    aggregation: AggregationType
    weight_metric: str | None = None  # Para WEIGHTED_AVERAGE: denominador
    formula: str | None = None  # Para DERIVED: expresión legible
    formula_components: tuple[str, ...] = field(
        default_factory=tuple,
    )  # Para DERIVED: nombres de métricas componentes
    is_unique_metric: bool = False  # True = personas únicas (no summable cross-day)
    real_api_name: str | None = None  # Si metric_name difiere del nombre real en la API
    source: str | None = None  # Fuente exacta de la API (endpoint/campo)
    higher_is_better: bool = True
    benchmarks: str | None = None  # Referencia de industria (fuente: MetricHQ/Klipfolio)
    providers: tuple[str, ...] = field(default_factory=tuple)


# ---------------------------------------------------------------------------
# ADDITIVE — SUM() seguro
# ---------------------------------------------------------------------------

_ADDITIVE: list[MetricDefinition] = [
    MetricDefinition(
        name="impressions",
        display_name="Impresiones",
        description="Veces que se mostró tu contenido o anuncio",
        interpretation="Más = mayor visibilidad. No implica personas únicas. impressions ≥ reach siempre.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta", "search_console"),
    ),
    MetricDefinition(
        name="clicks",
        display_name="Clics",
        description="Clics en tu contenido o anuncio",
        interpretation="Más = mayor interés. clicks/impressions = CTR.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta", "google_ads", "tiktok", "search_console"),
    ),
    MetricDefinition(
        name="spend",
        display_name="Inversión",
        description="Gasto publicitario",
        interpretation="Controlar vs presupuesto. spend/conversions = CPA.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.ADDITIVE,
        benchmarks="Referencia inversión publicitaria: B2B 2-5% de revenue, B2C 5-10% (eMarketer).",
        providers=("meta", "google_ads", "tiktok"),
    ),
    MetricDefinition(
        name="conversions",
        display_name="Conversiones",
        description="Acciones de conversión completadas. Meta: solo compras. GA4/GAds: configurado por usuario.",
        interpretation="Meta: compras atribuidas a ads. Si es 0, revisar pixel/tracking.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        benchmarks="Referencia CVR: Search 3.75%, Display 0.77%, Social 1-5%. >5% = excelente.",
        providers=("meta", "google_ads", "tiktok", "google_analytics"),
    ),
    MetricDefinition(
        name="conversion_value",
        display_name="Valor de Conversiones",
        description="Ingreso monetario atribuido a conversiones",
        interpretation="conversion_value / spend = ROAS (Return On Ad Spend).",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.ADDITIVE,
        providers=("google_ads",),
    ),
    MetricDefinition(
        name="sessions",
        display_name="Sesiones",
        description="Visitas al sitio. Un usuario puede tener múltiples sesiones.",
        interpretation="Más = más tráfico. sessions creciendo + users estable = usuarios vuelven (retención).",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        benchmarks="Referencia semanal: B2C 1,850-9,050, B2B 1,020-3,300 según tamaño empresa.",
        providers=("google_analytics",),
    ),
    MetricDefinition(
        name="engagedSessions",
        display_name="Sesiones Comprometidas",
        description="Sesiones con >10s de duración, 2+ pageviews, o una conversión",
        interpretation="engagedSessions / sessions = engagement rate del sitio.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        benchmarks="Referencia: 55-85% de sesiones son engaged. Típico: 60-70%. E-commerce: 70-80%.",
        providers=("google_analytics",),
    ),
    MetricDefinition(
        name="newUsers",
        display_name="Usuarios Nuevos",
        description="Usuarios que visitan el sitio por primera vez",
        interpretation="newUsers / sessions = tasa de adquisición.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("google_analytics",),
    ),
    MetricDefinition(
        name="screenPageViews",
        display_name="Vistas de Página",
        description="Total de páginas vistas (un usuario puede ver múltiples páginas)",
        interpretation="screenPageViews / sessions = profundidad de navegación.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        benchmarks="Referencia: promedio 5 páginas por sesión. B2B: 2, Grocery: 7.",
        providers=("google_analytics",),
    ),
    MetricDefinition(
        name="engagement",
        display_name="Interacciones",
        description="Likes + comments (+ shares en TikTok/FB). Mide resonancia del contenido.",
        interpretation="engagement / reach = engagement rate. Alto = contenido que genera conversación.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        benchmarks="Referencia engagement rate: Facebook 0.08%, Instagram 0.98% (RivalIQ 2021).",
        providers=("meta", "tiktok", "youtube"),
    ),
    MetricDefinition(
        name="video_views",
        display_name="Reproducciones de Video",
        description="Reproducciones totales de video en TikTok organic. Una persona puede ver múltiples veces.",
        interpretation="Más = mayor alcance de contenido. No es comparable con Meta reach (personas únicas).",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("tiktok",),
    ),
    MetricDefinition(
        name="views",
        display_name="Vistas",
        description="Vistas de video en YouTube (reproducciones >30s). No es personas únicas.",
        interpretation="Más = mayor alcance. No es comparable con Meta reach (personas únicas).",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("youtube",),
    ),
    MetricDefinition(
        name="contacts",
        display_name="Contactos",
        description="Intentos de contacto outbound (email, llamada, mensaje directo)",
        interpretation="Mide volumen de prospección. responses / contacts = tasa de respuesta.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("crm_internal",),
    ),
    MetricDefinition(
        name="responses",
        display_name="Respuestas",
        description="Respuestas recibidas a contacto outbound",
        interpretation="responses / contacts = tasa de respuesta.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("crm_internal",),
    ),
    MetricDefinition(
        name="emails_sent",
        display_name="Emails Enviados",
        description="Total de emails enviados en el período",
        interpretation="Línea base para calcular tasas. Alta variabilidad = campañas puntuales.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        benchmarks="Referencia: >50% del presupuesto publicitario se invierte en digital (eMarketer).",
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="unique_opens",
        display_name="Aperturas Únicas",
        description="Emails abiertos (contado por persona única, no por total de aperturas)",
        interpretation="unique_opens / emails_sent = open_rate.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="unique_clicks",
        display_name="Clics Únicos",
        description="Clics en email por persona única",
        interpretation="unique_clicks / emails_sent = click_rate.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="hard_bounces",
        display_name="Rebotes Duros",
        description="Emails no entregados permanentemente (dirección inválida, dominio inexistente)",
        interpretation="Alto = lista de emails sucia. Limpiar lista inmediatamente.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=False,
        benchmarks="Referencia: ~2.5% promedio global (Mailchimp). >5% = limpiar lista urgente.",
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="soft_bounces",
        display_name="Rebotes Suaves",
        description="Emails no entregados temporalmente (buzón lleno, servidor caído)",
        interpretation="Normal si es bajo ocasional. Preocupante si sube sostenidamente.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=False,
        benchmarks="Referencia: ~0.6% promedio global (Mailchimp).",
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="unsubscribes",
        display_name="Desuscripciones",
        description="Personas que se dieron de baja de la lista",
        interpretation="Alto = contenido no relevante o frecuencia excesiva. >0.5% es señal de alarma.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=False,
        benchmarks="Referencia: 0.1-0.3% promedio global. >0.5% = señal de alarma.",
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="spam_reports",
        display_name="Reportes de Spam",
        description="Emails marcados como spam por los destinatarios",
        interpretation="CRÍTICO si >0.1% de sent. Puede afectar deliverability permanentemente.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=False,
        benchmarks="Referencia: debe ser <0.1% de enviados. >0.1% afecta deliverability.",
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="forwards",
        display_name="Reenvíos",
        description="Emails reenviados por los destinatarios",
        interpretation="Señal de contenido valioso. Un forward = amplificación orgánica.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="opens_count",
        display_name="Aperturas Totales",
        description="Total de aperturas de email incluyendo re-aperturas por la misma persona",
        interpretation=(
            "Incluye re-opens. opens_count > unique_opens indica alto interés de "
            "relectura. Útil para medir engagement repetido con el contenido."
        ),
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=True,
        providers=("mailerlite", "mailchimp", "activecampaign"),
    ),
    MetricDefinition(
        name="clicks_count",
        display_name="Clics Totales",
        description="Total de clics en links de email incluyendo re-clics por la misma persona",
        interpretation=(
            "Incluye re-clicks. clicks_count > unique_clicks indica contenido que "
            "se revisita. Útil para medir engagement repetido con CTAs."
        ),
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=True,
        providers=("mailerlite", "mailchimp", "activecampaign"),
    ),
    MetricDefinition(
        name="form_conversions",
        display_name="Conversiones de Formulario",
        description="Formularios de captación completados",
        interpretation="Mide captación directa. form_conversions / form_views = tasa de conversión del form.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        benchmarks="Referencia: tasa conversión promedio 2.4%. Landing optimizada: ~4%.",
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="new_subscribers",
        display_name="Suscriptores Nuevos",
        description="Nuevos suscriptores de email en el período",
        interpretation="Crecimiento de lista. new_subscribers / emails_sent = tasa de crecimiento.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        benchmarks="Referencia: crecimiento de lista saludable 2-5% mensual.",
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="automation_completed",
        display_name="Automatizaciones Completadas",
        description="Flujos de automatización email completados",
        interpretation="Mide engagement con secuencias. automation_completed / emails_sent = tasa de completado.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="revenue",
        display_name="Ingresos Brutos",
        description="total_price de órdenes Shopify (excluye voided y fully refunded)",
        interpretation="Métrica principal de ventas. revenue - discounts - refunds = net_sales.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.ADDITIVE,
        providers=("shopify",),
    ),
    MetricDefinition(
        name="order_count",
        display_name="Órdenes",
        description="Cantidad de órdenes Shopify en el período",
        interpretation="revenue / order_count = AOV. order_count creciendo + revenue estable = AOV bajando.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("shopify",),
    ),
    MetricDefinition(
        name="units_sold",
        display_name="Unidades Vendidas",
        description="Items vendidos (suma de line_items quantity)",
        interpretation="Volumen de producto. units_sold / order_count = items por orden.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("shopify",),
    ),
    MetricDefinition(
        name="total_discounts",
        display_name="Descuentos",
        description="Total de descuentos aplicados en órdenes",
        interpretation="total_discounts / revenue = % descontado. Alto = dependencia de descuentos.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=False,
        providers=("shopify",),
    ),
    MetricDefinition(
        name="total_tax",
        display_name="Impuestos",
        description="Total de impuestos cobrados",
        interpretation="Informativo y contable.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.ADDITIVE,
        providers=("shopify",),
    ),
    MetricDefinition(
        name="net_sales",
        display_name="Ventas Netas",
        description="revenue - discounts - refunds. Ingreso real después de descuentos y reembolsos.",
        interpretation="Más preciso que revenue para P&L. net_sales / order_count = AOV neto.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.ADDITIVE,
        providers=("shopify",),
    ),
    MetricDefinition(
        name="refund_amount",
        display_name="Monto de Reembolsos",
        description="Valor monetario de reembolsos procesados",
        interpretation="refund_amount / revenue = tasa de reembolso monetaria.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=False,
        benchmarks="Referencia: tasa reembolso monetaria típica 1-3%. >5% = problema de calidad.",
        providers=("shopify",),
    ),
    MetricDefinition(
        name="refund_count",
        display_name="Reembolsos",
        description="Cantidad de reembolsos procesados",
        interpretation="refund_count / order_count = tasa de reembolso. >5% = problema de calidad.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=False,
        benchmarks="Referencia: tasa reembolso típica 1-3%. <1% excelente (SaaS). >5% = problema.",
        providers=("shopify",),
    ),
    MetricDefinition(
        name="shipping_revenue",
        display_name="Ingresos por Envío",
        description="Cobros por envío incluidos en las órdenes",
        interpretation="Contribución al margen. shipping_revenue / revenue = % de ingresos de envío.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.ADDITIVE,
        providers=("shopify",),
    ),
    MetricDefinition(
        name="discount_usage_count",
        display_name="Usos de Código de Descuento",
        description="Cantidad de órdenes que usaron un código de descuento",
        interpretation="discount_usage_count / order_count = penetración de descuentos.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("shopify",),
    ),
    MetricDefinition(
        name="count",
        display_name="Cantidad",
        description="Conteo genérico (checkouts iniciados, carritos abandonados). Contexto depende del channel_slug.",
        interpretation="Ver channel_slug para contexto específico.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("shopify",),
    ),
    MetricDefinition(
        name="value",
        display_name="Valor",
        description="Valor monetario genérico (valor de checkout, carrito). Contexto depende del channel_slug.",
        interpretation="Ver channel_slug para contexto específico.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.ADDITIVE,
        providers=("shopify",),
    ),
    MetricDefinition(
        name="pixel_pageviews",
        display_name="Vistas de Página (Pixel)",
        description="Eventos PageView registrados por el Meta Pixel",
        interpretation="Tráfico medido por Pixel. Complementa GA4. Diferencias = bloqueo de adblockers.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta_pixel",),
    ),
    MetricDefinition(
        name="pixel_view_content",
        display_name="ViewContent (Pixel)",
        description="Eventos ViewContent del Meta Pixel (usuario ve producto o contenido específico)",
        interpretation="Usuarios que ven producto/contenido. pixel_view_content / pixel_pageviews = engagement.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta_pixel",),
    ),
    MetricDefinition(
        name="pixel_leads",
        display_name="Leads (Pixel)",
        description="Eventos Lead registrados por el Meta Pixel",
        interpretation="Captación medida por Pixel. Comparar con form_conversions para validar tracking.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta_pixel",),
    ),
    MetricDefinition(
        name="pixel_add_to_cart",
        display_name="AddToCart (Pixel)",
        description="Eventos AddToCart del Meta Pixel",
        interpretation="Intención de compra. pixel_add_to_cart / pixel_view_content = tasa de carrito.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta_pixel",),
    ),
    MetricDefinition(
        name="pixel_purchases",
        display_name="Compras (Pixel)",
        description="Eventos Purchase del Meta Pixel",
        interpretation="Ventas atribuidas via Pixel. pixel_purchases / pixel_add_to_cart = tasa de completado.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta_pixel",),
    ),
    MetricDefinition(
        name="watch_time_minutes",
        display_name="Minutos Vistos",
        description="Tiempo total de visualización en minutos",
        interpretation="Indicador de engagement profundo. Más minutos = más interés.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=True,
        providers=("youtube",),
    ),
    MetricDefinition(
        name="subscribers_gained",
        display_name="Suscriptores Ganados",
        description="Nuevos suscriptores obtenidos en el período",
        interpretation="Crecimiento de la audiencia.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=True,
        providers=("youtube",),
    ),
    MetricDefinition(
        name="comments",
        display_name="Comentarios",
        description="Comentarios recibidos en el período",
        interpretation="Engagement profundo: indica conversación activa con tu audiencia.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=True,
        providers=("youtube",),
    ),
    MetricDefinition(
        name="shares",
        display_name="Compartidos",
        description="Veces que se compartió tu contenido",
        interpretation="Engagement viral: cada share amplifica tu alcance orgánico.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=True,
        providers=("youtube",),
    ),
    MetricDefinition(
        name="subscribers_lost",
        display_name="Suscriptores Perdidos",
        description="Suscriptores perdidos en el período",
        interpretation="Churn de audiencia. Si sube, revisa contenido reciente.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=False,
        providers=("youtube",),
    ),
    MetricDefinition(
        name="card_clicks",
        display_name="Clics en Tarjetas",
        description="Clics en tarjetas informativas de YouTube",
        interpretation="Interés en CTAs dentro del video.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=True,
        providers=("youtube",),
    ),
    MetricDefinition(
        name="card_impressions",
        display_name="Impresiones de Tarjetas",
        description="Veces que se mostraron tarjetas informativas",
        interpretation="Base para calcular CTR de tarjetas.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=True,
        providers=("youtube",),
    ),
    MetricDefinition(
        name="end_screen_clicks",
        display_name="Clics Pantalla Final",
        description="Clics en elementos de pantalla final de YouTube",
        interpretation="Efectividad de CTAs al final del video.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=True,
        providers=("youtube",),
    ),
    MetricDefinition(
        name="end_screen_impressions",
        display_name="Impresiones Pantalla Final",
        description="Veces que se mostraron elementos de pantalla final",
        interpretation="Cuántos viewers llegan al final del video.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=True,
        providers=("youtube",),
    ),
    # ── Instagram Organic (IG Account Insights API) ──
    # ── Meta Ads Expanded ──
    MetricDefinition(
        name="meta_inline_link_clicks",
        display_name="Clics al Destino",
        description="Clics que dirigen al destino del anuncio",
        interpretation="Más preciso que 'clicks' total — excluye clics en perfil/reacciones.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        benchmarks="Referencia: CPC al destino Facebook promedio $1.72 (Wordstream 2020).",
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_outbound_clicks",
        display_name="Clics Salientes",
        description="Clics que salen de Meta (a tu web)",
        interpretation="Tráfico real enviado fuera de Meta. meta_outbound_clicks / impressions = outbound CTR.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_post_engagement",
        display_name="Engagement de Post",
        description="Likes + comments + shares + saves + clics en el anuncio",
        interpretation="Engagement total del ad. Alto = creative resonante.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        benchmarks="Referencia: engagement Facebook 0.08% mediana, Instagram 0.98% (RivalIQ 2021).",
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_leads",
        display_name="Leads",
        description="Leads generados (evento Lead del Pixel o formulario nativo)",
        interpretation="Captación directa. meta_leads / clicks = tasa de conversión a lead.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        benchmarks="Referencia: CPA Facebook promedio $18.68 (Wordstream). Tasa leads/clicks 2-5%.",
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_add_to_cart",
        display_name="Agregar al Carrito",
        description="Productos añadidos al carrito (evento AddToCart del Pixel)",
        interpretation="Intención de compra. meta_add_to_cart / meta_view_content = tasa de carrito.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_initiate_checkout",
        display_name="Checkouts Iniciados",
        description="Checkouts iniciados (evento InitiateCheckout del Pixel)",
        interpretation="Avance en el funnel. meta_initiate_checkout / meta_add_to_cart = tasa de checkout.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_registrations",
        display_name="Registros",
        description="Registros completados (evento CompleteRegistration del Pixel)",
        interpretation="Captación completada. Comparar con meta_leads para ver drop-off.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_view_content",
        display_name="Vistas de Contenido",
        description="Vistas de contenido (evento ViewContent del Pixel)",
        interpretation="Tráfico cualificado que llegó al contenido objetivo.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_search_actions",
        display_name="Búsquedas",
        description="Búsquedas realizadas en tu sitio (evento Search del Pixel)",
        interpretation="Intención de descubrimiento. Alto = usuarios buscan activamente.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_landing_page_views",
        display_name="Vistas de Landing",
        description="Vistas de landing page (cargó completa, no solo clic)",
        interpretation="Más preciso que clicks — excluye rebotes antes de carga completa.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_conversations_started",
        display_name="Conversaciones",
        description="Conversaciones iniciadas en Messenger/IG DM desde el anuncio",
        interpretation="Engagement directo con el negocio. Alto = ad genera intención de contacto.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_link_clicks",
        display_name="Link Clicks",
        description="Clics en links del anuncio (incluye CTA y links en texto)",
        interpretation="Similar a clicks pero solo en links, no en perfil u otros elementos.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_page_engagement",
        display_name="Engagement de Página",
        description="Engagement total en la página de Facebook desde el anuncio",
        interpretation="Incluye likes de página, check-ins, y otras interacciones.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_video_views",
        display_name="Reproducciones de Video",
        description="Reproducciones de video del anuncio (3+ segundos)",
        interpretation="Atención inicial al video. meta_video_views / impressions = tasa de view.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_video_p25",
        display_name="Video 25%",
        description="Videos vistos al 25%",
        interpretation="Retención temprana. meta_video_p25 / meta_video_views = tasa de retención 25%.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_video_p50",
        display_name="Video 50%",
        description="Videos vistos al 50%",
        interpretation="Retención media. Caída grande vs p25 = contenido pierde interés a mitad.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_video_p75",
        display_name="Video 75%",
        description="Videos vistos al 75%",
        interpretation="Retención avanzada. Alto = contenido mantiene atención hasta el final.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_video_p100",
        display_name="Video 100%",
        description="Videos vistos completos",
        interpretation="Completados. meta_video_p100 / meta_video_views = tasa de completado.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_video_30sec",
        display_name="Video 30s+",
        description="Videos con 30+ segundos vistos (o completos si <30s)",
        interpretation="Retención significativa. Umbral estándar de Meta para 'vista'.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_conversion_value",
        display_name="Valor de Conversiones",
        description="Valor monetario de compras atribuidas al anuncio",
        interpretation="meta_conversion_value / spend = ROAS. Principal métrica de retorno.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.ADDITIVE,
        benchmarks="Referencia: conversion_value / spend = ROAS. >3x es excelente.",
        providers=("meta",),
    ),
    MetricDefinition(
        name="ig_views",
        display_name="Vistas",
        description="Veces que tu contenido fue reproducido o mostrado (reemplaza impressions desde API v22.0)",
        interpretation="Más = mayor visibilidad de contenido. Incluye reels, stories y posts.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        real_api_name="views",
        source="IG Account Insights API (metric=views, period=day)",
        providers=("meta",),
    ),
    MetricDefinition(
        name="total_interactions",
        display_name="Interacciones Totales",
        description="Total de likes + comments + shares + saves + replies en posts, stories y reels",
        interpretation="Métrica holística de engagement. total_interactions / reach = engagement rate real.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        source="IG Account Insights API (metric=total_interactions, period=day)",
        providers=("meta",),
    ),
    MetricDefinition(
        name="ig_likes",
        display_name="Likes",
        description="Likes en tus posts, reels y videos a nivel cuenta",
        interpretation="Engagement pasivo. Alto = contenido agradable. Bajo vs shares = contenido no provocativo.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        real_api_name="likes",
        source="IG Account Insights API (metric=likes, period=day)",
        providers=("meta",),
    ),
    MetricDefinition(
        name="ig_comments",
        display_name="Comentarios",
        description="Comentarios en tus posts, reels, videos y lives a nivel cuenta",
        interpretation="Engagement activo. Alto = contenido que genera conversación.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        real_api_name="comments",
        source="IG Account Insights API (metric=comments, period=day)",
        providers=("meta",),
    ),
    MetricDefinition(
        name="ig_shares",
        display_name="Compartidos",
        description="Veces que compartieron tus posts, stories, reels, videos y lives",
        interpretation="Señal de contenido valioso. Un share = amplificación orgánica gratuita.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        real_api_name="shares",
        source="IG Account Insights API (metric=shares, period=day)",
        providers=("meta",),
    ),
    MetricDefinition(
        name="ig_saves",
        display_name="Guardados",
        description="Veces que guardaron tus posts, reels y videos",
        interpretation="Señal de contenido de referencia. Alto saves = contenido educativo valioso.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        real_api_name="saves",
        source="IG Account Insights API (metric=saves, period=day)",
        providers=("meta",),
    ),
    MetricDefinition(
        name="ig_replies",
        display_name="Respuestas a Stories",
        description="Respuestas que recibiste en tus stories",
        interpretation="Engagement íntimo. Alto = conexión personal con audiencia.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        real_api_name="replies",
        source="IG Account Insights API (metric=replies, period=day)",
        providers=("meta",),
    ),
    MetricDefinition(
        name="ig_reposts",
        display_name="Reposts",
        description="Veces que repostearon tus posts, stories, reels y videos",
        interpretation="Amplificación directa en feeds ajenos.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        real_api_name="reposts",
        source="IG Account Insights API (metric=reposts, period=day)",
        providers=("meta",),
    ),
    MetricDefinition(
        name="ig_follows_gained",
        display_name="Seguidores Ganados",
        description="Cuentas nuevas que empezaron a seguirte en el período",
        interpretation="Mide crecimiento bruto. Comparar con ig_follows_lost para ver el neto.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        real_api_name="follows_and_unfollows[FOLLOWER]",
        source="IG Account Insights API (metric=follows_and_unfollows, breakdown=follow_type)",
        providers=("meta",),
    ),
    MetricDefinition(
        name="ig_follows_lost",
        display_name="Seguidores Perdidos",
        description="Cuentas que dejaron de seguirte en el período",
        interpretation="Mide churn de audiencia. Alto = contenido no retiene o desalineado.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        higher_is_better=False,
        real_api_name="follows_and_unfollows[NON_FOLLOWER]",
        source="IG Account Insights API (metric=follows_and_unfollows, breakdown=follow_type)",
        providers=("meta",),
    ),
    MetricDefinition(
        name="ig_follows_and_unfollows",
        display_name="Seguidores Netos",
        description="Crecimiento neto = seguidores ganados − seguidores perdidos",
        interpretation="Positivo = crecimiento neto. Negativo = contenido no retiene.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        real_api_name="follows_and_unfollows",
        source="Derivado de ig_follows_gained − ig_follows_lost",
        providers=("meta",),
    ),
    MetricDefinition(
        name="ig_profile_links_taps",
        display_name="Taps en Perfil",
        description="Taps en tus botones de dirección, llamada, email y texto del perfil",
        interpretation="Intención de contacto directo. Alto = perfil bien configurado.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.ADDITIVE,
        real_api_name="profile_links_taps",
        source="IG Account Insights API (metric=profile_links_taps, period=day)",
        providers=("meta",),
    ),
]

# ---------------------------------------------------------------------------
# WEIGHTED_AVERAGE — Requiere denominador para agregar correctamente
# ---------------------------------------------------------------------------

_WEIGHTED_AVERAGE: list[MetricDefinition] = [
    MetricDefinition(
        name="bounceRate",
        display_name="Tasa de Rebote",
        description="Porcentaje de sesiones de una sola página sin engagement",
        interpretation=">70% = landing page no retiene. Revisar contenido/diseño.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.WEIGHTED_AVERAGE,
        weight_metric="sessions",
        formula="bounced_sessions / sessions × 100",
        higher_is_better=False,
        benchmarks="Referencia: 47% promedio global. B2B: 75-83%. Blogs/news: hasta 90%.",
        providers=("google_analytics",),
    ),
    MetricDefinition(
        name="ctr",
        display_name="CTR",
        description="Click-through rate = clicks / impressions × 100",
        interpretation="<1% en ads = creative/copy no genera interés. >3% = muy bueno.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.WEIGHTED_AVERAGE,
        weight_metric="impressions",
        formula="clicks / impressions × 100",
        benchmarks="Referencia: Display 0.5%, Search 3.2% (WordStream). >3% = excelente.",
        providers=("meta", "google_ads", "search_console"),
    ),
    MetricDefinition(
        name="cpm",
        display_name="CPM",
        description="Costo por 1000 impresiones = (spend / impressions) × 1000",
        interpretation="Alto = audiencia competida o cara. Comparar por industria.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.WEIGHTED_AVERAGE,
        weight_metric="impressions",
        formula="spend / impressions × 1000",
        higher_is_better=False,
        providers=("meta",),
    ),
    MetricDefinition(
        name="open_rate",
        display_name="Tasa de Apertura",
        description="Porcentaje de emails abiertos sobre el total enviado",
        interpretation="<20% = subject lines débiles o lista fría. >40% = excelente.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.WEIGHTED_AVERAGE,
        weight_metric="emails_sent",
        formula="unique_opens / emails_sent × 100",
        benchmarks="Referencia: 18% promedio industrias (Campaign Monitor 2021). >40% = excelente.",
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="click_rate",
        display_name="Tasa de Clics Email",
        description="Porcentaje de clics sobre emails enviados",
        interpretation="<2% = CTAs no claros o contenido no relevante.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.WEIGHTED_AVERAGE,
        weight_metric="emails_sent",
        formula="unique_clicks / emails_sent × 100",
        benchmarks="Referencia: 2.6% promedio global (Campaign Monitor 2021). Rango: 1-4%.",
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="click_to_open_rate",
        display_name="CTOR",
        description="Click-to-open rate = unique_clicks / unique_opens × 100",
        interpretation="Mide calidad del contenido post-apertura. >10% = bueno.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.WEIGHTED_AVERAGE,
        weight_metric="unique_opens",
        formula="unique_clicks / unique_opens × 100",
        benchmarks="Referencia: 14.1% promedio global (Campaign Monitor 2021). >15% = bueno.",
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="averageSessionDuration",
        display_name="Duración Promedio de Sesión",
        description="Duración promedio de sesión en segundos",
        interpretation="<30s = usuarios no encuentran valor. >180s = alto engagement.",
        unit=MetricUnit.SECONDS,
        aggregation=AggregationType.WEIGHTED_AVERAGE,
        weight_metric="sessions",
        formula="total_duration / sessions",
        benchmarks="Referencia: 2-4 min promedio. Mobile: 4min 24s. >3 min = buen engagement.",
        providers=("google_analytics",),
    ),
    MetricDefinition(
        name="abandonment_rate",
        display_name="Tasa de Abandono de Carrito",
        description="Porcentaje de checkouts iniciados que no completaron la compra",
        interpretation="Alto = fricción en el proceso de checkout. Revisar UX y pricing.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.WEIGHTED_AVERAGE,
        weight_metric="count",
        formula="abandoned_count / total_checkout_count × 100",
        higher_is_better=False,
        benchmarks="Referencia: 55-80% rango industria, ~75% promedio. Mobile típicamente más alto.",
        providers=("shopify",),
    ),
    MetricDefinition(
        name="avg_view_duration",
        display_name="Duración Promedio de Vista",
        description="Duración promedio de visualización por vista en segundos",
        interpretation="Indica qué tan atrapante es el contenido.",
        unit=MetricUnit.SECONDS,
        aggregation=AggregationType.WEIGHTED_AVERAGE,
        weight_metric="views",
        higher_is_better=True,
        providers=("youtube",),
    ),
    MetricDefinition(
        name="avg_view_percentage",
        display_name="% Retención Promedio",
        description="Porcentaje promedio del video que los viewers ven",
        interpretation="Indica qué tan enganchante es el contenido. >50% es bueno para videos >10min.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.WEIGHTED_AVERAGE,
        weight_metric="views",
        higher_is_better=True,
        benchmarks="Referencia: >50% es bueno para videos >10 min. Videos cortos (<1 min): >70%.",
        providers=("youtube",),
    ),
    MetricDefinition(
        name="engagementRate",
        display_name="Tasa de Engagement",
        description="Porcentaje de sesiones con interacción significativa",
        interpretation="Sesiones >10s, 2+ pageviews, o una conversión. Recalcular: engagedSessions/sessions.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.WEIGHTED_AVERAGE,
        weight_metric="sessions",
        higher_is_better=True,
        benchmarks="Referencia GA4: >50% saludable. E-commerce: 70-80%. B2B: 75-85%.",
        providers=("google_analytics",),
    ),
    MetricDefinition(
        name="avg_position",
        display_name="Posición Promedio",
        description="Posición promedio en resultados de búsqueda orgánica",
        interpretation="Menor es mejor. <10 = primera página de Google.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.WEIGHTED_AVERAGE,
        weight_metric="impressions",
        higher_is_better=False,
        benchmarks="Referencia: <10 = primera página Google. <3 = posición premium.",
        providers=("search_console",),
    ),
]

# ---------------------------------------------------------------------------
# DERIVED — Recalcular SIEMPRE de componentes (NUNCA sumar)
# ---------------------------------------------------------------------------

_DERIVED: list[MetricDefinition] = [
    MetricDefinition(
        name="cpc",
        display_name="CPC",
        description="Costo por clic = spend / clicks",
        interpretation="Más bajo = más eficiente. cpc subiendo = audiencia más cara o menos relevante.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.DERIVED,
        formula="spend / clicks",
        formula_components=("spend", "clicks"),
        higher_is_better=False,
        benchmarks="Referencia: $2.69 search, $0.63 display (promedio global). Facebook: $1.72.",
        providers=("google_ads",),
    ),
    # ── Meta Ads Derived ──
    MetricDefinition(
        name="meta_cpp",
        display_name="CPP",
        description="Costo por punto de alcance = (spend / reach) × 1000",
        interpretation="Eficiencia de alcance. Comparar vs CPM para ver solapamiento de audiencia.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.DERIVED,
        formula="spend / reach × 1000",
        formula_components=("spend", "reach"),
        higher_is_better=False,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_cost_per_link_click",
        display_name="Costo por Clic al Destino",
        description="Costo por clic que dirige al destino del anuncio",
        interpretation="Más preciso que CPC genérico. Eficiencia de tráfico cualificado.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.DERIVED,
        formula="spend / meta_inline_link_clicks",
        formula_components=("spend", "meta_inline_link_clicks"),
        higher_is_better=False,
        benchmarks="Referencia: CPC link Facebook promedio $1.72 (Wordstream 2020).",
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_cost_per_outbound_click",
        display_name="Costo por Clic Saliente",
        description="Costo por clic que sale de Meta hacia tu destino",
        interpretation="Costo real de enviar tráfico fuera de Meta.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.DERIVED,
        formula="spend / meta_outbound_clicks",
        formula_components=("spend", "meta_outbound_clicks"),
        higher_is_better=False,
        benchmarks="Referencia: similar a CPC link, $1.50-$3.00 rango típico.",
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_cost_per_purchase",
        display_name="Costo por Compra",
        description="Costo por conversión de compra (CPA)",
        interpretation="spend / conversions. Principal métrica de eficiencia de ventas.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.DERIVED,
        formula="spend / conversions",
        formula_components=("spend", "conversions"),
        higher_is_better=False,
        benchmarks="Referencia: CPA Facebook promedio $18.68 (Wordstream 2020, 18 industrias).",
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_cost_per_lead",
        display_name="Costo por Lead",
        description="Costo por lead generado",
        interpretation="spend / meta_leads. Principal métrica de eficiencia de captación.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.DERIVED,
        formula="spend / meta_leads",
        formula_components=("spend", "meta_leads"),
        higher_is_better=False,
        benchmarks="Referencia: CPL Facebook varía por industria. $5-$50 rango típico B2C.",
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_purchase_roas",
        display_name="ROAS",
        description="Return on Ad Spend = meta_conversion_value / spend",
        interpretation=">1 = rentable. >3 = excelente. <1 = perdiendo dinero en ads.",
        unit=MetricUnit.RATIO,
        aggregation=AggregationType.DERIVED,
        formula="meta_conversion_value / spend",
        formula_components=("meta_conversion_value", "spend"),
        higher_is_better=True,
        benchmarks="Referencia: >1x = rentable, >3x = excelente, <1x = perdiendo dinero.",
        providers=("meta",),
    ),
    # ── Instagram Organic Derived ──
    MetricDefinition(
        name="ig_engagement_rate",
        display_name="Tasa de Engagement",
        description="Porcentaje de interacciones sobre vistas totales",
        interpretation="Calidad del contenido orgánico. >0.5% promedio global. >1.2% excelente.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.DERIVED,
        formula="total_interactions / ig_views × 100",
        formula_components=("total_interactions", "ig_views"),
        higher_is_better=True,
        benchmarks="Referencia: 0.50% mediana global (2025). >1.2% = top 25%.",
        providers=(),
    ),
    MetricDefinition(
        name="avg_order_value",
        display_name="Valor Promedio de Orden",
        description="Valor promedio por orden = revenue / order_count",
        interpretation="AOV subiendo = upsell/cross-sell funcionando. Bajando = descuentos excesivos.",
        unit=MetricUnit.CURRENCY,
        aggregation=AggregationType.DERIVED,
        formula="revenue / order_count",
        formula_components=("revenue", "order_count"),
        benchmarks="Referencia: varía por industria. Monitorear tendencia propia; AOV subiendo = upsell funciona.",
        providers=("shopify",),
    ),
    MetricDefinition(
        name="bounce_rate",
        display_name="Tasa de Rebote Email",
        description="Porcentaje de emails rebotados (hard + soft) sobre enviados",
        interpretation=">5% = lista sucia. Limpiar suscriptores inactivos y direcciones inválidas.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.DERIVED,
        formula="(hard_bounces + soft_bounces) / emails_sent × 100",
        formula_components=("hard_bounces", "soft_bounces", "emails_sent"),
        higher_is_better=False,
        benchmarks="Referencia: 0.7% promedio (Campaign Monitor 2020). >5% = lista sucia.",
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="unsubscribe_rate",
        display_name="Tasa de Desuscripción",
        description="Porcentaje de desuscripciones sobre emails enviados",
        interpretation=">0.5% = contenido no alineado con expectativas de la audiencia.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.DERIVED,
        formula="unsubscribes / emails_sent × 100",
        formula_components=("unsubscribes", "emails_sent"),
        higher_is_better=False,
        benchmarks="Referencia: 0.1% promedio (Campaign Monitor 2021). >0.5% = contenido desalineado.",
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="reactivation_rate",
        display_name="Tasa de Reactivación",
        description="Porcentaje de aperturas únicas sobre emails enviados (usado en secuencias de retención)",
        interpretation="Mide recuperación de suscriptores inactivos.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.DERIVED,
        formula="unique_opens / emails_sent × 100",
        formula_components=("unique_opens", "emails_sent"),
        benchmarks="Referencia: similar a open_rate. 18% promedio. Secuencias reactivación: 5-10%.",
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="response_rate",
        display_name="Tasa de Respuesta Outbound",
        description="Porcentaje de respuestas recibidas sobre contactos enviados",
        interpretation="Mide efectividad del outreach. <5% = mensaje o segmentación mejorable.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.DERIVED,
        formula="responses / contacts × 100",
        formula_components=("responses", "contacts"),
        benchmarks="Referencia outbound: 10-15% considerado bueno. <5% = mejorar mensaje/segmentación.",
        providers=(),
    ),
    MetricDefinition(
        name="form_conversion_rate",
        display_name="Tasa de Conversión de Formulario",
        description="Porcentaje de vistas de formulario que resultaron en conversión",
        interpretation="Mide efectividad de formularios de captación.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.DERIVED,
        formula="form_conversions / form_views × 100",
        # form_views is not tracked as a separate metric; cannot auto-recalculate
        formula_components=(),
        benchmarks="Referencia: promedio 2.4%. SaaS: 3-5%. Landing page optimizada: ~4%.",
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="completion_rate",
        display_name="Tasa de Completado de Automatización",
        description="Porcentaje de flujos de automatización completados sobre los disparados",
        interpretation="Mide engagement con secuencias de email. <50% = deserción alta.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.DERIVED,
        formula="completed / triggered × 100",
        # 'triggered' and 'completed' are not tracked as separate metrics; computed at read time
        formula_components=(),
        benchmarks="Referencia: automatización email típica 30-60% completado.",
        providers=(),
    ),
    # ── YouTube Organic Derived ──
    MetricDefinition(
        name="card_click_rate",
        display_name="CTR Tarjetas",
        description="Tasa de clics en tarjetas = card_clicks / card_impressions × 100",
        interpretation="Efectividad de tus CTAs dentro del video. >3% es bueno.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.DERIVED,
        formula="card_clicks / card_impressions × 100",
        formula_components=("card_clicks", "card_impressions"),
        higher_is_better=True,
        benchmarks="Referencia: 1-3% promedio, >7% excelente (YouTube Creator Academy).",
        providers=("youtube",),
    ),
    MetricDefinition(
        name="end_screen_click_rate",
        display_name="CTR Pantalla Final",
        description="Tasa de clics en pantalla final = end_screen_clicks / end_screen_impressions × 100",
        interpretation="Efectividad de CTAs al final del video. Mide retención hasta el final.",
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.DERIVED,
        formula="end_screen_clicks / end_screen_impressions × 100",
        formula_components=("end_screen_clicks", "end_screen_impressions"),
        higher_is_better=True,
        benchmarks="Referencia: 0.5-2% promedio, >5% excelente.",
        providers=("youtube",),
    ),
    # ── Email Marketing Derived (Email Intelligence Hub) ──
    MetricDefinition(
        name="deliverability_rate",
        display_name="Tasa de Entregabilidad",
        description=(
            "Porcentaje de emails efectivamente entregados = "
            "(emails_sent - hard_bounces - soft_bounces) / emails_sent × 100"
        ),
        interpretation=(
            "Mide salud de la infraestructura de envío. <95% indica problemas de "
            "reputación de dominio o lista sucia. >99% = excelente."
        ),
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.DERIVED,
        formula="(emails_sent - hard_bounces - soft_bounces) / emails_sent * 100",
        formula_components=("emails_sent", "hard_bounces", "soft_bounces"),
        higher_is_better=True,
        benchmarks="Referencia: 95% promedio global. >99% excelente. <90% = revisar reputación.",
        providers=(),
    ),
    MetricDefinition(
        name="list_growth_rate",
        display_name="Tasa de Crecimiento de Lista",
        description=(
            "Crecimiento neto de la lista de email = (new_subscribers - unsubscribes) / active_subscribers × 100"
        ),
        interpretation=(
            "Velocidad de crecimiento de la audiencia. Negativo = lista encogiéndose. "
            "3-8% mensual es saludable para creadores."
        ),
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.DERIVED,
        formula="(new_subscribers - unsubscribes) / active_subscribers * 100",
        formula_components=("new_subscribers", "unsubscribes", "active_subscribers"),
        higher_is_better=True,
        benchmarks="Referencia: 1-3% mensual promedio. 3-8% saludable para creadores.",
        providers=(),
    ),
    MetricDefinition(
        name="churn_rate",
        display_name="Tasa de Churn",
        description=("Porcentaje de suscriptores perdidos = unsubscribes / active_subscribers × 100"),
        interpretation=(
            "Velocidad a la que pierdes suscriptores. >2% mensual = contenido o "
            "frecuencia desalineados. Comparar con list_growth_rate para balance neto."
        ),
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.DERIVED,
        formula="unsubscribes / active_subscribers * 100",
        formula_components=("unsubscribes", "active_subscribers"),
        higher_is_better=False,
        benchmarks="Referencia: <0.5% mensual excelente. >2% = problema de retención.",
        providers=(),
    ),
    MetricDefinition(
        name="forward_rate",
        display_name="Tasa de Reenvío",
        description="Porcentaje de emails reenviados = forwards / emails_sent × 100",
        interpretation=(
            "Amplificación orgánica del contenido. Alto = contenido tan valioso que "
            "los suscriptores lo comparten. Señal de viralidad de email."
        ),
        unit=MetricUnit.PERCENTAGE,
        aggregation=AggregationType.DERIVED,
        formula="forwards / emails_sent * 100",
        formula_components=("forwards", "emails_sent"),
        higher_is_better=True,
        benchmarks="Referencia: 0.01-0.05% promedio. >0.15% = contenido viral.",
        providers=(),
    ),
]

# ---------------------------------------------------------------------------
# NON_AGGREGABLE — Solo diario; para rangos → API call o no agregar
# ---------------------------------------------------------------------------

_NON_AGGREGABLE: list[MetricDefinition] = [
    MetricDefinition(
        name="reach",
        display_name="Alcance",
        description=(
            "Personas únicas que vieron tu contenido ese día."
            " NO es summable cross-day (misma persona en lunes y martes = 2 al sumar, pero debería ser 1)."
        ),
        interpretation="Mide amplitud de audiencia. Para períodos >1 día, pedir a la API con el rango completo.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.NON_AGGREGABLE,
        is_unique_metric=True,
        providers=("meta",),
    ),
    MetricDefinition(
        name="users",
        display_name="Usuarios",
        description="Usuarios únicos del sitio ese día. NO summable cross-day.",
        interpretation="Mide audiencia real. Para períodos >1 día, pedir a GA4 con el rango completo.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.NON_AGGREGABLE,
        is_unique_metric=True,
        providers=("google_analytics",),
    ),
    MetricDefinition(
        name="frequency",
        display_name="Frecuencia",
        description=(
            "Promedio de veces que cada persona vio el anuncio = impressions / reach."
            " NO aggregable: depende de reach que tampoco es summable."
        ),
        interpretation=(
            ">3 = fatiga de audiencia, rotar creatives."
            " Para períodos: IMPOSIBLE calcular localmente, requiere API call."
        ),
        unit=MetricUnit.RATIO,
        aggregation=AggregationType.NON_AGGREGABLE,
        is_unique_metric=False,
        higher_is_better=False,
        benchmarks="Referencia: >3 = fatiga de audiencia, rotar creativos. 1-2 ideal para awareness.",
        providers=("meta",),
    ),
    MetricDefinition(
        name="activeUsers",
        display_name="Usuarios Activos",
        description="Usuarios únicos que interactuaron activamente con el sitio",
        interpretation="Métrica de audiencia real. No sumable entre días (se deduplica por rango).",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.NON_AGGREGABLE,
        higher_is_better=True,
        providers=("google_analytics",),
    ),
    MetricDefinition(
        name="repeat_customers",
        display_name="Clientes Recurrentes",
        description="Clientes con más de una orden histórica. Mismo cliente en múltiples días duplica al sumar.",
        interpretation="Para rangos: requiere dedup de customer_ids a nivel DB o query especial.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.NON_AGGREGABLE,
        is_unique_metric=True,
        providers=("shopify",),
    ),
    MetricDefinition(
        name="ig_accounts_engaged",
        display_name="Cuentas que Interactuaron",
        description="Cuentas únicas que interactuaron con tu contenido (incluyendo ads)",
        interpretation="Personas únicas, NO summable cross-day. Para rangos, pedir a la API.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.NON_AGGREGABLE,
        is_unique_metric=True,
        real_api_name="accounts_engaged",
        source="IG Account Insights API (metric=accounts_engaged, period=day)",
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_video_avg_watch_time",
        display_name="Duración Promedio",
        description="Duración promedio de visualización de videos en anuncios (segundos)",
        interpretation="Retención de atención. No summable — es un promedio ponderado por vistas.",
        unit=MetricUnit.SECONDS,
        aggregation=AggregationType.NON_AGGREGABLE,
        providers=("meta",),
    ),
]

# ---------------------------------------------------------------------------
# SNAPSHOT — Último valor del período (no sumar ni promediar)
# ---------------------------------------------------------------------------

_SNAPSHOT: list[MetricDefinition] = [
    MetricDefinition(
        name="active_subscribers",
        display_name="Suscriptores Activos",
        description="Total de suscriptores activos en el momento (snapshot del estado actual)",
        interpretation="Creciente = lista saludable. Decreciente = desuscripciones > nuevos suscriptores.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.SNAPSHOT,
        providers=("mailerlite",),
    ),
    MetricDefinition(
        name="top_pages",
        display_name="Páginas Top",
        description="JSON con las top 10 páginas por vistas en el período",
        interpretation="Muestra qué contenido genera más tráfico.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        providers=("google_analytics",),
    ),
    MetricDefinition(
        name="traffic_sources",
        display_name="Fuentes de Tráfico",
        description="JSON con distribución de tráfico por canal (organic, direct, paid, etc.)",
        interpretation="Diversificación de fuentes = menor riesgo. Dependencia de 1 fuente = vulnerabilidad.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        providers=("google_analytics",),
    ),
    MetricDefinition(
        name="device_split",
        display_name="Dispositivos",
        description="JSON con % de tráfico por dispositivo (mobile, desktop, tablet)",
        interpretation=">70% mobile = asegurarse que el sitio es mobile-first.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        providers=("google_analytics",),
    ),
    MetricDefinition(
        name="search_terms",
        display_name="Términos de Búsqueda",
        description="Términos de búsqueda que activaron los anuncios",
        interpretation="Muestra qué buscan los usuarios que ven tus anuncios.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        providers=("google_ads",),
    ),
    MetricDefinition(
        name="top_queries",
        display_name="Consultas Top",
        description="Top 20 términos de búsqueda orgánica en Google",
        interpretation="Qué buscan los usuarios para encontrar tu sitio.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        providers=("search_console",),
    ),
    # ── Instagram Organic snapshots ──
    MetricDefinition(
        name="ig_followers_count",
        display_name="Seguidores",
        description="Total de seguidores de tu cuenta al momento de la extracción",
        interpretation="Crecimiento de audiencia. Comparar con ig_follows_and_unfollows para velocidad.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.SNAPSHOT,
        source="IG User Node (fields=followers_count)",
        benchmarks="Referencia: crecimiento orgánico IG saludable 1-3% mensual.",
        providers=("meta",),
    ),
    MetricDefinition(
        name="ig_media_count",
        display_name="Publicaciones",
        description="Total de publicaciones en tu cuenta al momento de la extracción",
        interpretation="Indicador de volumen de contenido.",
        unit=MetricUnit.COUNT,
        aggregation=AggregationType.SNAPSHOT,
        source="IG User Node (fields=media_count)",
        providers=("meta",),
    ),
    MetricDefinition(
        name="ig_follower_demographics",
        display_name="Demografía Seguidores",
        description="Distribución por edad, ubicación y género de tus seguidores",
        interpretation="Conocer tu audiencia. Comparar con tu buyer persona.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        source="IG Account Insights API (metric=follower_demographics, period=lifetime)",
        providers=("meta",),
    ),
    MetricDefinition(
        name="ig_engaged_audience_demographics",
        display_name="Demografía Engaged",
        description="Distribución por edad, ubicación y género de cuentas que interactúan",
        interpretation="Tu audiencia activa vs total. Discrepancia = contenido no alineado.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        source="IG Account Insights API (metric=engaged_audience_demographics, period=lifetime)",
        providers=("meta",),
    ),
    # ── Meta Ads Breakdowns (Demographics & Placement) ──
    MetricDefinition(
        name="meta_reach_by_age",
        display_name="Alcance por Edad",
        description="Distribución de alcance por rango de edad",
        interpretation="Identifica qué edades ven tus anuncios. Ajustar targeting si no coincide con buyer persona.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_spend_by_age",
        display_name="Gasto por Edad",
        description="Distribución de gasto publicitario por rango de edad",
        interpretation="Dónde se va tu presupuesto. Optimizar si edades no relevantes consumen budget.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_impressions_by_age",
        display_name="Impresiones por Edad",
        description="Distribución de impresiones por rango de edad",
        interpretation="Volumen de exposición por edad.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_reach_by_gender",
        display_name="Alcance por Género",
        description="Distribución de alcance por género",
        interpretation="Identifica balance de género en tu audiencia publicitaria.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_spend_by_gender",
        display_name="Gasto por Género",
        description="Distribución de gasto publicitario por género",
        interpretation="Verificar que el gasto se alinea con tu audiencia objetivo.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_impressions_by_gender",
        display_name="Impresiones por Género",
        description="Distribución de impresiones por género",
        interpretation="Volumen de exposición por género.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_reach_by_placement",
        display_name="Alcance por Plataforma",
        description="Distribución de alcance por plataforma y posición (Feed, Stories, Reels, etc.)",
        interpretation="Identifica dónde tu contenido tiene más visibilidad.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_spend_by_placement",
        display_name="Gasto por Plataforma",
        description="Distribución de gasto por plataforma y posición",
        interpretation="Optimizar budget entre placements rentables vs costosos.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        providers=("meta",),
    ),
    MetricDefinition(
        name="meta_impressions_by_placement",
        display_name="Impresiones por Plataforma",
        description="Distribución de impresiones por plataforma y posición",
        interpretation="Volumen de exposición por placement.",
        unit=MetricUnit.JSON,
        aggregation=AggregationType.SNAPSHOT,
        providers=("meta",),
    ),
]

# ---------------------------------------------------------------------------
# Catálogo unificado
# ---------------------------------------------------------------------------

METRIC_CATALOG: dict[str, MetricDefinition] = {
    m.name: m for m in [*_ADDITIVE, *_WEIGHTED_AVERAGE, *_DERIVED, *_NON_AGGREGABLE, *_SNAPSHOT]
}


def get_metric_def(name: str) -> MetricDefinition | None:
    """Return the MetricDefinition for a given metric name, or None if not catalogued."""
    return METRIC_CATALOG.get(name)


def is_additive(name: str) -> bool:
    """Return True if the metric can be safely summed across time periods."""
    defn = get_metric_def(name)
    return defn is not None and defn.aggregation == AggregationType.ADDITIVE


def get_non_aggregable_for_provider(provider: str) -> list[str]:
    """Return metric names that require period extraction for a provider.

    These are NON_AGGREGABLE metrics (unique persons, etc.) that cannot be
    summed across days and must be fetched directly for each period.
    """
    return [
        m.name
        for m in METRIC_CATALOG.values()
        if m.aggregation == AggregationType.NON_AGGREGABLE and provider in m.providers
    ]
