"""Offer asset domain entity.

Represents a flyer/video/carousel/doc generated by AI or uploaded by the
user. Pure Pydantic — no framework imports.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any
from uuid import UUID, uuid4

from luana_core_offer_studio.domain.enums import AssetSource, AssetStatus, AssetType
from luana_core_platform.domain.base_entity import BaseEntity
from pydantic import Field

if TYPE_CHECKING:
    from datetime import datetime


class OfferAsset(BaseEntity):
    """Offer Asset.

    Assets live in three visibility buckets, encoded by
    ``(edition_id, shared_across_editions)``:

    ===============================  =================  ====================
    edition_id                       shared_across_...  Where it shows up
    ===============================  =================  ====================
    NULL                             any                Offer-level gallery
    <set>                            False              Only that edition
    <set>                            True               Every edition (shared)
    ===============================  =================  ====================

    The ``is_edition_scoped`` property encodes "this asset belongs to exactly
    one edition" so that the clone flow, listing API, and future UI filters
    never have to re-derive the rule.
    """

    id: UUID = Field(default_factory=uuid4)
    tenant_id: UUID
    offer_id: UUID
    # Nullable: offer-level asset. When set, binds the asset to one edition.
    edition_id: UUID | None = None
    # Promotes an edition-born asset to offer-wide visibility. Ignored
    # when ``edition_id`` is None.
    shared_across_editions: bool = False

    name: str
    type: AssetType
    source: AssetSource
    status: AssetStatus = AssetStatus.DRAFT

    # File references (nullable until processing completes)
    file_url: str | None = None
    thumbnail_url: str | None = None
    mime_type: str | None = None
    size_bytes: int | None = None

    # Type-specific metadata (duration_seconds, slide_count, page_count, ...)
    metadata: dict[str, Any] = Field(default_factory=dict)

    # Source/provenance
    prompt_params: dict[str, Any] | None = None  # populated when source=ai
    editable_in_puck: bool = False  # true only when source=ai

    error_message: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    deleted_at: datetime | None = None

    @property
    def is_edition_scoped(self) -> bool:
        """True iff this asset is visible to exactly one edition."""
        return self.edition_id is not None and not self.shared_across_editions


__all__ = ["OfferAsset"]
