"""Offer asset domain entity.

Represents a flyer/video/carousel/doc generated by AI or uploaded by the
user. Pure Pydantic — no framework imports.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID, uuid4

from pydantic import Field

from src.modules.offer.domain.enums import AssetSource, AssetStatus, AssetType
from src.shared.domain.base_entity import BaseEntity


class OfferAsset(BaseEntity):
    """Offer Asset."""

    id: UUID = Field(default_factory=uuid4)
    tenant_id: UUID
    offer_id: UUID
    name: str
    type: AssetType
    source: AssetSource
    status: AssetStatus = AssetStatus.DRAFT

    # File references (nullable until processing completes)
    file_url: str | None = None
    thumbnail_url: str | None = None
    mime_type: str | None = None
    size_bytes: int | None = None

    # Type-specific metadata (duration_seconds, slide_count, page_count, ...)
    metadata: dict[str, Any] = Field(default_factory=dict)

    # Source/provenance
    prompt_params: dict[str, Any] | None = None  # populated when source=ai
    editable_in_puck: bool = False  # true only when source=ai

    error_message: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    deleted_at: datetime | None = None


__all__ = ["OfferAsset"]
