import type { SectionSchema } from "@/lib/form-runtime/schema";

export const contactSchema: SectionSchema = {
  key: "brand.contact",
  title: "Contacto",
  description: "Canales oficiales y redes sociales.",
  fields: [
    {
      id: "support_email",
      label: "Email de soporte",
      type: "email",
      path: "support_email",
      hint: "Dirección de email para consultas post-venta y soporte al cliente.",
    },
    {
      id: "sales_email",
      label: "Email de ventas",
      type: "email",
      path: "sales_email",
      hint: "Dirección de email para consultas comerciales y leads entrantes.",
    },
    {
      id: "phone",
      label: "Teléfono",
      type: "text",
      path: "phone",
      hint: "Número con código de país. El agente lo comparte si el cliente pide contacto directo.",
    },
    {
      id: "whatsapp",
      label: "WhatsApp",
      type: "text",
      path: "whatsapp",
      hint: "Número de WhatsApp con código de país. Canal preferido en Latam para cerrar ventas.",
    },
    {
      id: "address",
      label: "Dirección",
      type: "textarea",
      path: "address",
      rows: 2,
      hint: "Dirección física o ciudad de operación. Para negocios online puedes poner solo ciudad y país.",
    },
    {
      id: "social_instagram",
      label: "Instagram",
      type: "text",
      path: "social_instagram",
      hint: "Usuario de Instagram (sin @). El agente puede referirlo cuando el lead pide más contenido.",
    },
    {
      id: "social_linkedin",
      label: "LinkedIn",
      type: "url",
      path: "social_linkedin",
      hint: "URL completa del perfil o página de empresa en LinkedIn.",
    },
    {
      id: "social_youtube",
      label: "YouTube",
      type: "url",
      path: "social_youtube",
      hint: "URL del canal de YouTube. El agente lo comparte cuando el lead pide ver más contenido.",
    },
    {
      id: "social_tiktok",
      label: "TikTok",
      type: "text",
      path: "social_tiktok",
      hint: "Usuario de TikTok (sin @). Canal de atracción clave para audiencias menores de 35.",
    },
    {
      id: "social_facebook",
      label: "Facebook",
      type: "text",
      path: "social_facebook",
      hint: "URL o nombre de página de Facebook. Relevante para audiencias 35+ en Latam.",
    },
    {
      id: "social_twitter",
      label: "Twitter / X",
      type: "text",
      path: "social_twitter",
      hint: "Usuario de Twitter/X. Canal de autoridad para consultores, educadores y marcas B2B.",
    },
    {
      id: "testimonials_url",
      label: "URL de testimonios",
      type: "url",
      path: "testimonials_url",
      hint: "Página, Google My Business, Trustpilot o video de reseñas. El agente lo comparte como prueba social.",
    },
  ],
};
