import type { SectionSchema } from "@/lib/form-runtime/schema";

export const identitySchema: SectionSchema = {
  key: "brand.identity",
  title: "Identidad",
  description: "Los cimientos de tu marca. El sales agent usará esto como ancla narrativa.",
  fields: [
    {
      id: "brand_name",
      label: "Nombre",
      type: "text",
      path: "brand_name",
      required: true,
      placeholder: "Ej: Visionarias",
      hint: "El nombre público con el que tus clientes te buscan y te recomiendan.",
    },
    {
      id: "tagline",
      label: "Tagline",
      type: "text",
      path: "tagline",
      hint: "Una línea que resume tu propuesta.",
      placeholder: "Creadoras que viven de lo que aman",
    },
    {
      id: "description",
      label: "Descripción",
      type: "textarea",
      path: "description",
      rows: 4,
      hint: "Qué hace tu marca, para quién y por qué importa.",
    },
    {
      id: "industry",
      label: "Industria",
      type: "text",
      path: "industry",
      placeholder: "Ej: Educación online, E-commerce, Coaching",
      hint: "El sector en el que opera tu negocio. Ayuda al agente a contextualizar tu mercado.",
    },
    {
      id: "voice_tone",
      label: "Tono de voz",
      type: "textarea",
      path: "voice_tone",
      rows: 2,
      hint: "Cómo habla tu marca. El SDR usará este tono en todas sus conversaciones.",
      placeholder: "Ej: Conversacional, aspiracional, directo con toques de humor",
      examples: [
        { brand: "Coach ejecutiva (CDMX)", text: "Directo, cálido, con metáforas de liderazgo. Sin tecnicismos. CTA claro al final de cada mensaje." },
        { brand: "Consultor de marketing (Medellín, CO)", text: "Conversacional, data-driven, ocasionalmente irreverente. Siempre con una cifra o ejemplo concreto." },
        { brand: "Nutricionista online (Lima, PE)", text: "Suave, educativo, sin culpa ni juicio. Evita imperativos bruscos. Abunda en preguntas de reflexión." },
      ],
      formula: {
        template: "<slot>3 adjetivos que describen la personalidad</slot> · No suena a <slot>qué estilo evitas</slot>",
      },
      downstreamUses: [
        { label: "Prompts del agente de ventas" },
        { label: "Copy auto-generado de landings" },
        { label: "Captions de assets sociales" },
      ],
    },
    {
      id: "voice_tone_clone",
      label: "Clonación de estilo (IA)",
      type: "custom",
      path: "voice_tone",
      action: "voice-clone",
      hint: "Pega texto tuyo o sube un archivo. La IA detecta tu tono y lo guarda arriba.",
    },
    {
      id: "website",
      label: "Sitio web",
      type: "url",
      path: "website",
      placeholder: "https://...",
      hint: "URL principal de tu marca. Se usa para auto-completar información y como referencia en conversaciones.",
    },
    {
      id: "founding_year",
      label: "Año de fundación",
      type: "text",
      path: "founding_year",
      placeholder: "2023",
      hint: "Año en que arrancó el negocio. Da contexto de trayectoria al agente.",
    },
    {
      id: "language",
      label: "Idioma principal",
      type: "text",
      path: "language",
      placeholder: "es",
      hint: "ISO 639-1 (2 letras). Idioma en que el agente se comunica por defecto con tus leads.",
    },
    {
      id: "timezone",
      label: "Zona horaria",
      type: "text",
      path: "timezone",
      placeholder: "America/Lima",
      hint: "IANA timezone ID. El agente usa esto para proponer horarios de llamada y respetar tu disponibilidad.",
    },
    {
      id: "smart_fill",
      label: "Auto-completar desde tu web",
      type: "custom",
      path: "brand_name",
      action: "smart-fill",
      hint: "La IA analiza tu sitio y propone valores para los campos vacíos.",
    },
    {
      id: "onboarding_wizard",
      label: "Asistente de configuración inicial",
      type: "custom",
      path: "brand_name",
      action: "onboarding-wizard",
      hint: "Flujo guiado para cargar tu marca desde cero.",
    },
    {
      id: "legal",
      label: "Datos legales",
      type: "custom",
      path: "legal_name",
      action: "legal",
      hint: "Razón social, CIF/RUC, términos y privacidad.",
    },
  ],
};
