import type { SectionSchema } from "@/lib/form-runtime/schema";

export const identitySchema: SectionSchema = {
  key: "brand.identity",
  title: "Identidad",
  description: "Los cimientos de tu marca. El sales agent usará esto como ancla narrativa.",
  fields: [
    {
      id: "brand_name",
      label: "Nombre",
      type: "text",
      path: "brand_name",
      required: true,
      placeholder: "Ej: Visionarias",
      hint: "El nombre público con el que tus clientes te buscan y te recomiendan.",
    },
    {
      id: "tagline",
      label: "Tagline",
      type: "text",
      path: "tagline",
      hint: "Una línea que resume tu propuesta.",
      placeholder: "Creadoras que viven de lo que aman",
    },
    {
      id: "description",
      label: "Descripción",
      type: "textarea",
      path: "description",
      rows: 4,
      hint: "Qué hace tu marca, para quién y por qué importa.",
    },
    {
      id: "industry",
      label: "Industria",
      type: "text",
      path: "industry",
      placeholder: "Ej: Educación online, E-commerce, Coaching",
      hint: "El sector en el que opera tu negocio. Ayuda al agente a contextualizar tu mercado.",
    },
    {
      id: "website",
      label: "Sitio web",
      type: "url",
      path: "website",
      placeholder: "https://...",
      hint: "URL principal de tu marca. Se usa para auto-completar información y como referencia en conversaciones.",
    },
    {
      id: "founding_year",
      label: "Año de fundación",
      type: "text",
      path: "founding_year",
      placeholder: "2023",
      hint: "Año en que arrancó el negocio. Da contexto de trayectoria al agente.",
    },
    {
      id: "language",
      label: "Idioma principal",
      type: "text",
      path: "language",
      placeholder: "es",
      hint: "ISO 639-1 (2 letras). Idioma en que el agente se comunica por defecto con tus leads.",
    },
    {
      id: "timezone",
      label: "Zona horaria",
      type: "text",
      path: "timezone",
      placeholder: "America/Lima",
      hint: "IANA timezone ID. El agente usa esto para proponer horarios de llamada y respetar tu disponibilidad.",
    },
  ],
};
