import type { SectionSchema } from "@/lib/form-runtime/schema";

export const identitySchema: SectionSchema = {
  key: "brand.identity",
  title: "Identidad",
  description: "Los cimientos de tu marca. El sales agent usará esto como ancla narrativa.",
  fields: [
    {
      id: "brand_name",
      label: "Nombre",
      type: "text",
      path: "brand_name",
      required: true,
      placeholder: "Ej: Visionarias",
    },
    {
      id: "tagline",
      label: "Tagline",
      type: "text",
      path: "tagline",
      hint: "Una línea que resume tu propuesta.",
      placeholder: "Creadoras que viven de lo que aman",
    },
    {
      id: "description",
      label: "Descripción",
      type: "textarea",
      path: "description",
      rows: 4,
      hint: "Qué hace tu marca, para quién y por qué importa.",
    },
    {
      id: "industry",
      label: "Industria",
      type: "text",
      path: "industry",
      placeholder: "Ej: Educación online, E-commerce, Coaching",
    },
    {
      id: "voice_tone",
      label: "Tono de voz",
      type: "textarea",
      path: "voice_tone",
      rows: 2,
      hint: "Cómo habla tu marca. El SDR usará este tono en todas sus conversaciones.",
      placeholder: "Ej: Conversacional, aspiracional, directo con toques de humor",
    },
    {
      id: "voice_tone_clone",
      label: "Clonación de estilo (IA)",
      type: "custom",
      path: "voice_tone",
      action: "voice-clone",
      hint: "Pega texto tuyo o sube un archivo. La IA detecta tu tono y lo guarda arriba.",
    },
    {
      id: "website",
      label: "Sitio web",
      type: "url",
      path: "website",
      placeholder: "https://...",
    },
    {
      id: "founding_year",
      label: "Año de fundación",
      type: "text",
      path: "founding_year",
      placeholder: "2023",
    },
    {
      id: "language",
      label: "Idioma principal",
      type: "text",
      path: "language",
      placeholder: "es",
    },
    {
      id: "timezone",
      label: "Zona horaria",
      type: "text",
      path: "timezone",
      placeholder: "America/Lima",
    },
    {
      id: "smart_fill",
      label: "Auto-completar desde tu web",
      type: "custom",
      path: "brand_name",
      action: "smart-fill",
      hint: "La IA analiza tu sitio y propone valores para los campos vacíos.",
    },
    {
      id: "onboarding_wizard",
      label: "Asistente de configuración inicial",
      type: "custom",
      path: "brand_name",
      action: "onboarding-wizard",
      hint: "Flujo guiado para cargar tu marca desde cero.",
    },
    {
      id: "legal",
      label: "Datos legales",
      type: "custom",
      path: "legal_name",
      action: "legal",
      hint: "Razón social, CIF/RUC, términos y privacidad.",
    },
  ],
};
