import type { SectionSchema } from "@/lib/form-runtime/schema";

export const visualsSchema: SectionSchema = {
  key: "brand.visuals",
  title: "Visuales",
  description: "Paleta, tipografía, estilo. Todo lo que hace que tu marca se vea como tu marca.",
  fields: [
    {
      id: "visuals_wizard",
      label: "Wizard completo",
      type: "custom",
      path: "primary_color",
      action: "brand-visuals-wizard",
      hint: "Flujo guiado: sube una URL, extrae colores, tipografías y estilo.",
    },
    {
      id: "theme_injector",
      label: "Inyectar tema a la app",
      type: "custom",
      path: "primary_color",
      action: "theme-injector",
    },
    {
      id: "primary_color",
      label: "Color primario",
      type: "text",
      path: "primary_color",
      placeholder: "#000000",
    },
    { id: "secondary_color", label: "Color secundario", type: "text", path: "secondary_color" },
    { id: "accent_color", label: "Color de acento", type: "text", path: "accent_color" },
    { id: "background_color", label: "Fondo", type: "text", path: "background_color" },
    { id: "surface_color", label: "Superficie", type: "text", path: "surface_color" },
    { id: "text_primary_color", label: "Texto primario", type: "text", path: "text_primary_color" },
    {
      id: "text_secondary_color",
      label: "Texto secundario",
      type: "text",
      path: "text_secondary_color",
    },
    { id: "font_heading", label: "Tipografía de títulos", type: "text", path: "font_heading" },
    { id: "font_body", label: "Tipografía de cuerpo", type: "text", path: "font_body" },
    { id: "font_accent", label: "Tipografía de acento", type: "text", path: "font_accent" },
    { id: "design_style", label: "Estilo de diseño", type: "text", path: "design_style" },
    {
      id: "photography_style",
      label: "Estilo fotográfico",
      type: "textarea",
      path: "photography_style",
      rows: 2,
    },
    { id: "icon_style", label: "Estilo de iconos", type: "text", path: "icon_style" },
    {
      id: "visual_references",
      label: "Referencias visuales",
      type: "textarea",
      path: "visual_references",
      rows: 3,
      hint: "Marcas, moodboards o links que te inspiran.",
    },
    {
      id: "logo_url",
      label: "Logo principal (URL)",
      type: "url",
      path: "logo_url",
    },
    {
      id: "logo_picker",
      label: "Seleccionar logo principal",
      type: "custom",
      path: "logo_url",
      action: "single-image",
    },
    {
      id: "favicon_url",
      label: "Favicon (URL)",
      type: "url",
      path: "favicon_url",
    },
  ],
};
