from __future__ import annotations

from typing import TYPE_CHECKING
from uuid import UUID

from src.modules.crm.domain.lead import Lead, UserProfile
from src.modules.crm.infrastructure.repositories.lead_repository import LeadRepository

if TYPE_CHECKING:
    from sqlalchemy.orm import Session


class LeadService:
    def __init__(self, db: Session) -> None:
        self.db = db
        self.repository = LeadRepository(db)

    def get_lead(self, lead_id: UUID) -> Lead | None:
        return self.repository.get_by_id(lead_id)

    def find_lead_by_channel(
        self,
        channel: str,
        channel_id: str,
        tenant_id: UUID,
    ) -> Lead | None:
        return self.repository.get_by_channel_id(channel, channel_id, tenant_id)

    def create_lead(
        self,
        tenant_id: UUID,
        profile: UserProfile | None = None,
        **channel_ids: str,
    ) -> Lead:
        new_lead = Lead(
            id=UUID(
                int=0,
            ),  # Placeholder, will be generated by DB or Pydantic default if we change it
            tenant_id=tenant_id,
            profile_data=profile or UserProfile(),
            **channel_ids,
        )
        # Note: In Domain Entity, ID is mandatory UUID. In create flow, we usually let DB generate it or generate here.
        import uuid

        new_lead.id = uuid.uuid4()

        return self.repository.create(new_lead)

    def update_lead(self, lead: Lead) -> Lead:
        return self.repository.update(lead)


class PipelineService:
    def __init__(self, db: Session) -> None:
        self.db = db
        self.lead_repo = LeadRepository(db)

    def move_stage(
        self,
        profile_id: UUID,
        new_stage: str,
        admin_user_id: str | None = None,
        note: str = "",
    ) -> None:
        """Move a profile to a new lifecycle stage via manual override.

        Delegates to LifecycleService.force_stage for audit trail and validation.
        """
        from src.modules.crm.application.services.lifecycle_service import (
            LifecycleService,
        )
        from src.modules.crm.domain.enums import LifecycleStage

        stage = LifecycleStage(new_stage)
        svc = LifecycleService(self.db)
        svc.force_stage(
            profile_id=profile_id,
            tenant_id=self.db.info.get("tenant_id") if hasattr(self.db, "info") else None,
            new_stage=stage,
            admin_user_id=admin_user_id,
            note=note,
        )
