import type { StageSummary } from '../types/metrics';

export const STAGE_SUMMARIES: StageSummary[] = [
  {
    id: 'ATRACCION',
    order: 0,
    label: 'Atraccion',
    description: 'Visitantes que llegan a tu ecosistema digital desde todos los canales',
    mainKpi: { label: 'visitantes', value: 45000 },
    secondaryKpi: { label: 'canales activos', value: 8 },
    hasDetail: true,
  },
  {
    id: 'CAPTURA',
    order: 1,
    label: 'Captura',
    description: 'Visitantes que dejan sus datos y se convierten en leads',
    mainKpi: { label: 'leads', value: 8500 },
    secondaryKpi: { label: 'tasa conversion', value: 18.9, unit: '%' },
    hasDetail: true,
  },
  {
    id: 'NUTRICION',
    order: 2,
    label: 'Nutricion',
    description: 'Leads que interactuan con tu contenido y avanzan en el embudo',
    mainKpi: { label: 'MQLs', value: 3200 },
    secondaryKpi: { label: 'engagement rate', value: 37.6, unit: '%' },
    hasDetail: true,
  },
  {
    id: 'OPORTUNIDAD',
    order: 3,
    label: 'Oportunidad',
    description: 'Leads calificados listos para recibir una oferta',
    mainKpi: { label: 'SQLs', value: 850 },
    secondaryKpi: { label: 'pipeline value', value: 425000, unit: '$' },
    hasDetail: true,
  },
  {
    id: 'VENTAS',
    order: 4,
    label: 'Ventas',
    description: 'Oportunidades que se convierten en clientes de pago',
    mainKpi: { label: 'clientes', value: 450 },
    secondaryKpi: { label: 'ticket promedio', value: 2800, unit: '$' },
    hasDetail: true,
  },
  {
    id: 'ADOPCION',
    order: 5,
    label: 'Adopcion',
    description: 'Clientes que usan activamente tu producto o servicio',
    mainKpi: { label: 'activos', value: 400 },
    secondaryKpi: { label: 'activacion', value: 88.9, unit: '%' },
    hasDetail: true,
  },
  {
    id: 'EXPANSION',
    order: 6,
    label: 'Expansion',
    description: 'Clientes que compran mas productos o upgradean',
    mainKpi: { label: 'upsells', value: 120 },
    secondaryKpi: { label: 'revenue expansion', value: 30, unit: '%' },
    hasDetail: false,
  },
  {
    id: 'EVANGELIZACION',
    order: 7,
    label: 'Evangelizacion',
    description: 'Clientes que refieren nuevos prospectos activamente',
    mainKpi: { label: 'referidores', value: 85 },
    secondaryKpi: { label: 'referidos/mes', value: 340 },
    hasDetail: true,
  },
];
